'use client';
import {useEffect,useState} from 'react';
import {getPlatformAuthToken} from '../../lib/magnanimous-session';

const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
type Row=Record<string,any>;
async function read(r:Response){const t=await r.text();try{return JSON.parse(t)}catch{return{detail:t||`Request failed (${r.status})`}}}

export default function WhiteLabelFunnel(){
 const[token,setToken]=useState(''),[clients,setClients]=useState<Row[]>([]),[clientId,setClientId]=useState(''),[funnels,setFunnels]=useState<Row[]>([]),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const[form,setForm]=useState({name:'',slug:'',headline:'',offer:'',cta_label:'Get started',cta_url:'',status:'draft'});
 useEffect(()=>{const t=getPlatformAuthToken();if(!t){location.replace('/login?returnTo=%2Fwhite-label%2Ffunnel');return}setToken(t);start(t)},[]);
 async function request(path:string,t=token,options:RequestInit={}){const h=new Headers(options.headers||{});h.set('Authorization',`Bearer ${t}`);if(options.body&&!h.has('Content-Type'))h.set('Content-Type','application/json');const r=await fetch(`${api}${path}`,{...options,headers:h,cache:'no-store'}),d=await read(r);if(r.status===401){location.replace('/login?returnTo=%2Fwhite-label%2Ffunnel');throw new Error('Sign in required.')}if(!r.ok)throw new Error(d.detail||'Request failed.');return d}
 async function start(t:string){try{const bill=await request('/api/billing/status',t);if(bill.plan!=='agency'&&bill.plan!=='agency_pro'){location.replace('/white-label');return}const c=await request('/api/agency/clients',t);const list=c.clients||[];setClients(list);const first=list[0]?.id||'';setClientId(first);if(first)await loadFunnels(first,t)}catch(e:any){setError(e?.message||'Funnel Builder could not load.')}}
 async function loadFunnels(id=clientId,t=token){if(!id)return;try{const d=await request(`/api/agency/funnels?client_id=${encodeURIComponent(id)}`,t);setFunnels(d.funnels||[])}catch(e:any){setError(e.message)}}
 useEffect(()=>{if(token&&clientId)loadFunnels(clientId,token)},[clientId]);
 async function save(){if(!clientId){setError('Choose a client first.');return}if(!form.name.trim()||!form.slug.trim()){setError('Give the funnel a name and a short URL name.');return}setBusy('save');setError('');setNotice('');try{await request('/api/agency/funnels',token,{method:'POST',body:JSON.stringify({...form,client_id:clientId})});setNotice('Saved. Your funnel is ready in the list.');setForm({name:'',slug:'',headline:'',offer:'',cta_label:'Get started',cta_url:'',status:'draft'});await loadFunnels()}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function status(id:string,next:string){try{await request(`/api/agency/funnels/${id}`,token,{method:'PATCH',body:JSON.stringify({status:next})});setNotice(next==='active'?'Funnel turned on.':'Funnel paused.');await loadFunnels()}catch(e:any){setError(e.message)}}
 return <main className="page">
  <header><a href="/white-label">← White Label Apps</a><span>FUNNEL BUILDER</span><a href="/agency-command">Advanced Agency Command →</a></header>
  <section className="hero"><small>WHITE LABEL APP • SIMPLE MODE</small><h1>Make a funnel in four little steps.</h1><div className="steps"><b>1<span>Pick a client</span></b><b>2<span>Name the page</span></b><b>3<span>Write the offer</span></b><b>4<span>Save it</span></b></div></section>
  {error&&<div className="msg err">{error}</div>}{notice&&<div className="msg ok">{notice}</div>}
  <section className="work"><article className="builder"><small>STEP 1</small><h2>Who is this for?</h2><select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">Choose a client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{!clients.length&&<p className="hint">No client yet? <a href="/bpo-operations">Create one here first.</a></p>}
   <small>STEP 2</small><h2>Name the page</h2><label>Funnel name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Summer Special"/></label><label>Short URL name<input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'-')})} placeholder="summer-special"/></label>
   <small>STEP 3</small><h2>Tell people what you offer</h2><label>Big headline<input value={form.headline} onChange={e=>setForm({...form,headline:e.target.value})} placeholder="Get your free estimate today"/></label><label>Offer / page words<textarea value={form.offer} onChange={e=>setForm({...form,offer:e.target.value})} placeholder="Tell the customer what they get and why they should care."/></label><div className="two"><label>Button words<input value={form.cta_label} onChange={e=>setForm({...form,cta_label:e.target.value})}/></label><label>Button goes to<input value={form.cta_url} onChange={e=>setForm({...form,cta_url:e.target.value})} placeholder="https://…"/></label></div>
   <small>STEP 4</small><h2>Save it</h2><label>Start as<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Draft — keep it off</option><option value="active">Active — turn it on</option><option value="paused">Paused</option></select></label><button className="save" onClick={save} disabled={busy==='save'}>{busy==='save'?'Saving…':'Save my funnel →'}</button><p className="hint">Custom-domain publishing only becomes live after the domain and required permissions are really connected. The platform does not pretend an unconnected domain is live.</p></article>
   <article className="list"><div><small>SAVED FUNNELS</small><h2>{funnels.length} for this client</h2></div>{funnels.length===0?<div className="empty">Nothing here yet. Fill the four steps and press Save.</div>:funnels.map(f=><section key={f.id}><div><b>{f.name}</b><span>/{f.slug} • {f.status}</span><p>{f.headline||'No headline yet'}</p><small>{Number(f.visits||0)} visits • {Number(f.leads||0)} leads</small></div><aside><button onClick={()=>status(f.id,'active')}>Turn on</button><button className="pause" onClick={()=>status(f.id,'paused')}>Pause</button></aside></section>)}</article>
  </section>
  <style jsx>{`
  *{box-sizing:border-box}.page{min-height:100vh;background:#05080f;color:#f1f8ff;font-family:Inter,system-ui,sans-serif;padding:22px 26px 70px;background-image:radial-gradient(circle at 80% 0,rgba(117,80,255,.18),transparent 30%)}header,.hero,.msg,.work{max-width:1260px;margin-left:auto;margin-right:auto}header{display:flex;justify-content:space-between;color:#839bb0;font-size:10px;letter-spacing:.12em}header a{color:#89e8ff;text-decoration:none}.hero{padding:52px 0 25px}.hero small,.builder>small,.list>div small{color:#8be9ff;font-size:9px;letter-spacing:.16em;font-weight:900}.hero h1{font-size:clamp(42px,6vw,72px);line-height:.95;margin:8px 0 23px}.steps{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.steps b{border:1px solid #334560;border-radius:14px;padding:13px;color:#bbaaff;font-size:21px;background:#0a111d}.steps span{display:block;color:#95a8ba;font-size:9px;letter-spacing:.07em;margin-top:5px}.msg{padding:11px 13px;border-radius:10px;margin-top:9px}.err{border:1px solid #63343b;background:#201014;color:#ffb7c0}.ok{border:1px solid #285f4a;background:#091b15;color:#8df0c2}.work{display:grid;grid-template-columns:1fr 1fr;gap:12px}.builder,.list{border:1px solid #27384f;border-radius:20px;background:#08101a;padding:22px}.builder h2{font-size:22px;margin:5px 0 10px}.builder>small{display:block;margin-top:23px}.builder>small:first-child{margin-top:0}label{display:grid;gap:5px;color:#91a5b8;font-size:10px;margin:9px 0}input,textarea,select{width:100%;border:1px solid #32465e;border-radius:10px;background:#050a11;color:#f4f9ff;padding:12px;font:inherit}textarea{min-height:130px;resize:vertical}.two{display:grid;grid-template-columns:1fr 1fr;gap:8px}.save{width:100%;border:0;border-radius:11px;background:linear-gradient(90deg,#73e8ff,#a389ff);color:#071117;padding:13px;font-weight:950;cursor:pointer;margin-top:8px}.save:disabled{opacity:.5}.hint{color:#72899c;font-size:10px;line-height:1.5}.hint a{color:#7ce4fb}.list>div h2{margin:5px 0 12px}.list>section{border-top:1px solid #1c2b3b;padding:15px 0;display:grid;grid-template-columns:1fr auto;gap:12px}.list b{display:block;font-size:15px}.list span{display:block;color:#8298aa;font-size:9px;margin-top:3px}.list p{color:#a5b5c4;font-size:11px}.list section small{color:#637c8e;font-size:9px}.list aside{display:flex;gap:5px;align-items:start}.list button{border:1px solid #386078;background:#0c2633;color:#a6edff;border-radius:8px;padding:8px 9px;font-size:9px;cursor:pointer}.list .pause{border-color:#554869;background:#211b2d;color:#d0bfff}.empty{min-height:300px;display:grid;place-items:center;text-align:center;color:#61798b}@media(max-width:800px){.page{padding:18px 14px 60px}.work{grid-template-columns:1fr}.steps{grid-template-columns:1fr 1fr}.two{grid-template-columns:1fr}header span{display:none}.list>section{grid-template-columns:1fr}.list aside{margin-top:4px}}
  `}</style>
 </main>
}
