'use client';

import { FormEvent, useEffect, useState } from 'react';
import styles from '../sim/sim.module.css';

const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
async function parse(response:Response){const text=await response.text();try{return JSON.parse(text)}catch{return{detail:text||`Request failed (${response.status})`}}}

export default function TelecomSecurityPage(){
 const[token,setToken]=useState('');const[error,setError]=useState('');const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);
 const[customerId,setCustomerId]=useState('');const[lineId,setLineId]=useState('');const[swapType,setSwapType]=useState('sim_swap');const[verificationRef,setVerificationRef]=useState('');const[swapConfirmed,setSwapConfirmed]=useState(false);
 const[portCustomerId,setPortCustomerId]=useState('');const[portLineId,setPortLineId]=useState('');const[portAuthRef,setPortAuthRef]=useState('');const[portConfirmed,setPortConfirmed]=useState(false);
 useEffect(()=>{const saved=localStorage.getItem('magnanimous_admin_token')||localStorage.getItem('odin_admin_token')||localStorage.getItem('iam_account_token')||'';if(!saved){location.replace(`/login?returnTo=${encodeURIComponent('/telecom/security')}`);return}setToken(saved)},[]);
 async function call(body:Record<string,unknown>){const response=await fetch(`${api}/api/telecom/operations/service-orders`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await parse(response);if(!response.ok)throw new Error(data.detail||'Secure line-change request failed.');return data}
 async function submitSwap(event:FormEvent){event.preventDefault();setBusy(true);setError('');setNotice('');try{const result=await call({customer_id:customerId,line_id:lineId,order_type:swapType,identity_verification_reference:verificationRef,confirm_sim_swap_security_review:swapConfirmed,payload:{security_class:'sim_swap_step_up',verification_reference:verificationRef}});setNotice(`Secure ${swapType==='esim_swap'?'eSIM':'SIM'} swap order ${result.id} acknowledged.`);setVerificationRef('');setSwapConfirmed(false)}catch(caught:any){setError(caught?.message||'Unable to create secure SIM swap order.')}finally{setBusy(false)}}
 async function submitPort(event:FormEvent){event.preventDefault();setBusy(true);setError('');setNotice('');try{const result=await call({customer_id:portCustomerId,line_id:portLineId,order_type:'port_out',porting_authorization_reference:portAuthRef,confirm_port_out_authorization:portConfirmed,payload:{security_class:'port_out_authorized',authorization_reference:portAuthRef}});setNotice(`Secure port-out order ${result.id} acknowledged.`);setPortAuthRef('');setPortConfirmed(false)}catch(caught:any){setError(caught?.message||'Unable to create secure port-out order.')}finally{setBusy(false)}}
 return <main className={styles.shell}>
  <header className={styles.header}><nav><a href='/telecom'>← TELECOM</a><a href='/telecom/operations'>OPERATIONS</a><a href='/telecom/sim'>SIM + eSIM</a></nav><p className={styles.eyebrow}>MAGNANIMOUS TELECOM · HIGH-RISK LINE CHANGES</p><h1>Secure <em>Line Changes</em></h1><p>SIM swaps, eSIM swaps and port-outs require step-up verification before fulfillment. Magnanimous stores an opaque verification or authorization reference—not copies of identity documents in this workflow.</p></header>
  {error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}
  <section className={styles.grid}>
   <form className={styles.card} onSubmit={submitSwap}><small>SIM TAKEOVER PROTECTION</small><h2>Secure SIM/eSIM swap</h2><label>Customer ID<input required value={customerId} onChange={e=>setCustomerId(e.target.value)} placeholder='Magnanimous customer ID'/></label><label>Line ID<input required value={lineId} onChange={e=>setLineId(e.target.value)} placeholder='Magnanimous line ID'/></label><label>Swap type<select value={swapType} onChange={e=>setSwapType(e.target.value)}><option value='sim_swap'>Physical SIM swap</option><option value='esim_swap'>eSIM swap</option></select></label><label>Identity verification reference<input required value={verificationRef} onChange={e=>setVerificationRef(e.target.value)} placeholder='Opaque verified-case/reference ID'/></label><label><input type='checkbox' checked={swapConfirmed} onChange={e=>setSwapConfirmed(e.target.checked)}/> I confirm the subscriber identity/security review is complete.</label><button disabled={busy||!customerId||!lineId||!verificationRef||!swapConfirmed}>SUBMIT SECURE SWAP</button></form>
   <form className={styles.card} onSubmit={submitPort}><small>NUMBER TAKEOVER PROTECTION</small><h2>Secure port-out</h2><label>Customer ID<input required value={portCustomerId} onChange={e=>setPortCustomerId(e.target.value)} placeholder='Magnanimous customer ID'/></label><label>Line ID<input required value={portLineId} onChange={e=>setPortLineId(e.target.value)} placeholder='Magnanimous line ID'/></label><label>Port authorization reference<input required value={portAuthRef} onChange={e=>setPortAuthRef(e.target.value)} placeholder='Opaque authorization/reference ID'/></label><label><input type='checkbox' checked={portConfirmed} onChange={e=>setPortConfirmed(e.target.checked)}/> I confirm the subscriber authorized this port-out request.</label><button disabled={busy||!portCustomerId||!portLineId||!portAuthRef||!portConfirmed}>SUBMIT SECURE PORT-OUT</button></form>
  </section>
  <section className={styles.guardrail}><h2>Why this is separate</h2><p>A phone number can control password resets, OTPs and financial-account access. Magnanimous treats a SIM/eSIM swap or port-out as a security-sensitive subscriber action, not a routine plan change. The carrier or regulator may require additional identity, SIM-registration, porting or account validation before the order can complete.</p></section>
 </main>
}
