"""Ports keep databases, realtime transports, push networks and call rails replaceable."""
from typing import Protocol
from .domain import Conversation, Message, Receipt


class ConversationStore(Protocol):
    async def create_conversation(self, conversation: Conversation) -> Conversation: ...
    async def get_conversation(self, conversation_id: str) -> Conversation | None: ...
    async def save_message(self, message: Message) -> Message: ...
    async def list_messages(self, conversation_id: str, limit: int = 50) -> list[Message]: ...
    async def save_receipt(self, receipt: Receipt) -> None: ...


class RealtimePublisher(Protocol):
    async def publish(self, user_ids: tuple[str, ...], event: dict) -> None: ...


class CallSignalingPort(Protocol):
    async def create_session(self, caller_id: str, callee_id: str, media: str) -> dict: ...


class TelecomCallPort(Protocol):
    async def place_authorized_pstn_call(self, caller_id: str, destination: str) -> dict: ...
