'use client';
import {useEffect,useState} from 'react';
import {getPlatformAuthToken} from '../../lib/magnanimous-session';

const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
type Client={id:string;name:string};
type Connection={external_account_id:string;display_name:string};
type Message={id:string;sender:string;customer_text:string;suggested_text:string;received_at:number;reply_status:string;reply_text:string};
async function read(r:Response){const raw=await r.text();try{return JSON.parse(raw)}catch{return{detail:raw||`Request failed (${r.status})`}}}

export default function WhatsAppInbox(){
 const[token,setToken]=useState(''),[clients,setClients]=useState<Client[]>([]),[client,setClient]=useState(''),[connections,setConnections]=useState<Connection[]>([]),[connection,setConnection]=useState(''),[phone,setPhone]=useState(''),[routes,setRoutes]=useState<any[]>([]),[messages,setMessages]=useState<Message[]>([]),[reply,setReply]=useState<Record<string,string>>({}),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function request(path:string,t=token,options:RequestInit={}){
  const r=await fetch(`${api}${path}`,{...options,headers:{Authorization:`Bearer ${t}`,...(options.body?{'Content-Type':'application/json'}:{})},cache:'no-store'}),d=await read(r);
  if(!r.ok)throw new Error(d.detail||d.error||`Request failed (${r.status})`);return d;
 }
 async function refresh(t=token,c=client){if(!t||!c)return;try{const [inbox,route]=await Promise.all([request(`/api/white-label/native/whatsapp/inbox?client_id=${encodeURIComponent(c)}`,t),request('/api/white-label/native/whatsapp/routes',t)]);setMessages(inbox.messages||[]);setRoutes((route.routes||[]).filter((x:any)=>x.client_id===c))}catch(e:any){setNotice(e.message)}}
 useEffect(()=>{const t=getPlatformAuthToken();if(!t){location.replace('/login?returnTo=%2Fwhite-label%2Fwhatsapp');return}setToken(t);Promise.all([request('/api/agency/clients',t),request('/api/integrations',t)]).then(([c,i])=>{setClients(c.clients||[]);setClient(c.clients?.[0]?.id||'');const linked=i.integrations?.find((x:any)=>x.id==='whatsapp')?.connected||[];setConnections(linked);setConnection(linked[0]?.external_account_id||'')}).catch(e=>setNotice(e.message))},[]);
 useEffect(()=>{refresh()},[client,token]);
 async function connect(){setBusy(true);setNotice('');try{await request('/api/white-label/native/whatsapp/routes',token,{method:'POST',body:JSON.stringify({phone_number_id:phone,client_id:client,integration_external_account_id:connection})});setPhone('');setNotice('Verified. Messages from this business number will appear in this client inbox after the Meta webhook is configured.');await refresh()}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}
 async function send(id:string){const text=(reply[id]||'').trim();if(!text)return setNotice('Review and enter a reply first.');setBusy(true);setNotice('');try{await request(`/api/white-label/native/whatsapp/reply/${encodeURIComponent(id)}`,token,{method:'POST',body:JSON.stringify({text})});setNotice('WhatsApp confirmed the reply was sent.');await refresh()}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}
 return <main className="wa"><a href="/white-label">← White Label</a><h1>WhatsApp Product Inbox</h1><p>Magnanimous keeps each customer conversation with its client. Replies are drafts until you approve them. You need an official Meta WhatsApp Business connection.</p>
 <section><h2>Connect a business number</h2><p>First connect WhatsApp in <a href="/connections">Connections</a>. In Meta, set this domain’s <code>/api/white-label/native/whatsapp/webhook</code> as the callback and subscribe to messages. Save the same webhook verification token in Owner Integrations. Only a number verified through your connected account can be routed.</p><label>Client <select value={client} onChange={e=>setClient(e.target.value)}><option value="">Choose a client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Connected WhatsApp account <select value={connection} onChange={e=>setConnection(e.target.value)}><option value="">Choose an account</option>{connections.map(c=><option key={c.external_account_id} value={c.external_account_id}>{c.display_name}</option>)}</select></label><label>Business phone number ID from Meta <input value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,''))} placeholder="Meta phone_number_id"/></label><button disabled={busy||!client||!connection||!phone} onClick={connect}>Verify and route number</button>{routes.map(r=><p key={r.phone_number_id}>✓ Routed number ID {r.phone_number_id}</p>)}</section>
 {notice&&<p role="status" className="notice">{notice}</p>}
 <section><div className="row"><h2>Questions awaiting review</h2><button disabled={!client||busy} onClick={()=>refresh()}>Refresh inbox</button></div>{messages.map(m=><article key={m.id}><small>{new Date(m.received_at*1000).toLocaleString()} · {m.reply_status}</small><h3>Customer: {m.sender}</h3><p>{m.customer_text}</p>{m.reply_status==='review'?<><label>Magnanimous catalog-grounded draft. Edit before sending.<textarea value={reply[m.id]??m.suggested_text} onChange={e=>setReply({...reply,[m.id]:e.target.value})}/></label><button disabled={busy} onClick={()=>send(m.id)}>Send reviewed reply</button></>:<p>Reply: {m.reply_text||'Delivery needs manual review in your connected account.'}</p>}</article>)}{!messages.length&&<p>No messages yet. Check the official Meta webhook subscription and client number routing.</p>}</section>
 <footer>This inbox does not send automatically, invent product prices, or start conversations outside Meta’s permitted service window. Media and calls need separate review.</footer><style jsx>{`
 .wa{min-height:100vh;background:#06131b;color:#e7f8ff;font:15px system-ui,sans-serif;padding:24px;max-width:850px;margin:auto}a{color:#82e0ff}h1{font-size:clamp(30px,5vw,52px)}p,footer{color:#a1bac5;line-height:1.55}section,article{border:1px solid #2a5064;background:#0b202b;border-radius:14px;padding:20px;margin:20px 0}article{margin:12px 0}label{display:grid;gap:7px;margin:12px 0;color:#d6eaf3}input,select,textarea{background:#06131b;color:white;border:1px solid #315b6e;border-radius:8px;padding:11px;font:inherit}textarea{min-height:95px}button{border:0;border-radius:8px;padding:10px 14px;background:#79daf5;color:#05121a;font-weight:800;cursor:pointer}button:disabled{opacity:.5;cursor:not-allowed}small{color:#8dddcf}.row{display:flex;align-items:center;justify-content:space-between;gap:15px}.notice{color:#afe9ed}footer{font-size:12px;margin:26px 0}@media(max-width:650px){.row{display:block}.wa{padding:14px}}
 `}</style></main>
}
