'use client';
import {useEffect,useState} from 'react';
import {getPlatformAuthToken} from '../lib/magnanimous-session';

const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
type Connection={id:string;name:string;configured:boolean;connected:boolean;display_name?:string;external_id?:string;expires_at?:number|null;approval?:string};
async function read(r:Response){const t=await r.text();try{return JSON.parse(t)}catch{return{detail:t||`Request failed (${r.status})`}}}

export default function SocialConnectPage(){
 const[token,setToken]=useState(''),[connections,setConnections]=useState<Connection[]>([]),[role,setRole]=useState(''),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const[videoUrl,setVideoUrl]=useState(''),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[privacy,setPrivacy]=useState('private'),[linkedinText,setLinkedinText]=useState(''),[tiktokPrivacy,setTiktokPrivacy]=useState('SELF_ONLY');
 const[tiktokKey,setTiktokKey]=useState(''),[tiktokSecret,setTiktokSecret]=useState(''),[linkedinId,setLinkedinId]=useState(''),[linkedinSecret,setLinkedinSecret]=useState('');

 useEffect(()=>{const t=getPlatformAuthToken();if(!t){location.replace('/login');return}setToken(t);void load(t);const q=new URLSearchParams(location.search);const connected=q.get('connected'),e=q.get('error');if(connected)setNotice(`${connected} connected successfully.`);if(e)setError(e);if(connected||e)history.replaceState({},'',location.pathname)},[]);
 async function load(t=token){
  try{const [cr,me]=await Promise.all([fetch(`${api}/api/social-connect/connections`,{headers:{Authorization:`Bearer ${t}`},cache:'no-store'}),fetch(`${api}/api/auth/me`,{headers:{Authorization:`Bearer ${t}`},cache:'no-store'})]);const cd=await read(cr),md=await read(me);if(!cr.ok)throw new Error(cd.detail||'Could not load social connections.');setConnections(cd.connections||[]);setRole(md?.user?.role||'')}catch(e:any){setError(e?.message||'Could not load social connections.')}
 }
 async function connect(id:string){setBusy(`connect-${id}`);setError('');setNotice('');try{const r=await fetch(`${api}/api/social-connect/${id}/start`,{method:'POST',headers:{Authorization:`Bearer ${token}`}}),d=await read(r);if(!r.ok)throw new Error(d.detail||`${id} connection could not start.`);if(!d.url)throw new Error('Authorization URL was not returned.');location.href=d.url}catch(e:any){setError(e?.message||'Connection could not start.');setBusy('')}}
 async function disconnect(id:string){setBusy(`disconnect-${id}`);setError('');try{const r=await fetch(`${api}/api/social-connect/${id}`,{method:'DELETE',headers:{Authorization:`Bearer ${token}`}}),d=await read(r);if(!r.ok)throw new Error(d.detail||'Disconnect failed.');setNotice(`${id} disconnected.`);await load()}catch(e:any){setError(e?.message||'Disconnect failed.')}finally{setBusy('')}}
 async function saveDeveloperCredentials(){setBusy('credentials');setError('');setNotice('');try{const values:Record<string,string>={};if(tiktokKey.trim())values.TIKTOK_CLIENT_KEY=tiktokKey.trim();if(tiktokSecret.trim())values.TIKTOK_CLIENT_SECRET=tiktokSecret.trim();if(linkedinId.trim())values.LINKEDIN_CLIENT_ID=linkedinId.trim();if(linkedinSecret.trim())values.LINKEDIN_CLIENT_SECRET=linkedinSecret.trim();const r=await fetch(`${api}/api/social-connect/credentials`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({values})}),d=await read(r);if(!r.ok)throw new Error(d.detail||'Credentials could not be saved.');setTikTokFields();setNotice('Developer credentials saved encrypted in the platform vault.');await load()}catch(e:any){setError(e?.message||'Credentials could not be saved.')}finally{setBusy('')}}
 function setTikTokFields(){setTiktokKey('');setTiktokSecret('');setLinkedinId('');setLinkedinSecret('')}
 async function publish(provider:string){setBusy(`publish-${provider}`);setError('');setNotice('');try{let payload:any={};if(provider==='youtube')payload={video_url:videoUrl,title,description,privacy_status:privacy,made_for_kids:false};else if(provider==='tiktok')payload={video_url:videoUrl,title,privacy_level:tiktokPrivacy,explicit_consent:true};else payload={text:linkedinText,explicit_consent:true};const r=await fetch(`${api}/api/social-connect/${provider}/publish`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await read(r);if(!r.ok)throw new Error(d.detail||`${provider} publish failed.`);setNotice(provider==='youtube'&&d.url?`Published to YouTube: ${d.url}`:`${provider} publish request accepted successfully.`)}catch(e:any){setError(e?.message||'Publish failed.')}finally{setBusy('')}}
 const by=(id:string)=>connections.find(x=>x.id===id);
 return <main className="page">
  <header><a href="/social-media">← Social Studio</a><span>MAGNANIMOUS SOCIAL NETWORK</span></header>
  <section className="hero"><small>OFFICIAL API CONNECTIONS</small><h1>Connect. Authorize. Publish.</h1><p>Magnanimous uses each platform’s official authorization flow. Nothing is posted until the account owner authorizes the connection and starts a publish action.</p></section>
  {notice&&<div className="notice">{notice}</div>}{error&&<div className="error">{error}</div>}
  <section className="cards">{connections.map(c=><article key={c.id}><div className="top"><div><small>{c.configured?'APP READY':'APP SETUP REQUIRED'}</small><h2>{c.name}</h2></div><b className={c.connected?'connected':'off'}>{c.connected?'CONNECTED':'NOT CONNECTED'}</b></div>{c.connected?<><p>Authorized as <strong>{c.display_name||'Connected account'}</strong>.</p><button className="secondary" disabled={!!busy} onClick={()=>disconnect(c.id)}>{busy===`disconnect-${c.id}`?'Disconnecting…':'Disconnect'}</button></>:<><p>{c.approval}</p><button disabled={!!busy||!c.configured} onClick={()=>connect(c.id)}>{busy===`connect-${c.id}`?'Opening authorization…':c.configured?`Connect ${c.name}`:'Developer app credentials required'}</button></>}</article>)}</section>
  {role==='owner'&&connections.some(c=>!c.configured&&['tiktok','linkedin'].includes(c.id))&&<section className="owner"><small>OWNER SETUP</small><h2>TikTok / LinkedIn developer credentials</h2><p>These values come from developer apps you own. Secrets are encrypted before storage and are never displayed again.</p><div className="fields"><input value={tiktokKey} onChange={e=>setTiktokKey(e.target.value)} placeholder="TikTok Client Key"/><input type="password" value={tiktokSecret} onChange={e=>setTiktokSecret(e.target.value)} placeholder="TikTok Client Secret"/><input value={linkedinId} onChange={e=>setLinkedinId(e.target.value)} placeholder="LinkedIn Client ID"/><input type="password" value={linkedinSecret} onChange={e=>setLinkedinSecret(e.target.value)} placeholder="LinkedIn Client Secret"/></div><button disabled={busy==='credentials'} onClick={saveDeveloperCredentials}>{busy==='credentials'?'Saving encrypted…':'Save developer credentials'}</button></section>}
  <section className="publish"><div><small>VIDEO SOURCE</small><h2>YouTube / TikTok</h2><p>Use a public HTTPS video URL generated by your Video Studio or another source you control.</p><input value={videoUrl} onChange={e=>setVideoUrl(e.target.value)} placeholder="https://…/video.mp4"/><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Video title / TikTok caption"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="YouTube description"/><div className="row"><select value={privacy} onChange={e=>setPrivacy(e.target.value)}><option value="private">YouTube private</option><option value="unlisted">YouTube unlisted</option><option value="public">YouTube public</option></select><button disabled={!by('youtube')?.connected||!!busy||!videoUrl.trim()} onClick={()=>publish('youtube')}>{busy==='publish-youtube'?'Uploading…':'Publish to YouTube'}</button></div><div className="row"><select value={tiktokPrivacy} onChange={e=>setTiktokPrivacy(e.target.value)}><option value="SELF_ONLY">TikTok private</option><option value="MUTUAL_FOLLOW_FRIENDS">Friends</option><option value="FOLLOWER_OF_CREATOR">Followers</option><option value="PUBLIC_TO_EVERYONE">Public</option></select><button disabled={!by('tiktok')?.connected||!!busy||!videoUrl.trim()} onClick={()=>publish('tiktok')}>{busy==='publish-tiktok'?'Sending…':'Consent & publish to TikTok'}</button></div></div><div><small>LINKEDIN</small><h2>Member post</h2><p>Review the text before publishing. Clicking Publish is the explicit confirmation to send this content.</p><textarea className="linkedin" value={linkedinText} onChange={e=>setLinkedinText(e.target.value)} placeholder="Write or paste the final LinkedIn post…"/><button disabled={!by('linkedin')?.connected||!!busy||!linkedinText.trim()} onClick={()=>publish('linkedin')}>{busy==='publish-linkedin'?'Publishing…':'Confirm & publish to LinkedIn'}</button></div></section>
  <section className="truth"><b>Platform approval still matters.</b><p>YouTube, TikTok and LinkedIn control OAuth scopes, quotas, app review and account eligibility. Magnanimous reports those states rather than pretending an unapproved post succeeded.</p></section>
  <style jsx>{`.page{min-height:100vh;background:#06100d;color:#ecfff7;padding:24px 32px 64px;font-family:Inter,system-ui,sans-serif;background-image:radial-gradient(circle at 15% 15%,rgba(65,255,178,.1),transparent 25%),radial-gradient(circle at 80% 45%,rgba(74,140,255,.1),transparent 28%)}header,.hero,.cards,.owner,.publish,.truth,.notice,.error{max-width:1250px;margin-left:auto;margin-right:auto}header{display:flex;justify-content:space-between;font-size:10px;letter-spacing:.14em;color:#7aa18e}header a{color:#baf5dc;text-decoration:none}.hero{padding:55px 0 32px}.hero small,.owner small,.publish small{color:#55dda4;letter-spacing:.18em;font-weight:900}.hero h1{font-size:clamp(42px,7vw,78px);margin:9px 0;line-height:.95}.hero p,.owner p,.publish p,.truth p,article p{color:#8ba89a;line-height:1.6}.notice,.error{padding:13px 15px;border-radius:10px;margin-bottom:16px}.notice{border:1px solid #315d48;background:#0b2519;color:#a7f7c8}.error{border:1px solid #6b3441;background:#2a0d16;color:#ffc2cc}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:13px}.cards article,.owner,.publish>div,.truth{border:1px solid #1f4937;background:rgba(6,25,18,.83);border-radius:18px;padding:21px}.top{display:flex;justify-content:space-between;gap:12px}.top small{font-size:9px;color:#58dda4}.top h2{margin:5px 0 12px}.top b{font-size:8px;padding:6px 8px;border-radius:20px;height:max-content}.connected{color:#89ffc1;border:1px solid #347c58}.off{color:#d8aa69;border:1px solid #675032}button{border:0;border-radius:10px;background:#58e9aa;color:#052017;padding:12px 15px;font-weight:900;cursor:pointer}button:disabled{opacity:.45;cursor:not-allowed}.secondary{background:transparent;color:#b4cfbf;border:1px solid #345346}.owner{margin-top:18px}.fields{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:15px 0}.publish{margin-top:18px;display:grid;grid-template-columns:1.35fr 1fr;gap:14px}.publish input,.publish textarea,.publish select,.owner input{box-sizing:border-box;width:100%;border:1px solid #285340;background:#06120d;color:#fff;border-radius:10px;padding:12px;margin:5px 0}.publish textarea{min-height:100px}.publish .linkedin{min-height:250px}.row{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:7px}.truth{margin-top:18px}.truth b{color:#ffc875}.truth p{margin-bottom:0}@media(max-width:850px){.page{padding:18px 14px 55px}.cards,.publish{grid-template-columns:1fr}.fields,.row{grid-template-columns:1fr}header span{display:none}}`}</style>
 </main>
}