'use client';
import {useEffect,useMemo,useState} from 'react';
import {getPlatformAuthToken} from '../lib/magnanimous-session';

const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
type Checkpoint={id:number;session_key:string;scope:string;kind:string;stage:string;content:string;status:string;created_at:number;updated_at:number;metadata?:Record<string,any>};
type Work={id:number;title:string;goal:string;status:string;stage:string;progress:number;updated_at:number};
async function read(r:Response){const t=await r.text();try{return JSON.parse(t)}catch{return{detail:t||`Request failed (${r.status})`}}}
function when(ts:number){if(!ts)return'';return new Date(ts*1000).toLocaleString()}

export default function ActivityCenter(){
 const[token,setToken]=useState(''),[checkpoints,setCheckpoints]=useState<Checkpoint[]>([]),[work,setWork]=useState<Work[]>([]),[filter,setFilter]=useState('recoverable'),[error,setError]=useState('');
 useEffect(()=>{const t=getPlatformAuthToken();if(!t){location.replace('/login?returnTo=%2Factivity');return}setToken(t);Promise.all([fetch(`${api}/api/progress/checkpoint?limit=250`,{headers:{Authorization:`Bearer ${t}`},cache:'no-store'}).then(read),fetch(`${api}/api/work-engine?limit=120`,{headers:{Authorization:`Bearer ${t}`},cache:'no-store'}).then(read)]).then(([p,w])=>{setCheckpoints(p.checkpoints||[]);setWork(w.items||[])}).catch(()=>setError('Activity history could not be loaded.'))},[]);
 const recoverable=useMemo(()=>checkpoints.filter(x=>x.status==='failed'||x.stage==='working'||x.stage==='page-exit'||x.stage==='started'),[checkpoints]);
 const visible=filter==='all'?checkpoints:filter==='failed'?checkpoints.filter(x=>x.status==='failed'||x.stage==='failed'):recoverable;
 function resumeLink(c:Checkpoint){const id=String(c.metadata?.work_id||'');if(id)return`/work-engine?work=${encodeURIComponent(id)}`;const path=String(c.metadata?.path||'');return path&&path.startsWith('/')?path:'/work-engine'}
 return <main className="page">
  <header><a href="/">← Dashboard</a><span>ACTIVITY • RESTORE • CONTINUE</span><a href="/work-engine">Work Engine →</a></header>
  <section className="hero"><small>BUILT ON YOUR EXISTING AUTOSAVE SYSTEM</small><h1>See what happened. Resume what was interrupted.</h1><p>Your drafts and action checkpoints already save during work. This center makes that history visible without changing the underlying autosave system.</p><div className="stats"><div><b>{work.length}</b><span>saved work items</span></div><div><b>{checkpoints.length}</b><span>recent checkpoints</span></div><div><b>{recoverable.length}</b><span>recovery candidates</span></div><div><b>{work.filter(x=>x.status==='completed').length}</b><span>completed workflows</span></div></div></section>
  {error&&<div className="error">{error}</div>}
  <section className="grid"><article className="panel"><div className="head"><div><small>PERSISTENT WORK</small><h2>Jobs & workflows</h2></div><a href="/work-engine">Open all →</a></div>{!work.length?<p className="empty">No persistent work items yet.</p>:work.map(x=><div className="work" key={x.id}><div><b>{x.title}</b><p>{x.goal}</p><small>{x.status.toUpperCase()} • {x.stage} • {x.progress}% • {when(x.updated_at)}</small></div><a href={`/work-engine?work=${x.id}`}>{x.status==='completed'?'Review':'Resume'} →</a></div>)}</article>
   <article className="panel"><div className="head"><div><small>CHECKPOINT HISTORY</small><h2>Recoverable activity</h2></div><div className="tabs"><button className={filter==='recoverable'?'on':''} onClick={()=>setFilter('recoverable')}>Recoverable</button><button className={filter==='failed'?'on':''} onClick={()=>setFilter('failed')}>Failed</button><button className={filter==='all'?'on':''} onClick={()=>setFilter('all')}>All</button></div></div>{!visible.length?<p className="empty">No matching checkpoints.</p>:visible.slice(0,120).map(c=><div className="checkpoint" key={c.id}><span className={`dot ${c.status}`}/><div><b>{c.kind} • {c.stage}</b><p>{c.content||'Checkpoint saved without content.'}</p><small>{c.scope} • {when(c.updated_at)}{c.metadata?.path?` • ${c.metadata.path}`:''}</small></div><a href={resumeLink(c)}>Continue →</a></div>)}</article></section>
  <section className="rules"><div><b>RESTORE</b><p>Resume the original work surface or persistent job rather than creating a duplicate.</p></div><div><b>RETRY</b><p>Failed steps remain visible so you can retry intentionally instead of losing the reason they stopped.</p></div><div><b>PROOF</b><p>Completed work keeps checkpoints so future Magnanimous workflows can show what actually happened.</p></div></section>
  <style jsx>{`
  *{box-sizing:border-box}.page{min-height:100vh;background:#05090d;color:#eaf7ff;padding:24px 28px 70px;font-family:Inter,system-ui,sans-serif;background-image:radial-gradient(circle at 80% 0,rgba(54,214,255,.08),transparent 28%)}header,.hero,.grid,.rules,.error{max-width:1450px;margin-left:auto;margin-right:auto}header{display:flex;justify-content:space-between;font-size:9px;letter-spacing:.14em;color:#668594}header a{color:#73dff5;text-decoration:none}.hero{margin-top:26px;border:1px solid #1c4350;border-radius:22px;padding:32px;background:#071017}.hero small,.head small{font-size:9px;letter-spacing:.17em;color:#53d6ed}.hero h1{font-size:clamp(42px,6vw,70px);line-height:.98;margin:8px 0}.hero p{max-width:900px;color:#819aa5;line-height:1.65}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:18px}.stats div{border:1px solid #173744;border-radius:11px;padding:13px;background:#050c11}.stats b{display:block;font-size:28px;color:#8cecfb}.stats span{font-size:9px;color:#6e8b96}.error{margin-top:10px;border:1px solid #63313a;background:#211014;color:#ffb8c0;padding:10px;border-radius:10px}.grid{display:grid;grid-template-columns:1fr 1.25fr;gap:12px;margin-top:12px}.panel{border:1px solid #173844;border-radius:16px;background:#071017;padding:18px;min-width:0}.head{display:flex;justify-content:space-between;gap:12px;align-items:center}.head h2{margin:4px 0;font-size:24px}.head>a{color:#75dff2;text-decoration:none;font-size:9px}.tabs{display:flex;gap:5px}.tabs button{border:1px solid #274b59;background:#08131a;color:#7897a2;border-radius:20px;padding:7px 9px;font-size:8px;cursor:pointer}.tabs button.on{background:#0d2b36;color:#c8f6ff;border-color:#3c7c8f}.work,.checkpoint{display:grid;grid-template-columns:1fr auto;gap:12px;padding:12px 0;border-top:1px solid #153039;align-items:center}.work:first-of-type,.checkpoint:first-of-type{margin-top:8px}.work b,.checkpoint b{font-size:11px}.work p,.checkpoint p{color:#8098a3;font-size:10px;line-height:1.5;margin:5px 0;white-space:pre-wrap}.work small,.checkpoint small{color:#5f7d88;font-size:8px}.work a,.checkpoint a{color:#79dff0;text-decoration:none;font-size:9px;white-space:nowrap}.checkpoint{grid-template-columns:10px 1fr auto}.dot{width:7px;height:7px;border-radius:50%;background:#5992a3}.dot.failed{background:#e46f7a}.empty{color:#718995;padding:30px 5px}.rules{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:12px}.rules div{border:1px solid #243b44;border-radius:12px;padding:14px;background:#080e12}.rules b{color:#e7bd69;font-size:9px;letter-spacing:.12em}.rules p{font-size:10px;color:#7f969f;line-height:1.5}@media(max-width:980px){.grid{grid-template-columns:1fr}.stats{grid-template-columns:1fr 1fr}}@media(max-width:620px){.page{padding:18px 12px}.stats,.rules{grid-template-columns:1fr}.head{display:block}.tabs{margin:8px 0}}
  `}</style>
 </main>
}
