'use client';
import {useEffect,useState} from 'react';
const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
type Contact={id:number;first_name:string;last_name:string;email:string;phone:string;company:string;status:string;source:string;tags:string[];notes:string};
type Stats={contacts:number;leads:number;customers:number;pipeline_value:number;overdue_tasks:number};
const statuses=['lead','qualified','customer','inactive'];
export default function CRM(){
 const[token,setToken]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[signup,setSignup]=useState(false),[error,setError]=useState(''),[workspace,setWorkspace]=useState<any>(null),[contacts,setContacts]=useState<Contact[]>([]),[stats,setStats]=useState<Stats>({contacts:0,leads:0,customers:0,pipeline_value:0,overdue_tasks:0}),[q,setQ]=useState(''),[status,setStatus]=useState(''),[showForm,setShowForm]=useState(false),[form,setForm]=useState({first_name:'',last_name:'',email:'',phone:'',company:'',status:'lead',source:'',tags:'',notes:''});
 useEffect(()=>{const t=localStorage.getItem('iam_crm_token')||'';if(t){setToken(t);load(t)}},[]);useEffect(()=>{if(token)load(token)},[q,status]);
 async function load(t=token){const h={Authorization:`Bearer ${t}`};try{const[m,c,s]=await Promise.all([fetch(`${api}/api/crm/me`,{headers:h}),fetch(`${api}/api/crm/contacts?q=${encodeURIComponent(q)}&status=${encodeURIComponent(status)}`,{headers:h}),fetch(`${api}/api/crm/summary`,{headers:h})]);if(!m.ok){logout();return}const md=await m.json(),cd=await c.json(),sd=await s.json();setWorkspace(md.workspace);setContacts(cd.contacts||[]);setStats(sd)}catch{setError('Unable to connect to CRM.')}}
 async function auth(){setError('');const endpoint=signup?'/api/crm/signup':'/api/crm/login';const r=await fetch(`${api}${endpoint}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,email,password})});const d=await r.json();if(!r.ok){setError(d.detail||'Unable to sign in');return}localStorage.setItem('iam_crm_token',d.token);setToken(d.token);setWorkspace(d.workspace)}
 function logout(){localStorage.removeItem('iam_crm_token');setToken('');setWorkspace(null);setContacts([])}
 async function save(){const b={...form,tags:form.tags.split(',').map(x=>x.trim()).filter(Boolean)};const r=await fetch(`${api}/api/crm/contacts`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(b)});if(r.ok){setShowForm(false);setForm({first_name:'',last_name:'',email:'',phone:'',company:'',status:'lead',source:'',tags:'',notes:''});load()}}
 if(!token)return <main className="crm-login"><div className="crm-box"><div className="mark">✦</div><h1>{signup?'Create your CRM':'Welcome to I AM CRM'}</h1><p>{signup?'Create your own private CRM workspace. Your contacts and business data belong to your workspace.':'Sign in to your private CRM workspace.'}</p>{signup&&<input placeholder="Your name or business name" value={name} onChange={e=>setName(e.target.value)}/>}<input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Password (8+ characters)" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={auth}>{signup?'Create My CRM':'Sign In'}</button>{error&&<div className="error">{error}</div>}<button className="linkbtn" onClick={()=>setSignup(!signup)}>{signup?'Already have an account? Sign in':'Need your own CRM? Create one free'}</button><a href="/">← Back to I AM Platform</a></div></main>;
 return <main className="crm-app"><header className="crm-header"><div><span className="eyebrow">I AM MAGNANIMOUS WAY™</span><h1>{workspace?.name||'My CRM'}</h1><p>Private workspace • {workspace?.plan||'free'} plan</p></div><div><button onClick={()=>setShowForm(true)}>+ Add Contact</button><button className="secondary" onClick={logout}>Log out</button></div></header><section className="crm-stats"><div><b>{stats.contacts}</b><span>Contacts</span></div><div><b>{stats.leads}</b><span>Leads</span></div><div><b>{stats.customers}</b><span>Customers</span></div><div><b>${Number(stats.pipeline_value||0).toLocaleString()}</b><span>Open Pipeline</span></div><div><b>{stats.overdue_tasks}</b><span>Due Tasks</span></div></section><section className="crm-toolbar"><input placeholder="Search contacts…" value={q} onChange={e=>setQ(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></section><section className="crm-grid">{contacts.map(c=><article key={c.id}><div className="person"><div className="avatar">{c.first_name?.[0]||'?'}{c.last_name?.[0]||''}</div><div><h2>{c.first_name} {c.last_name}</h2><small>{c.company||'No company'}</small></div><span>{c.status}</span></div><p>{c.email||'No email'}</p><p>{c.phone||'No phone'}</p><div className="tags">{c.tags.map(t=><em key={t}>{t}</em>)}</div></article>)}{contacts.length===0&&<div className="empty">No contacts yet. Add your first contact.</div>}</section>{showForm&&<div className="modal"><div className="crm-box"><button className="close" onClick={()=>setShowForm(false)}>×</button><h2>Add Contact</h2>{(['first_name','last_name','email','phone','company','source'] as const).map(k=><input key={k} placeholder={k.replace('_',' ')} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>) }<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{statuses.map(s=><option key={s}>{s}</option>)}</select><input placeholder="Tags, comma separated" value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})}/><textarea placeholder="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button onClick={save}>Save Contact</button></div></div>}</main>}
