'use client';
import {useEffect,useState} from 'react';
import {getPlatformAuthToken} from '../../lib/magnanimous-session';

const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
type Tool='invoice'|'pos'|'website'|'app';
type Client={id:string;name:string};
type Item={description:string;quantity:number;unit_price:number};
type Product={id:string;name:string;sku:string;price_cents:number;stock:number};
type Document={id:string;title:string;status:string;body:any};
const titles:Record<Tool,string>={invoice:'Invoice Maker',pos:'Point of Sale',website:'Website Builder',app:'App Prototype Builder'};
const tokenHeader=(token:string)=>({Authorization:`Bearer ${token}`});
async function read(response:Response){const raw=await response.text();try{return JSON.parse(raw)}catch{return{detail:raw||`Request failed (${response.status})`}}}
function download(name:string,body:string,type:string){const url=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function escaped(value:any){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]||char))}
function exportWebsite(document:Document){const b=document.body,html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escaped(document.title)}</title><style>body{font-family:system-ui,sans-serif;margin:0;color:#172534}header,main{padding:4rem max(1rem,calc((100vw - 800px)/2))}header{background:${escaped(b.theme_color)};color:white}h1{font-size:clamp(2rem,5vw,4rem)}a{color:inherit}</style></head><body><header><h1>${escaped(b.headline)}</h1><p>${escaped(b.description)}</p></header><main>${(b.sections||[]).map((s:any)=>`<section><h2>${escaped(s.heading)}</h2><p>${escaped(s.copy)}</p></section>`).join('')}</main></body></html>`;download(`${document.title.toLowerCase().replace(/[^a-z0-9]+/g,'-')||'site'}.html`,html,'text/html')}

export default function NativeWhiteLabel(){
 const[tool,setTool]=useState<Tool>('invoice'),[token,setToken]=useState(''),[clients,setClients]=useState<Client[]>([]),[clientId,setClientId]=useState(''),[documents,setDocuments]=useState<Document[]>([]),[products,setProducts]=useState<Product[]>([]),[cart,setCart]=useState<Record<string,number>>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const[number,setNumber]=useState(''),[customer,setCustomer]=useState(''),[currency,setCurrency]=useState('USD'),[dueDate,setDueDate]=useState(''),[tax,setTax]=useState(0),[items,setItems]=useState<Item[]>([{description:'',quantity:1,unit_price:0}]);
 const[name,setName]=useState(''),[description,setDescription]=useState(''),[headline,setHeadline]=useState(''),[themeColor,setThemeColor]=useState('#164c78');
 const[sku,setSku]=useState(''),[price,setPrice]=useState(0),[stock,setStock]=useState(0),[externalConfirmed,setExternalConfirmed]=useState(false),[printInvoice,setPrintInvoice]=useState<Document|null>(null);
 function printDraft(document:Document){setPrintInvoice(document);setTimeout(()=>window.print(),150)}
 useEffect(()=>{
  const q=new URLSearchParams(location.search).get('tool');if(q&&['invoice','pos','website','app'].includes(q))setTool(q as Tool);
  const t=getPlatformAuthToken();if(!t){location.replace('/login?returnTo=%2Fwhite-label%2Fnative');return}setToken(t);
  fetch(`${api}/api/agency/clients`,{headers:tokenHeader(t),cache:'no-store'}).then(async r=>{const d=await read(r);if(!r.ok)throw new Error(d.detail||'Could not load client accounts.');setClients(d.clients||[]);if(d.clients?.[0]?.id)setClientId(d.clients[0].id)}).catch(e=>setMessage(e.message));
 },[]);
 useEffect(()=>{if(!token||!clientId)return;refresh()},[token,clientId,tool]);
 async function refresh(){
  const path=tool==='pos'?'/api/white-label/native/pos/products':`/api/white-label/native/${tool}`;
  try{const r=await fetch(`${api}${path}?client_id=${encodeURIComponent(clientId)}`,{headers:tokenHeader(token),cache:'no-store'}),d=await read(r);if(!r.ok)throw new Error(d.detail||'Could not load this app.');if(tool==='pos')setProducts(d.products||[]);else setDocuments(d.documents||[])}catch(e:any){setMessage(e.message)}
 }
 async function save(path:string,body:any){setBusy(true);setMessage('');try{const r=await fetch(`${api}${path}`,{method:'POST',headers:{...tokenHeader(token),'Content-Type':'application/json'},body:JSON.stringify({...body,client_id:clientId})}),d=await read(r);if(!r.ok)throw new Error(d.detail||'Could not save.');setMessage('Saved in this client workspace.');await refresh();return d}catch(e:any){setMessage(e.message);return null}finally{setBusy(false)}}
 async function saveInvoice(){if(await save('/api/white-label/native/invoice',{number,customer,currency,due_date:dueDate,tax_percent:tax,items})){setNumber('');setCustomer('');setItems([{description:'',quantity:1,unit_price:0}])}}
 async function saveProject(){if(await save(`/api/white-label/native/${tool}`,{name,description,headline,theme_color:themeColor})){setName('');setHeadline('');setDescription('')}}
 async function saveProduct(){if(await save('/api/white-label/native/pos/products',{name,sku,price,stock})){setName('');setSku('');setPrice(0);setStock(0)}}
 async function recordSale(method:'cash'|'external'){
  const sale=await save('/api/white-label/native/pos/sales',{payment_method:method,external_payment_confirmed:method==='external'&&externalConfirmed,items:Object.entries(cart).filter(([,q])=>q>0).map(([product_id,quantity])=>({product_id,quantity}))});
  if(sale){setCart({});setExternalConfirmed(false);setMessage(`Sale recorded: ${(sale.total_cents/100).toFixed(2)}. No card payment was processed here.`)}
 }
 const total=items.reduce((sum,item)=>sum+(Number(item.quantity)||0)*(Number(item.unit_price)||0),0),cartTotal=products.reduce((sum,p)=>sum+(cart[p.id]||0)*p.price_cents,0)/100;
 return <main className="native"><header><a href="/white-label">← White Label</a><div><small>MAGNANIMOUS AI • NATIVE BUSINESS TOOLS</small><h1>{titles[tool]}</h1><p>Each client stays separate. Magnanimous owns the workspace; no outside builder is required for these drafts.</p></div></header>
  <nav>{(['invoice','pos','website','app'] as Tool[]).map(key=><button key={key} className={tool===key?'selected':''} onClick={()=>{setTool(key);history.replaceState({},'',`/white-label/native?tool=${key}`);setMessage('')}}>{titles[key]}</button>)}</nav>
  <label>Client workspace <select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">Choose a client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
  {!clients.length&&<p>Create a client in <a href="/agency-command">Agency Command</a> before using these tools.</p>}{message&&<p role="status" className="message">{message}</p>}
  {tool==='invoice'&&<section className="columns"><div className="panel"><h2>New invoice draft</h2><p>Save a draft, then review and print it. Nothing is emailed or charged automatically.</p><label>Invoice number<input value={number} onChange={e=>setNumber(e.target.value)} placeholder="INV-001"/></label><label>Customer<input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Customer name"/></label><div className="row"><label>Currency<input value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())} maxLength={3}/></label><label>Due date<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label><label>Tax %<input type="number" min="0" max="100" value={tax} onChange={e=>setTax(Number(e.target.value))}/></label></div><h3>Items</h3>{items.map((item,i)=><div className="row" key={i}><input aria-label={`Item ${i+1} description`} placeholder="What you provided" value={item.description} onChange={e=>setItems(items.map((x,n)=>n===i?{...x,description:e.target.value}:x))}/><input aria-label={`Item ${i+1} quantity`} type="number" min="1" value={item.quantity} onChange={e=>setItems(items.map((x,n)=>n===i?{...x,quantity:Number(e.target.value)}:x))}/><input aria-label={`Item ${i+1} price`} type="number" min="0" step="0.01" value={item.unit_price} onChange={e=>setItems(items.map((x,n)=>n===i?{...x,unit_price:Number(e.target.value)}:x))}/></div>)}<button className="secondary" onClick={()=>setItems([...items,{description:'',quantity:1,unit_price:0}])}>+ Add line</button><p>Estimated subtotal: {currency} {total.toFixed(2)}</p><button disabled={!clientId||busy} onClick={saveInvoice}>Save invoice draft</button></div><div className="panel"><h2>Saved drafts</h2>{documents.map(d=><article key={d.id}><strong>{d.title}</strong><p>{d.body.customer} · {d.body.currency} {(d.body.total_cents/100).toFixed(2)}</p><small>Draft only · Review before sending</small><button className="secondary" onClick={()=>printDraft(d)}>Print this invoice</button></article>)}{!documents.length&&<p>No invoices yet.</p>}</div></section>}
  {tool==='pos'&&<section className="columns"><div className="panel"><h2>Add inventory</h2><label>Product name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>SKU<input value={sku} onChange={e=>setSku(e.target.value)}/></label><div className="row"><label>Price<input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(Number(e.target.value))}/></label><label>Stock<input type="number" min="0" value={stock} onChange={e=>setStock(Number(e.target.value))}/></label></div><button disabled={!clientId||busy} onClick={saveProduct}>Save product</button></div><div className="panel"><h2>New sale</h2><p>Cash or a payment completed elsewhere. Card processing is not included.</p>{products.map(p=><div key={p.id} className="row product"><span>{p.name}<small>{p.sku} · stock {p.stock} · {(p.price_cents/100).toFixed(2)}</small></span><input aria-label={`${p.name} quantity`} type="number" min="0" max={p.stock} value={cart[p.id]||0} onChange={e=>setCart({...cart,[p.id]:Math.min(p.stock,Math.max(0,Number(e.target.value)||0))})}/></div>)}<p>Total: {cartTotal.toFixed(2)}</p><button disabled={!clientId||busy||cartTotal<=0} onClick={()=>recordSale('cash')}>Record cash sale</button><label className="check"><input type="checkbox" checked={externalConfirmed} onChange={e=>setExternalConfirmed(e.target.checked)}/> I confirmed payment outside this POS</label><button className="secondary" disabled={!clientId||busy||cartTotal<=0||!externalConfirmed} onClick={()=>recordSale('external')}>Record external payment sale</button></div></section>}
  {(tool==='website'||tool==='app')&&<section className="columns"><div className="panel"><h2>Build a {tool==='website'?'website':'business app'} draft</h2><p>{tool==='website'?'Create branded content and a visual preview. Publishing and domains remain separate, reviewed steps.':'Create an app prototype brief. This does not automatically ship a native iOS or Android binary.'}</p><label>Project name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>What it does<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Headline<input value={headline} onChange={e=>setHeadline(e.target.value)}/></label><label>Theme color<input type="color" value={themeColor} onChange={e=>setThemeColor(e.target.value)}/></label><button disabled={!clientId||busy} onClick={saveProject}>Save draft</button></div><div className="panel"><h2>Client projects</h2>{documents.map(d=><article key={d.id}><strong>{d.title}</strong><p>{d.body.description||'No description yet'}</p>{tool==='website'&&<div className="preview" style={{borderColor:d.body.theme_color}}><h3>{d.body.headline}</h3><p>{d.body.description}</p><span>{d.body.call_to_action}</span></div>}<small>Draft · Not deployed or app-store published</small><button className="secondary" onClick={()=>tool==='website'?exportWebsite(d):download(`${d.title.toLowerCase().replace(/[^a-z0-9]+/g,'-')||'app'}.json`,JSON.stringify(d.body,null,2),'application/json')}>Export {tool==='website'?'HTML':'prototype JSON'}</button></article>)}{!documents.length&&<p>No projects yet.</p>}</div></section>}
  {printInvoice&&<section className="printInvoice"><h1>INVOICE · {printInvoice.title}</h1><p>Customer: {printInvoice.body.customer}</p><p>Due: {printInvoice.body.due_date||'Not set'}</p><table><thead><tr><th>Item</th><th>Quantity</th><th>Unit price</th><th>Total</th></tr></thead><tbody>{printInvoice.body.items.map((x:any,i:number)=><tr key={i}><td>{x.description}</td><td>{x.quantity}</td><td>{(x.unit_price_cents/100).toFixed(2)}</td><td>{(x.total_cents/100).toFixed(2)}</td></tr>)}</tbody></table><p>Subtotal: {printInvoice.body.currency} {(printInvoice.body.subtotal_cents/100).toFixed(2)} · Tax: {(printInvoice.body.tax_cents/100).toFixed(2)}</p><h2>Total: {printInvoice.body.currency} {(printInvoice.body.total_cents/100).toFixed(2)}</h2><p>Draft · Review before sending · No payment processed</p></section>}
  <footer>Native tools save into the selected client workspace. Telecom, WhatsApp, online card payments, and app-store distribution still need their respective regulated connections or accounts.</footer><style jsx>{`
   .native{min-height:100vh;background:#061018;color:#e9f6ff;padding:24px;font-family:Inter,system-ui,sans-serif}header{max-width:1200px;margin:auto;display:flex;gap:22px;align-items:start}a{color:#79dcff}header small{color:#71bfd5;letter-spacing:.15em;font-size:10px}h1{font-size:clamp(30px,5vw,54px);margin:5px 0}p{color:#91a9b8;line-height:1.5}nav{display:flex;flex-wrap:wrap;gap:8px;max-width:1200px;margin:25px auto}button{background:#80dbff;color:#061018;border:0;border-radius:9px;padding:10px 13px;cursor:pointer;font-weight:800}button:disabled{opacity:.45;cursor:not-allowed}nav button,.secondary{background:#102838;color:#b2ebff;border:1px solid #37607a}nav .selected{background:#83ddff;color:#061018}.native>label,.columns{max-width:1200px;margin:auto}.native>label{display:block}.columns{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:20px}.panel{border:1px solid #234458;background:#0b1b27;border-radius:16px;padding:20px}.panel h2{margin-top:0}.panel label{display:grid;gap:4px;margin:10px 0;color:#a9c9d9;font-size:12px}input,select,textarea{box-sizing:border-box;background:#06121c;color:#e7f7ff;border:1px solid #2b5369;border-radius:8px;padding:10px;min-width:0}label input,label select,label textarea{width:100%}textarea{min-height:100px}.row{display:flex;gap:7px;align-items:end;margin:8px 0}.row>*{flex:1}.row>input:nth-of-type(n+2){max-width:90px}.product{border-bottom:1px solid #234458;padding:5px 0}.product small{display:block;color:#819dad}.product input{max-width:75px}.check{display:flex!important;align-items:center;gap:8px}.check input{width:auto}article{border-bottom:1px solid #234458;padding:12px 0}article small{display:block;color:#75adbd}.preview{border:2px solid;border-radius:12px;padding:14px;margin:10px 0}.preview h3{margin:0}.preview span{display:inline-block;background:#73c8e6;color:#061018;padding:8px;border-radius:8px}.message{max-width:1200px;margin:10px auto;color:#bce9f5}.printInvoice{display:none}footer{max-width:1200px;margin:32px auto;color:#7d9bae;font-size:11px}@media(max-width:800px){.columns{grid-template-columns:1fr}.native{padding:14px}header{display:block}}@media print{header,nav,.columns,footer,.message,.native>label{display:none!important}.native{background:#fff;color:#000}.printInvoice{display:block;color:#000}.printInvoice p{color:#000}.printInvoice table{width:100%;border-collapse:collapse}.printInvoice th,.printInvoice td{border-bottom:1px solid #ccc;padding:8px;text-align:left}}
  `}</style></main>
}
