'use client';
import {useEffect,useState} from 'react';
const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
async function read(r:Response){const t=await r.text();try{return JSON.parse(t)}catch{return{detail:t}}}
export default function MovieWatch(){
 const[meta,setMeta]=useState<any>(null),[ads,setAds]=useState<any[]>([]),[error,setError]=useState('');
 useEffect(()=>{const token=new URLSearchParams(location.search).get('asset')||'';if(!token){setError('Movie link is missing.');return}(async()=>{const r=await fetch(api+`/api/movie-maker/share/${encodeURIComponent(token)}/meta`,{cache:'no-store'}),d=await read(r);if(!r.ok){setError(d.detail||'Movie not found.');return}setMeta(d);if(d.ad_supported){const ar=await fetch(api+'/api/ads?placement=movie-watch',{cache:'no-store'}),ad=await read(ar);if(ar.ok)setAds(ad.ads||[])}})()},[]);
 async function share(){if(!meta)return;const url=location.href;if(navigator.share){await navigator.share({title:meta.title,url});return}await navigator.clipboard.writeText(url)}
 if(error)return <main className="page"><div className="card"><h1>Magnanimous Movie</h1><p>{error}</p><a href="/movie-maker">Open Movie Maker</a></div><style jsx>{css}</style></main>;
 if(!meta)return <main className="page"><div className="card"><h1>Loading Magnanimous Movie…</h1></div><style jsx>{css}</style></main>;
 return <main className="page"><header><a href="/">I AM MAGNANIMOUS WAY™</a><span>Magnanimous Movie Maker</span></header><section className="hero"><small>{meta.watermarked?'MAGNANIMOUS WATERMARKED CREATION':'CLEAN CREATION'}</small><h1>{meta.title||'Magnanimous Movie'}</h1>{String(meta.content_type).startsWith('video')?<video src={meta.asset_url} controls playsInline autoPlay={false}/>:<img src={meta.asset_url} alt={meta.title||'Magnanimous creation'}/>}<div className="buttons"><a href={meta.asset_url} download target="_blank" rel="noopener noreferrer">Download</a><button onClick={share}>Share</button><a href="/movie-maker">Create yours</a></div></section>{meta.ad_supported&&ads.length>0&&<section className="sponsors"><small>SPONSORED</small><div>{ads.slice(0,3).map(a=><a key={a.id} href={a.url} target="_blank" rel="sponsored noopener noreferrer"><b>{a.title}</b><span>{a.label||'Sponsored'}</span></a>)}</div><p>Ads are clearly labeled. Viewing or clicking is optional and is never rewarded or required.</p></section>}<footer>Created with Magnanimous AI • I AM MAGNANIMOUS WAY™</footer><style jsx>{css}</style></main>
}
const css=`.page{min-height:100vh;background:#050911;color:#eef8ff;padding:24px;font-family:Inter,system-ui,sans-serif;background-image:radial-gradient(circle at 20% 0,#17325a 0,transparent 28%),radial-gradient(circle at 90% 60%,#3c1744 0,transparent 30%)}header,.hero,.sponsors,footer,.card{max-width:1180px;margin:auto}header{display:flex;justify-content:space-between;color:#83dfff;font-size:11px;letter-spacing:.13em}header a{color:#83dfff;text-decoration:none}.hero{margin-top:35px;border:1px solid #263f55;background:#08111d;border-radius:22px;padding:22px}.hero small,.sponsors small{color:#74e8ff;letter-spacing:.16em}.hero h1{font-size:clamp(34px,6vw,72px);margin:9px 0 18px}.hero video,.hero img{width:100%;max-height:76vh;object-fit:contain;background:#000;border-radius:14px}.buttons{display:flex;gap:8px;flex-wrap:wrap;margin-top:13px}.buttons a,.buttons button{border:1px solid #31506b;background:#0e1c2b;color:#f0fbff;padding:11px 15px;border-radius:10px;text-decoration:none;font-weight:800;cursor:pointer}.sponsors{margin-top:14px;border:1px solid #2b4152;border-radius:18px;padding:18px;background:#09131c}.sponsors>div{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:10px}.sponsors a{border:1px solid #314b5f;border-radius:12px;padding:13px;color:#fff;text-decoration:none}.sponsors span{display:block;color:#8399aa;font-size:10px;margin-top:7px}.sponsors p{color:#758b9b;font-size:11px}footer{padding:28px 5px;color:#6d8495;font-size:11px}.card{margin-top:80px;border:1px solid #263f55;border-radius:18px;padding:25px}.card a{color:#7ee9ff}@media(max-width:760px){.page{padding:14px}.sponsors>div{grid-template-columns:1fr}header{gap:12px;flex-direction:column}}`;
