'use client';
import {useEffect,useState} from 'react';
const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
type RequestRow={id:number;request_type:string;message:string;status:string;created_at:number;updated_at:number};
async function read(r:Response){const t=await r.text();try{return JSON.parse(t)}catch{return{detail:t}}}
export default function BillingSupport(){
 const[token,setToken]=useState(''),[rows,setRows]=useState<RequestRow[]>([]),[type,setType]=useState('cancel'),[message,setMessage]=useState(''),[msg,setMsg]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(t:string){try{const r=await fetch(`${api}/api/billing/management-request`,{headers:{Authorization:`Bearer ${t}`},cache:'no-store'}),d=await read(r);if(r.status===401){location.replace('/login?returnTo=%2Fbilling-support');return}if(r.ok)setRows(d.requests||[]);else setError(d.detail||'Unable to load billing requests.')}catch{setError('Billing support could not be reached. Check your connection and try again.')}}
 useEffect(()=>{const t=localStorage.getItem('iam_account_token')||'';if(!t){location.replace('/login?returnTo=%2Fbilling-support');return}setToken(t);load(t)},[]);
 async function submit(){if(type==='cancel'&&!confirm('Submit a cancellation request for your active paid subscription? Your access remains unchanged until Stripe records the subscription change.'))return;setBusy(true);setError('');setMsg('');try{const r=await fetch(`${api}/api/billing/management-request`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({request_type:type,message})}),d=await read(r);if(!r.ok)throw new Error(d.detail||'Request could not be submitted.');setMsg(d.detail||'Request submitted.');setMessage('');await load(token)}catch(e:any){setError(e?.message||'Billing support could not be reached. Check your connection and try again.')}finally{setBusy(false)}}
 function label(v:string){return v==='cancel'?'Cancel paid subscription':v==='payment_method'?'Update payment method':'Billing question'}
 return <main><header><a href="/pricing">← Pricing & Billing</a><span>I AM MAGNANIMOUS WAY™</span></header><section className="hero"><small>ACCOUNT BILLING</small><h1>Billing Support</h1><p>When Stripe Customer Portal is available, the Pricing page opens it directly. This secure fallback sends a billing-management request to the platform team without changing your subscription prematurely.</p></section>{msg&&<div className="msg ok" role="status">{msg}</div>}{error&&<div className="msg err" role="alert">{error}</div>}<section className="grid"><article><h2>Submit a request</h2><label>Request type<select value={type} onChange={e=>setType(e.target.value)}><option value="cancel">Cancel paid subscription</option><option value="payment_method">Update payment method</option><option value="billing_question">Billing question</option></select></label><label>Details<textarea maxLength={2000} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Add any details that will help the billing team respond."/></label><button disabled={busy} onClick={submit}>{busy?'Submitting…':'Submit billing request'}</button><p className="note">This form creates a support request; it does not instantly cancel, change, or refund a Stripe subscription. Access changes only after the corresponding Stripe subscription update is processed.</p></article><article><h2>Request history</h2>{rows.length===0?<p className="empty">No billing requests yet.</p>:rows.map(r=><div className="request" key={r.id}><div><b>{label(r.request_type)}</b><span className={`status ${r.status}`}>{r.status.replace('_',' ')}</span></div>{r.message&&<p>{r.message}</p>}<small>{new Date(r.created_at*1000).toLocaleString()}</small></div>)}</article></section><style jsx>{`
main{min-height:100vh;background:#05080d;color:#eaf4fb;padding:24px 28px 60px;font-family:Inter,system-ui,sans-serif}header,.hero,.grid,.msg{max-width:1050px;margin-left:auto;margin-right:auto}header{display:flex;justify-content:space-between;color:#758a99;font-size:10px;letter-spacing:.14em}header a{color:#78dff5;text-decoration:none}.hero{padding:64px 0 30px}.hero small{color:#5fe2ff;font-size:9px;letter-spacing:.18em}.hero h1{font-size:clamp(42px,7vw,72px);margin:8px 0}.hero p{max-width:750px;color:#96a9b8;line-height:1.65}.msg{padding:12px 14px;margin-bottom:14px;border-radius:10px}.ok{background:#0b1b12;border:1px solid #315c42;color:#a4efb9}.err{background:#251013;border:1px solid #65333b;color:#ffb4bd}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.grid article{border:1px solid #213542;background:#081018;border-radius:18px;padding:22px}.grid h2{margin-top:0}label{display:block;color:#8ca0af;font-size:11px;margin:12px 0}select,textarea{display:block;width:100%;box-sizing:border-box;margin-top:6px;background:#050a0f;border:1px solid #29414f;color:#edf8ff;border-radius:9px;padding:12px;font:inherit}textarea{min-height:125px;resize:vertical}button{border:1px solid #50d8f7;background:#50d8f7;color:#031016;border-radius:9px;padding:12px 15px;font-weight:900;cursor:pointer}button:disabled{opacity:.55}.note,.empty{font-size:10px;line-height:1.55;color:#728896;margin-top:14px}.request{border-top:1px solid #18303d;padding:13px 0}.request:first-of-type{border-top:0}.request>div{display:flex;justify-content:space-between;gap:10px}.request b{font-size:12px}.request p{color:#91a6b5;font-size:11px;line-height:1.45}.request small{color:#617784;font-size:9px}.status{font-size:8px;letter-spacing:.08em;text-transform:uppercase;border:1px solid #385267;border-radius:999px;padding:5px 7px;color:#9dc9df}.status.completed{border-color:#386349;color:#86e9a7}.status.rejected{border-color:#67343b;color:#ff9ea9}@media(max-width:760px){main{padding:18px 14px 40px}.grid{grid-template-columns:1fr}}
`}</style></main>}
