'use client';
import {useEffect,useState} from 'react';
const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
type Row={id:number;tenant_id:string;workspace_name?:string;user_id:string;email:string;request_type:string;message:string;status:string;created_at:number;updated_at:number};
async function read(r:Response){const t=await r.text();try{return JSON.parse(t)}catch{return{detail:t}}}
export default function OwnerBilling(){
 const[token,setToken]=useState(''),[rows,setRows]=useState<Row[]>([]),[filter,setFilter]=useState(''),[msg,setMsg]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(0);
 async function load(t:string,f=filter){setError('');const q=f?`?status=${encodeURIComponent(f)}`:'';const r=await fetch(`${api}/api/admin/billing-requests${q}`,{headers:{Authorization:`Bearer ${t}`},cache:'no-store'}),d=await read(r);if(r.status===401||r.status===403){location.replace('/owner-login');return}if(r.ok)setRows(d.requests||[]);else setError(d.detail||'Unable to load billing requests.')}
 useEffect(()=>{const t=localStorage.getItem('odin_admin_token')||'';if(!t){location.replace('/owner-login');return}setToken(t);load(t,'')},[]);
 async function setStatus(id:number,status:string){setBusy(id);setError('');const r=await fetch(`${api}/api/admin/billing-requests/${id}`,{method:'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({status})}),d=await read(r);if(r.ok){setMsg(`Billing request #${id} marked ${status.replace('_',' ')}.`);await load(token)}else setError(d.detail||'Unable to update request.');setBusy(0)}
 function typeLabel(v:string){return v==='cancel'?'CANCEL FULL BUSINESS':v==='payment_method'?'UPDATE PAYMENT METHOD':'BILLING QUESTION'}
 return <main><header><a href="/owner-center">← Owner Center</a><span>PRIVATE PLATFORM BILLING</span></header><section className="hero"><div><small>I AM MAGNANIMOUS WAY™</small><h1>Billing Queue</h1><p>Customer requests that cannot be completed through Stripe Customer Portal appear here. Mark them in progress while handling the corresponding Stripe account action, then complete the request after Stripe records the subscription change.</p></div><a href="/pricing">View live plans →</a></section>{msg&&<div className="msg ok">{msg}</div>}{error&&<div className="msg err">{error}</div>}<section className="toolbar"><label>Status<select value={filter} onChange={e=>{setFilter(e.target.value);load(token,e.target.value)}}><option value="">All requests</option><option value="pending">Pending</option><option value="in_progress">In progress</option><option value="completed">Completed</option><option value="rejected">Rejected</option></select></label><b>{rows.length} REQUESTS</b></section><section className="list">{rows.length===0?<div className="empty">No billing requests in this view.</div>:rows.map(r=><article key={r.id}><div className="top"><div><small>#{r.id} • {typeLabel(r.request_type)}</small><h2>{r.workspace_name||r.tenant_id}</h2><p>{r.email}</p></div><span className={`status ${r.status}`}>{r.status.replace('_',' ')}</span></div>{r.message&&<div className="message">{r.message}</div>}<footer><small>{new Date(r.created_at*1000).toLocaleString()}</small><div><button disabled={busy===r.id} onClick={()=>setStatus(r.id,'in_progress')}>In progress</button><button disabled={busy===r.id} onClick={()=>setStatus(r.id,'completed')}>Complete</button><button className="reject" disabled={busy===r.id} onClick={()=>setStatus(r.id,'rejected')}>Reject</button></div></footer></article>)}</section><style jsx>{`
main{min-height:100vh;background:#050607;color:#f5ead5;padding:24px 32px 60px;font-family:Inter,system-ui,sans-serif}header,.hero,.toolbar,.list,.msg{max-width:1200px;margin-left:auto;margin-right:auto}header{display:flex;justify-content:space-between;color:#9a825c;font-size:10px;letter-spacing:.15em}header a{color:#e5b968;text-decoration:none}.hero{margin-top:28px;border:1px solid #514025;border-radius:19px;padding:30px;background:linear-gradient(135deg,#12100d,#08090a);display:flex;justify-content:space-between;gap:24px;align-items:end}.hero small{font-size:9px;letter-spacing:.18em;color:#b69050}.hero h1{font:700 clamp(40px,6vw,68px) Georgia,serif;color:#ffd98e;margin:6px 0}.hero p{color:#a89a84;max-width:800px;line-height:1.55}.hero>a{border:1px solid #5b4525;border-radius:9px;padding:11px 13px;color:#efc675;text-decoration:none;white-space:nowrap}.msg{margin-top:12px;padding:11px 14px;border-radius:9px}.ok{background:#0c1a10;border:1px solid #345b3e;color:#a9efb9}.err{background:#231013;border:1px solid #633039;color:#ffb3bc}.toolbar{margin-top:14px;border:1px solid #32291d;background:#0b0b0b;border-radius:14px;padding:13px 16px;display:flex;justify-content:space-between;align-items:end}.toolbar label{color:#8d806d;font-size:10px}.toolbar select{display:block;margin-top:5px;background:#070707;border:1px solid #403426;color:#f4e6cc;border-radius:8px;padding:9px}.toolbar b{font-size:10px;color:#b89c68}.list{margin-top:12px;display:grid;gap:10px}.list article,.empty{border:1px solid #332a1e;background:#0b0b0b;border-radius:15px;padding:18px}.top{display:flex;justify-content:space-between;gap:20px}.top small{color:#b79251;font-size:9px;letter-spacing:.08em}.top h2{margin:5px 0;font-size:20px}.top p{margin:0;color:#817665;font-size:11px}.status{height:max-content;border:1px solid #65502e;border-radius:999px;padding:6px 9px;font-size:8px;text-transform:uppercase;letter-spacing:.08em;color:#d6b77f}.status.completed{border-color:#345f42;color:#8be9aa}.status.rejected{border-color:#61343a;color:#ff9da7}.message{margin-top:14px;padding:12px;border-radius:9px;background:#11100e;color:#b5a994;font-size:12px;line-height:1.5}footer{margin-top:15px;border-top:1px solid #282016;padding-top:12px;display:flex;justify-content:space-between;gap:15px;align-items:center}footer small{color:#6f6556}footer div{display:flex;gap:7px}button{border:1px solid #795a29;background:#6f4915;color:#fff0d1;border-radius:8px;padding:9px 11px;font-weight:800;cursor:pointer}.reject{background:#2d1517;border-color:#603237;color:#ffb5b9}button:disabled{opacity:.5}@media(max-width:720px){main{padding:18px 14px 40px}.hero{display:block}.hero>a{display:inline-block;margin-top:10px}.toolbar,.top,footer{align-items:flex-start;flex-direction:column}}
`}</style></main>}
