'use client';

import {useEffect,useState} from 'react';

const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
type Family={id:string;name:string;owned_contract:string;current_target:string;future_targets?:string[];status:string;external_network_required?:boolean};
type Summary={identity:string;infrastructure_owner:string;architecture:string;active_runtime:string;cutover_phase:string;production_cutover_complete:boolean;external_host_dependency_active:boolean;data_cutover_required:boolean;dns_cutover_required:boolean;families:Family[];rules:string[]};
async function read(r:Response){const t=await r.text();try{return JSON.parse(t)}catch{return{detail:t||('Request failed ('+r.status+')')}}}
const card={border:'1px solid #214756',borderRadius:14,padding:16,background:'#081117'} as const;
export default function OwnerInfrastructure(){
 const[data,setData]=useState<Summary|null>(null),[error,setError]=useState('');
 useEffect(()=>{const token=localStorage.getItem('odin_admin_token')||'';if(!token){location.replace('/owner-login?returnTo=%2Fowner-infrastructure');return}fetch(api+'/api/magnanimous/infrastructure',{headers:{Authorization:'Bearer '+token},cache:'no-store'}).then(async r=>{const d=await read(r);if(r.status===401||r.status===403){localStorage.removeItem('odin_admin_token');location.replace('/owner-login?returnTo=%2Fowner-infrastructure');return}if(!r.ok)throw new Error(d.detail||'Infrastructure status could not load.');setData(d)}).catch(e=>setError(e?.message||'Infrastructure status could not load.'))},[]);
 return <main style={{minHeight:'100vh',background:'#05080b',color:'#eaf7ff',padding:'24px 32px 60px',fontFamily:'Inter,system-ui,sans-serif'}}>
  <header style={{maxWidth:1400,margin:'auto',display:'flex',justifyContent:'space-between',fontSize:10,letterSpacing:'.16em',color:'#6d91a2'}}><a href="/owner-center" style={{color:'#7ae7ff'}}>← Owner Center</a><span>PRIVATE INFRASTRUCTURE CONTROL</span></header>
  <section style={{...card,maxWidth:1400,margin:'28px auto 0',display:'flex',justifyContent:'space-between',gap:24,alignItems:'center'}}><div><small style={{color:'#5dddf9'}}>I AM MAGNANIMOUS WAY™</small><h1 style={{fontSize:48,margin:'8px 0'}}>Magnanimous Infrastructure</h1><p style={{maxWidth:800,color:'#8fa6b2'}}>Magnanimous AI owns the control plane. Hosting, databases, model compute, DNS, storage and network services are replaceable execution rails beneath it.</p></div><div style={{display:'grid',gap:8,minWidth:230}}><b>{data?.production_cutover_complete?'STANDALONE ACTIVE':'PARALLEL MIGRATION'}</b><span>{data?.active_runtime||'Loading runtime…'}</span><span>{data?.cutover_phase||'Loading phase…'}</span></div></section>
  {error&&<div style={{...card,maxWidth:1400,margin:'12px auto',borderColor:'#69353b',color:'#ffb7c0'}}>{error}</div>}
  {data&&<><section style={{maxWidth:1400,margin:'12px auto',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10}}><article style={card}><small>OWNER</small><strong style={{display:'block',marginTop:7}}>{data.infrastructure_owner}</strong></article><article style={card}><small>ARCHITECTURE</small><strong style={{display:'block',marginTop:7}}>{data.architecture}</strong></article><article style={card}><small>DATA CUTOVER</small><strong style={{display:'block',marginTop:7}}>{data.data_cutover_required?'REQUIRED':'COMPLETE'}</strong></article><article style={card}><small>DNS CUTOVER</small><strong style={{display:'block',marginTop:7}}>{data.dns_cutover_required?'REQUIRED':'COMPLETE'}</strong></article></section>
  <section style={{maxWidth:1400,margin:'0 auto',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(290px,1fr))',gap:10}}>{data.families.map(f=><article style={card} key={f.id}><small style={{color:'#5dddf9'}}>{f.id.toUpperCase()}</small><h2>{f.name}</h2><p style={{color:'#8fa6b2'}}>{f.owned_contract}</p><p><b>NOW:</b> <code>{f.current_target}</code></p>{f.future_targets?.length?<p><b>NEXT:</b> <code>{f.future_targets.join(' · ')}</code></p>:null}<p style={{color:'#8ef0b0'}}>{f.status}</p>{f.external_network_required?<em style={{color:'#e7bd72'}}>Real public-network capacity remains an external infrastructure requirement.</em>:null}</article>)}</section>
  <section style={{...card,maxWidth:1400,margin:'10px auto'}}><h2>Magnanimous Infrastructure Rules</h2>{data.rules.map(rule=><p key={rule} style={{color:'#92a9b4'}}>• {rule}</p>)}</section></>}
 </main>;
}
