'use client';
export const PLAN_TERMS:Record<string,{version:string;title:string;summary:string;recurring:boolean}>={
 plus:{version:'unlimited-2026-09-18.1',title:'Unlimited Fair-Use Terms',summary:'$19.99/month. Ordinary platform access is subject to fair-use, safety, concurrency and anti-abuse controls. Third-party GPU, telecom, carrier, premium-model, storage and other metered/pass-through costs are not unlimited and require funded usage when applicable.',recurring:true},
 scale:{version:'annual-2026-09-18.1',title:'Annual Plan Terms',summary:'$199/year. Annual access renews yearly until canceled. Fair-use protections apply and separately metered/pass-through infrastructure is not lifetime or unlimited usage.',recurring:true},
 agency:{version:'agency-2026-09-18.1',title:'Agency Terms',summary:'$299/month. Includes White Label agency access and up to 25 managed client subaccounts subject to the stated capacities. Variable provider usage and client rebilling remain separately controlled and funded.',recurring:true},
 agency_pro:{version:'agency-pro-2026-09-18.1',title:'Agency Pro Terms',summary:'$499/month. Includes the higher-capacity White Label workspace and up to 100 managed client subaccounts subject to stated capacities. Variable provider usage and client rebilling remain separately controlled and funded.',recurring:true},
 prepaid10:{version:'prepaid10-2026-09-18.1',title:'$10 Prepaid Credit Terms',summary:'One-time $10 prepaid credit for eligible metered usage. It is not a recurring subscription and does not itself grant Unlimited, Annual, Agency or ownership rights.',recurring:false},
 prepaid25:{version:'prepaid25-2026-09-18.1',title:'$25 Prepaid Credit Terms',summary:'One-time $25 prepaid credit for eligible metered usage. It is not a recurring subscription and does not itself grant Unlimited, Annual, Agency or ownership rights.',recurring:false},
 ownership:{version:'ownership-2026-09-18.1',title:'Complete Ownership License Terms',summary:'One-time $499 software/license purchase for the covered Magnanimous rights identified at purchase. It does not include lifetime-free third-party infrastructure, telecom, GPU, taxes or other pass-through usage.',recurring:false}
};
export function PremiumAgreementConsent({checked,onChange,plan='plus'}:{checked:boolean,onChange:(v:boolean)=>void,plan?:string}){const t=PLAN_TERMS[plan]||PLAN_TERMS.plus;return <section><label><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/> I agree to the {t.title} for this purchase.</label><p>{t.summary}</p><p><a href={`/terms#terms-${plan}`} target="_blank" rel="noreferrer">Read the {t.title}</a></p>{t.recurring&&<p><strong>Recurring plan:</strong> This subscription renews at the price and interval stated above and at checkout until you cancel.</p>}</section>}