'use client';
export const PLAN_TERMS:Record<string,{version:string;title:string;summary:string;recurring:boolean}>={
 plus:{version:'unlimited-2026-09-18.1',title:'Unlimited Fair-Use Terms',summary:'$19.99/month. Ordinary platform access is subject to fair-use, safety, concurrency and anti-abuse controls. Third-party GPU, telecom, carrier, premium-model, storage and other metered/pass-through costs are not unlimited and require funded usage when applicable.',recurring:true},
 crm:{version:'crm-2026-10-10.1',title:'Magnanimous CRM Pro Terms',summary:'$79/month. Standalone Magnanimous CRM Pro includes the CRM and revenue-operations workspace under fair-use and security controls. Third-party enrichment, telecom, premium AI, storage and other metered provider usage is separately funded when applicable and charged under the disclosed 20% markup policy.',recurring:true},
 business:{version:'business-2026-10-10.2',title:'Magnanimous Business Terms',summary:'$214/month. Includes Magnanimous CRM Pro ($79), the Professional Business Plan ($79), and the $19.99 paid-platform baseline. The required 20% bundle upsell is applied to the $177.99 combined component value: $177.99 × 1.20 = $213.588, rounded to $214. Metered third-party provider usage remains separately funded when applicable.',recurring:true},
 pro:{version:'business-2026-10-10.2',title:'Magnanimous Business Terms',summary:'Legacy Pro selections map to Magnanimous Business at $214/month for new checkout. Existing paid subscriptions are not silently repriced by this terms update. Metered third-party provider usage remains separately funded when applicable.',recurring:true},
 scale:{version:'business-annual-2026-10-10.2',title:'Magnanimous Business Annual Terms',summary:'$2,568/year for new annual Business checkout, equal to twelve months of the $214 Business package. Includes CRM Pro, the Professional Business Plan, and the broader paid business platform. Existing subscriptions are not silently repriced. Fair-use protections apply and separately metered/pass-through infrastructure requires funded usage.',recurring:true},
 agency:{version:'agency-2026-09-18.1',title:'Agency Terms',summary:'$299/month. Includes White Label agency access and up to 25 managed client subaccounts subject to the stated capacities. Variable provider usage and client rebilling remain separately controlled and funded.',recurring:true},
 agency_pro:{version:'agency-pro-2026-09-18.1',title:'Agency Pro Terms',summary:'$499/month. Includes the higher-capacity White Label workspace and up to 100 managed client subaccounts subject to stated capacities. Variable provider usage and client rebilling remain separately controlled and funded.',recurring:true},
 prepaid10:{version:'prepaid10-2026-09-18.1',title:'$10 Prepaid Credit Terms',summary:'One-time $10 prepaid credit for eligible metered usage. It is not a recurring subscription and does not itself grant Unlimited, Annual, Agency or ownership rights.',recurring:false},
 prepaid25:{version:'prepaid25-2026-09-18.1',title:'$25 Prepaid Credit Terms',summary:'One-time $25 prepaid credit for eligible metered usage. It is not a recurring subscription and does not itself grant Unlimited, Annual, Agency or ownership rights.',recurring:false},
 ownership:{version:'ownership-2026-09-18.1',title:'Complete Ownership License Terms',summary:'One-time $499 software/license purchase for the covered Magnanimous rights identified at purchase. It does not include lifetime-free third-party infrastructure, telecom, GPU, taxes or other pass-through usage.',recurring:false}
};
export function PremiumAgreementConsent({checked,onChange,plan='plus'}:{checked:boolean,onChange:(v:boolean)=>void,plan?:string}){const t=PLAN_TERMS[plan]||PLAN_TERMS.plus;return <section><label><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/> I agree to the {t.title} for this purchase.</label><p>{t.summary}</p><p><a href={`/terms#terms-${plan}`} target="_blank" rel="noreferrer">Read the {t.title}</a></p>{t.recurring&&<p><strong>Recurring plan:</strong> This subscription renews at the price and interval stated above and at checkout until you cancel.</p>}</section>}
