'use client';
import {useEffect,useMemo,useState} from 'react';
import {getPlatformAuthToken} from '../../lib/magnanimous-session';

const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
type Row=Record<string,any>;
async function read(r:Response){const t=await r.text();try{return JSON.parse(t)}catch{return{detail:t||`Request failed (${r.status})`}}}

export default function BrandedAi(){
 const[token,setToken]=useState(''),[clients,setClients]=useState<Row[]>([]),[clientId,setClientId]=useState(''),[settings,setSettings]=useState<Row>({}),[brain,setBrain]=useState<Row>({}),[goal,setGoal]=useState(''),[answer,setAnswer]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 const client=useMemo(()=>clients.find(x=>x.id===clientId)||null,[clients,clientId]);
 useEffect(()=>{const t=getPlatformAuthToken();if(!t){location.replace('/login?returnTo=%2Fwhite-label%2Fbranded-ai');return}setToken(t);(async()=>{try{
   const [b,c]=await Promise.all([
    fetch(api+'/api/white-label/brain/status',{headers:{Authorization:'Bearer '+t},cache:'no-store'}),
    fetch(api+'/api/agency/clients',{headers:{Authorization:'Bearer '+t},cache:'no-store'})
   ]);const bd=await read(b),cd=await read(c);if(!b.ok)throw Error(bd.detail||'White Label AI is not available.');if(!c.ok)throw Error(cd.detail||'Could not load clients.');setBrain(bd);setClients(cd.clients||[]);if(cd.clients?.[0]?.id)setClientId(cd.clients[0].id);
  }catch(e:any){setMsg(e.message)}})()},[]);
 useEffect(()=>{if(token&&clientId)loadBrand(clientId)},[token,clientId]);
 async function loadBrand(id:string){try{const r=await fetch(api+'/api/agency/clients/'+encodeURIComponent(id)+'/settings',{headers:{Authorization:'Bearer '+token},cache:'no-store'}),d=await read(r);if(!r.ok)throw Error(d.detail||'Could not load brand settings.');setSettings(d.settings||{})}catch(e:any){setMsg(e.message)}}
 async function ask(){if(!goal.trim())return;setBusy(true);setAnswer('');setMsg('');try{const r=await fetch(api+'/api/white-label/brain/assist',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({app:'branded-ai',client_id:clientId,goal:goal.trim(),context:`Dedicated branded AI workspace for ${settings.brand_name||client?.name||'this client'}.`})}),d=await read(r);if(!r.ok)throw Error(d.detail||'Magnanimous could not answer.');setAnswer(d.output||'No answer returned.')}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function rate(helpful:boolean){if(!answer)return;await fetch(api+'/api/white-label/brain/feedback',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({app:'branded-ai',client_id:clientId,helpful})}).catch(()=>null);setMsg(helpful?'Magnanimous recorded that this helped.':'Magnanimous recorded that this needs improvement.')}
 const brand=settings.brand_name||client?.name||'Client AI',accent=/^#[0-9a-f]{3,8}$/i.test(String(settings.accent_color||''))?settings.accent_color:'#73dff8';
 return <main className="page" style={{'--accent':accent} as any}>
  <header><a href="/white-label">← White Label</a><b>BRANDED AI</b><a href="/agency-command?tab=branding">Brand settings →</a></header>
  <section className="hero"><small>MAGNANIMOUS AI • CLIENT-SCOPED • YOUR BRAND</small><h1>{brand}</h1><p>A dedicated Magnanimous workspace using this client’s approved brand and client context. The Magnanimous brain remains the platform intelligence layer and keeps each client’s private context separated.</p></section>
  {msg&&<div className="msg">{msg}</div>}
  <section className="layout"><aside><label>Client<select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">Choose client</option>{clients.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><div className="brand">{settings.logo_url&&<img src={settings.logo_url} alt="Client logo"/>}<b>{brand}</b><span>{settings.white_label_enabled?'White Label enabled':'Brand configured in preview mode'}</span></div><div className="stat"><b>{Number(brain.memory_count||0)}</b><span>learned workspace lessons</span></div><div className="stat"><b>{Number(brain.signal_count||0)}</b><span>private learning signals</span></div><p>Custom domains, calling, external messaging, publishing and other connected actions are only live when their real permissions and provider connections are configured.</p></aside>
   <section className="chat"><div className="head"><small>{brand.toUpperCase()}</small><h2>Ask Magnanimous</h2><p>Give it a client task in plain words.</p></div>{answer&&<article><small>MAGNANIMOUS AI</small><pre>{answer}</pre><div><button onClick={()=>rate(true)}>👍 Helpful</button><button onClick={()=>rate(false)}>👎 Improve</button></div></article>}<div className="compose"><textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Example: Write a welcome message for this client’s new customers."/><button onClick={ask} disabled={busy||!clientId||!goal.trim()}>{busy?'Working…':'Ask Magnanimous →'}</button></div></section>
  </section>
  <style jsx>{`
   *{box-sizing:border-box}.page{min-height:100vh;background:#050b10;color:#effaff;padding:24px 28px 70px;font-family:Inter,system-ui,sans-serif;background-image:radial-gradient(circle at 75% 0,color-mix(in srgb,var(--accent) 22%,transparent),transparent 30%)}header,.hero,.msg,.layout{max-width:1250px;margin-left:auto;margin-right:auto}header{display:flex;justify-content:space-between;font-size:10px;letter-spacing:.12em}a{color:var(--accent);text-decoration:none}.hero{padding:50px 0 24px}.hero small,.head small,article>small{color:var(--accent);letter-spacing:.15em;font-size:9px}.hero h1{font-size:clamp(44px,7vw,76px);line-height:.96;margin:8px 0}.hero p{max-width:850px;color:#8da5b0;line-height:1.65}.msg{border:1px solid #314d5b;border-radius:10px;background:#0b161e;padding:11px}.layout{display:grid;grid-template-columns:300px 1fr;gap:12px}.layout>aside,.chat{border:1px solid #233c48;border-radius:18px;background:#081219}.layout>aside{padding:17px}.layout label{font-size:9px;color:#83a0ac}.layout select,.compose textarea{width:100%;display:block;margin-top:5px;border:1px solid #2b4a57;border-radius:10px;background:#040a0e;color:#effaff;padding:11px}.brand{display:grid;place-items:center;text-align:center;border:1px solid #294856;border-radius:14px;padding:18px;margin:13px 0}.brand img{width:72px;height:72px;object-fit:contain;border-radius:14px;background:white;padding:5px;margin-bottom:10px}.brand b{font-size:20px}.brand span{font-size:9px;color:#758f9b;margin-top:4px}.stat{display:flex;justify-content:space-between;align-items:end;border-bottom:1px solid #1d3540;padding:10px 0}.stat b{font-size:25px;color:var(--accent)}.stat span{font-size:9px;color:#738d98}.layout aside>p{font-size:9px;color:#637d88;line-height:1.55}.chat{display:grid;grid-template-rows:auto 1fr auto;min-height:600px;padding:20px}.head h2{font-size:30px;margin:4px 0}.head p{color:#78929d;margin-top:0}.chat article{align-self:start;margin-top:15px;border:1px solid #234552;border-radius:14px;background:#0a1a23;padding:15px}.chat pre{white-space:pre-wrap;font:inherit;line-height:1.6;font-size:12px}.chat article div{display:flex;gap:7px}.chat article button,.compose button{border:1px solid #2e5665;border-radius:9px;background:#0d2530;color:#dff8ff;padding:8px 10px;cursor:pointer}.compose{align-self:end}.compose textarea{min-height:120px;resize:vertical}.compose button{width:100%;margin-top:8px;background:var(--accent);color:#041318;font-weight:950;border:0;padding:12px}.compose button:disabled{opacity:.45}@media(max-width:800px){.layout{grid-template-columns:1fr}.chat{min-height:520px}}@media(max-width:620px){.page{padding:18px 12px 60px}}`}</style>
 </main>
}