'use client';

import { FormEvent, useEffect, useState } from 'react';
import styles from '../sim/sim.module.css';

const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
type Counts={absorbed_patterns:number;standards:number;open_service_orders:number;open_trouble_tickets:number;network_functions:number;usage_events:number;open_fraud_cases:number;active_balance_accounts:number;active_routes:number};
type Overview={identity:string;brain:string;architecture:string;counts:Counts;principles:string[]};
type Pattern={pattern_key:string;category:string;pattern_name:string;status:string;source_family:string;magnanimous_use:string};
type Standard={standard_key:string;standard_family:string;version:string;lifecycle_status:string;magnanimous_scope:string};
type Plan={id:string;name:string;status?:string};
const empty:Overview={identity:'Magnanimous Telecom',brain:'Magnanimous AI',architecture:'carrier-grade OSS/BSS orchestration',counts:{absorbed_patterns:0,standards:0,open_service_orders:0,open_trouble_tickets:0,network_functions:0,usage_events:0,open_fraud_cases:0,active_balance_accounts:0,active_routes:0},principles:[]};
async function parse(response:Response){const text=await response.text();try{return JSON.parse(text)}catch{return{detail:text||`Request failed (${response.status})`}}
}

export default function TelecomOperationsPage(){
 const[token,setToken]=useState('');const[overview,setOverview]=useState<Overview>(empty);const[patterns,setPatterns]=useState<Pattern[]>([]);const[standards,setStandards]=useState<Standard[]>([]);const[plans,setPlans]=useState<Plan[]>([]);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);
 const[planId,setPlanId]=useState('');const[billingMode,setBillingMode]=useState('postpaid');const[validityDays,setValidityDays]=useState('30');const[autoRenew,setAutoRenew]=useState(true);const[noExpiry,setNoExpiry]=useState(false);const[roaming,setRoaming]=useState(false);const[shared,setShared]=useState(false);const[convertible,setConvertible]=useState(false);const[unliVoice,setUnliVoice]=useState(false);const[unliSms,setUnliSms]=useState(false);const[unliData,setUnliData]=useState(false);
 const[customerId,setCustomerId]=useState('');const[orderType,setOrderType]=useState('activate');const[orderPlan,setOrderPlan]=useState('');const[lineId,setLineId]=useState('');
 const[functionRole,setFunctionRole]=useState('sip_edge');const[implementation,setImplementation]=useState('magnanimous-native');const[hostRef,setHostRef]=useState('');const[region,setRegion]=useState('');const[functionStatus,setFunctionStatus]=useState('planned');
 const[ticketTitle,setTicketTitle]=useState('');const[ticketSeverity,setTicketSeverity]=useState('normal');const[ticketDetail,setTicketDetail]=useState('');

 useEffect(()=>{const saved=localStorage.getItem('magnanimous_admin_token')||localStorage.getItem('odin_admin_token')||localStorage.getItem('iam_account_token')||'';if(!saved){location.replace(`/login?returnTo=${encodeURIComponent('/telecom/operations')}`);return}setToken(saved);void refresh(saved)},[]);
 async function call(path:string,options:RequestInit={},activeToken=token){const headers=new Headers(options.headers||{});headers.set('Authorization',`Bearer ${activeToken}`);if(options.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');const response=await fetch(`${api}${path}`,{...options,headers});const data=await parse(response);if(!response.ok)throw new Error(data.detail||'Request failed.');return data}
 async function refresh(activeToken=token){try{const [summary,knowledge,catalog]=await Promise.all([call('/api/telecom/operations/overview',{},activeToken),call('/api/telecom/operations/knowledge',{},activeToken),call('/api/telecom/service/plans',{},activeToken)]);setOverview({...empty,...summary,counts:{...empty.counts,...(summary.counts||{})}});setPatterns(knowledge.patterns||[]);setStandards(knowledge.standards||[]);setPlans(catalog.plans||[]);if(!planId&&catalog.plans?.[0]?.id)setPlanId(catalog.plans[0].id);if(!orderPlan&&catalog.plans?.[0]?.id)setOrderPlan(catalog.plans[0].id);setError('')}catch(caught:any){setError(caught?.message||'Unable to load carrier operations.')}}
 async function savePlanPolicy(event:FormEvent){event.preventDefault();if(!planId)return;setBusy(true);setError('');setNotice('');try{await call(`/api/telecom/operations/plan-policy/${encodeURIComponent(planId)}`,{method:'PUT',body:JSON.stringify({billing_mode:billingMode,validity_seconds:noExpiry?0:Math.max(0,Number(validityDays||0))*86400,auto_renew:autoRenew,no_expiry:noExpiry,roaming_enabled:roaming,shared_balance_enabled:shared,convertible_allowances:convertible,unlimited_voice:unliVoice,unlimited_sms:unliSms,unlimited_data:unliData})});setNotice('Magnanimous plan behavior updated.')}catch(caught:any){setError(caught?.message||'Unable to update plan behavior.')}finally{setBusy(false)}}
 async function createOrder(event:FormEvent){event.preventDefault();setBusy(true);setError('');setNotice('');try{const result=await call('/api/telecom/operations/service-orders',{method:'POST',body:JSON.stringify({customer_id:customerId,line_id:lineId,plan_id:orderPlan,order_type:orderType})});setNotice(`Service order ${result.id} acknowledged.`);setCustomerId('');setLineId('');await refresh()}catch(caught:any){setError(caught?.message||'Unable to create service order.')}finally{setBusy(false)}}
 async function addFunction(event:FormEvent){event.preventDefault();setBusy(true);setError('');setNotice('');try{await call('/api/telecom/operations/network-functions',{method:'POST',body:JSON.stringify({function_role:functionRole,implementation_family:implementation,host_ref:hostRef,region,status:functionStatus})});setNotice('Network function added to Magnanimous inventory.');setHostRef('');await refresh()}catch(caught:any){setError(caught?.message||'Unable to add network function.')}finally{setBusy(false)}}
 async function openTicket(event:FormEvent){event.preventDefault();setBusy(true);setError('');setNotice('');try{const result=await call('/api/telecom/operations/trouble-tickets',{method:'POST',body:JSON.stringify({customer_id:customerId||undefined,line_id:lineId||undefined,title:ticketTitle,severity:ticketSeverity,detail:ticketDetail})});setNotice(`Trouble ticket ${result.id} opened.`);setTicketTitle('');setTicketDetail('');await refresh()}catch(caught:any){setError(caught?.message||'Unable to open trouble ticket.')}finally{setBusy(false)}}

 return <main className={styles.shell}>
  <header className={styles.header}><nav><a href='/telecom'>← TELECOM</a><a href='/telecom/plans'>PLANS</a><a href='/telecom/network'>CARRIER ACCESS</a><a href='/telecom/sim'>SIM + eSIM</a></nav><p className={styles.eyebrow}>MAGNANIMOUS TELECOM · OSS/BSS + NETWORK OPERATIONS</p><h1>Carrier <em>Operations</em></h1><p>Magnanimous AI owns the operating model: products, orders, subscriber service, usage, charging, routing, fraud, network functions, support and future mobile-core evolution. Outside systems remain replaceable adapters.</p></header>
  {error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}
  <section className={styles.metrics}><article><small>ABSORBED PATTERNS</small><strong>{overview.counts.absorbed_patterns}</strong></article><article><small>STANDARDS BASELINES</small><strong>{overview.counts.standards}</strong></article><article><small>SERVICE ORDERS</small><strong>{overview.counts.open_service_orders}</strong></article><article><small>TROUBLE TICKETS</small><strong>{overview.counts.open_trouble_tickets}</strong></article><article><small>NETWORK FUNCTIONS</small><strong>{overview.counts.network_functions}</strong></article></section>
  <section className={styles.status}><div><span className={styles.good}/><b>{overview.identity} · Brain: {overview.brain}</b></div><p>Telecom remains non-white-label. Research patterns are absorbed into Magnanimous architecture; external projects and carriers do not become the customer-facing identity.</p></section>
  <section className={styles.grid}>
   <form className={styles.card} onSubmit={savePlanPolicy}><small>PRODUCT + CHARGING</small><h2>Plan behavior</h2><label>Magnanimous plan<select value={planId} onChange={e=>setPlanId(e.target.value)}><option value=''>Select plan</option>{plans.map(plan=><option key={plan.id} value={plan.id}>{plan.name}</option>)}</select></label><label>Billing model<select value={billingMode} onChange={e=>setBillingMode(e.target.value)}><option value='postpaid'>Postpaid monthly</option><option value='prepaid'>Prepaid</option><option value='hybrid'>Hybrid</option></select></label><label>Validity days<input type='number' min='0' value={validityDays} onChange={e=>setValidityDays(e.target.value)} disabled={noExpiry}/></label><label><input type='checkbox' checked={autoRenew} onChange={e=>setAutoRenew(e.target.checked)}/> Auto renew</label><label><input type='checkbox' checked={noExpiry} onChange={e=>setNoExpiry(e.target.checked)}/> No-expiry allowance</label><label><input type='checkbox' checked={roaming} onChange={e=>setRoaming(e.target.checked)}/> Roaming enabled</label><label><input type='checkbox' checked={shared} onChange={e=>setShared(e.target.checked)}/> Shared balance/pool</label><label><input type='checkbox' checked={convertible} onChange={e=>setConvertible(e.target.checked)}/> Convertible allowances</label><label><input type='checkbox' checked={unliVoice} onChange={e=>setUnliVoice(e.target.checked)}/> Unlimited voice policy</label><label><input type='checkbox' checked={unliSms} onChange={e=>setUnliSms(e.target.checked)}/> Unlimited SMS policy</label><label><input type='checkbox' checked={unliData} onChange={e=>setUnliData(e.target.checked)}/> Unlimited data policy</label><button disabled={busy||!planId}>SAVE PLAN BEHAVIOR</button></form>
   <form className={styles.card} onSubmit={createOrder}><small>SERVICE FULFILLMENT</small><h2>Create service order</h2><label>Customer ID<input value={customerId} onChange={e=>setCustomerId(e.target.value)} placeholder='Magnanimous customer ID'/></label><label>Line ID<input value={lineId} onChange={e=>setLineId(e.target.value)} placeholder='Optional existing line'/></label><label>Plan<select value={orderPlan} onChange={e=>setOrderPlan(e.target.value)}><option value=''>Optional plan</option>{plans.map(plan=><option key={plan.id} value={plan.id}>{plan.name}</option>)}</select></label><label>Order type<select value={orderType} onChange={e=>setOrderType(e.target.value)}><option value='activate'>Activate</option><option value='change_plan'>Change plan</option><option value='add_on'>Add-on</option><option value='suspend'>Suspend</option><option value='resume'>Resume</option><option value='cancel'>Cancel</option><option value='port_in'>Port in</option><option value='port_out'>Port out</option><option value='sim_swap'>SIM swap</option><option value='esim_swap'>eSIM swap</option><option value='roaming_enable'>Enable roaming</option></select></label><button disabled={busy||!customerId.trim()}>CREATE ORDER</button></form>
   <form className={styles.card} onSubmit={addFunction}><small>NETWORK INVENTORY</small><h2>Add network function</h2><label>Role<select value={functionRole} onChange={e=>setFunctionRole(e.target.value)}><option value='sip_edge'>SIP edge / SBC</option><option value='pbx_media'>PBX / media</option><option value='call_control'>Call control</option><option value='charging'>Charging / rating</option><option value='observability'>Observability</option><option value='mobile_core_lab'>Mobile core lab</option><option value='ims_lab'>IMS / VoLTE lab</option><option value='provisioning'>Provisioning</option><option value='fraud'>Fraud engine</option></select></label><label>Implementation family<input value={implementation} onChange={e=>setImplementation(e.target.value)} placeholder='magnanimous-native or adapter family'/></label><label>Host reference<input value={hostRef} onChange={e=>setHostRef(e.target.value)} placeholder='Private host/service reference'/></label><label>Region<input value={region} onChange={e=>setRegion(e.target.value)} placeholder='Singapore, Philippines, US…'/></label><label>Status<select value={functionStatus} onChange={e=>setFunctionStatus(e.target.value)}><option value='planned'>Planned</option><option value='lab'>Lab</option><option value='configured'>Configured</option><option value='active'>Active</option></select></label><button disabled={busy}>ADD FUNCTION</button></form>
   <form className={styles.card} onSubmit={openTicket}><small>ASSURANCE</small><h2>Open trouble ticket</h2><label>Title<input value={ticketTitle} onChange={e=>setTicketTitle(e.target.value)} placeholder='No inbound audio, eSIM activation failed…'/></label><label>Severity<select value={ticketSeverity} onChange={e=>setTicketSeverity(e.target.value)}><option value='low'>Low</option><option value='normal'>Normal</option><option value='high'>High</option><option value='critical'>Critical</option></select></label><label>Detail<input value={ticketDetail} onChange={e=>setTicketDetail(e.target.value)} placeholder='Symptoms and context'/></label><button disabled={busy||!ticketTitle.trim()}>OPEN TICKET</button></form>
  </section>
  <section className={styles.inventory}><div className={styles.title}><div><small>ABSORBED INDUSTRY PATTERNS</small><h2>What Magnanimous learned and owns as architecture</h2></div><button onClick={()=>refresh()} disabled={busy}>REFRESH</button></div><div className={styles.table}>{patterns.map(pattern=><article key={pattern.pattern_key}><div><b>{pattern.pattern_name}</b><span>{pattern.status}</span></div><p>{pattern.magnanimous_use}</p><small>{pattern.category} · research family: {pattern.source_family}</small></article>)}</div></section>
  <section className={styles.inventory}><div className={styles.title}><div><small>STANDARDS WATCH</small><h2>Current architecture baselines</h2></div></div><div className={styles.table}>{standards.map(item=><article key={item.standard_key}><div><b>{item.standard_family}</b><span>{item.version}</span></div><p>{item.magnanimous_scope}</p><small>{item.lifecycle_status}</small></article>)}</div></section>
  <section className={styles.guardrail}><h2>Future mobile core: lab first, authority before public service</h2><p>Magnanimous can learn from and interoperate with EPC/5GC/IMS technologies, charging engines and SIP observability systems. Any mobile-core/RAN lab remains isolated until lawful spectrum access, host-network agreements, emergency routing, interconnection and operator authorization are actually in place.</p></section>
 </main>
}
