import {currentUser} from './integrations.js';
const J=(d,s=200)=>Response.json(d,{status:s,headers:{'cache-control':'no-store'}}),N=()=>Math.floor(Date.now()/1000),ID=()=>crypto.randomUUID(),S=(v,n=1000)=>String(v??'').trim().slice(0,n);
async function schema(env){for(const q of[
"CREATE TABLE IF NOT EXISTS credential_programs(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,owner_user_id TEXT NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',issuer_name TEXT NOT NULL DEFAULT 'I AM MAGNANIMOUS WAY',questions_json TEXT NOT NULL DEFAULT '[]',passing_score REAL NOT NULL DEFAULT 80,visibility TEXT NOT NULL DEFAULT 'workspace',status TEXT NOT NULL DEFAULT 'draft',accreditation_status TEXT NOT NULL DEFAULT 'platform-issued',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)",
"CREATE TABLE IF NOT EXISTS credential_attempts(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,program_id TEXT NOT NULL,score REAL NOT NULL DEFAULT 0,passed INTEGER NOT NULL DEFAULT 0,answers_json TEXT NOT NULL DEFAULT '[]',created_at INTEGER NOT NULL)",
"CREATE TABLE IF NOT EXISTS credential_awards(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,program_id TEXT NOT NULL,attempt_id TEXT NOT NULL,award_code TEXT NOT NULL UNIQUE,recipient_name TEXT NOT NULL,issuer_name TEXT NOT NULL,credential_title TEXT NOT NULL,score REAL NOT NULL DEFAULT 0,issued_at INTEGER NOT NULL,expires_at INTEGER,public_share INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'active',accreditation_status TEXT NOT NULL DEFAULT 'platform-issued',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)",
"CREATE INDEX IF NOT EXISTS idx_credential_programs_owner ON credential_programs(tenant_id,owner_user_id,updated_at DESC)",
"CREATE INDEX IF NOT EXISTS idx_credential_attempts_user ON credential_attempts(tenant_id,user_id,created_at DESC)",
"CREATE INDEX IF NOT EXISTS idx_credential_awards_user ON credential_awards(tenant_id,user_id,issued_at DESC)"
])await env.DB.prepare(q).run()}
function questions(raw){const src=Array.isArray(raw)?raw:[],out=[];for(const x of src.slice(0,50)){const q=S(x?.question,700),opts=(Array.isArray(x?.options)?x.options:[]).slice(0,6).map(v=>S(v,400)).filter(Boolean),a=Number(x?.answer_index);if(!q||opts.length<2||!Number.isInteger(a)||a<0||a>=opts.length)continue;out.push({question:q,options:opts,answer_index:a})}return out}
function safeProgram(row,owner=false){if(!row)return null;const q=JSON.parse(row.questions_json||'[]');return{id:row.id,title:row.title,description:row.description,issuer_name:row.issuer_name,passing_score:Number(row.passing_score),visibility:row.visibility,status:row.status,accreditation_status:'platform-issued',question_count:q.length,questions:owner?q:undefined,created_at:row.created_at,updated_at:row.updated_at}}
function quizProgram(row){if(!row)return null;const q=JSON.parse(row.questions_json||'[]');return{id:row.id,title:row.title,description:row.description,issuer_name:row.issuer_name,passing_score:Number(row.passing_score),accreditation_status:'platform-issued',questions:q.map((x,i)=>({index:i,question:x.question,options:x.options}))}}
function code(){return'MAG-'+crypto.randomUUID().replaceAll('-','').slice(0,14).toUpperCase()}
async function program(env,t,id){return env.DB.prepare('SELECT * FROM credential_programs WHERE id=? AND tenant_id=?').bind(id,t).first()}
export async function handleCredentials(request,env){const u=new URL(request.url);if(!u.pathname.startsWith('/api/credentials'))return null;await schema(env);
 const verify=u.pathname.match(/^\/api\/credentials\/verify\/([A-Z0-9-]+)$/i);
 if(verify&&request.method==='GET'){const row=await env.DB.prepare("SELECT award_code,recipient_name,issuer_name,credential_title,score,issued_at,expires_at,status,accreditation_status FROM credential_awards WHERE award_code=? AND public_share=1").bind(verify[1].toUpperCase()).first();if(!row)return J({valid:false,detail:'Public credential not found.'},404);const expired=Number(row.expires_at||0)>0&&Number(row.expires_at)<N();return J({valid:row.status==='active'&&!expired,...row,expired,notice:'This is a platform-issued credential. External accreditation is not implied.'})}
 const user=await currentUser(request,env).catch(()=>null);if(!user)return J({detail:'Sign in required.'},401);const t=String(user.tenant_id),uid=String(user.id),body=['POST','PUT','PATCH'].includes(request.method)?await request.clone().json().catch(()=>({})):{};
 if(u.pathname==='/api/credentials/programs'&&request.method==='GET'){const{results=[]}=await env.DB.prepare("SELECT * FROM credential_programs WHERE tenant_id=? AND (owner_user_id=? OR visibility='workspace') ORDER BY updated_at DESC LIMIT 100").bind(t,uid).all();return J({programs:results.map(x=>safeProgram(x,String(x.owner_user_id)===uid))})}
 if(u.pathname==='/api/credentials/programs'&&request.method==='POST'){const qs=questions(body.questions);if(!S(body.title,180)||!qs.length)return J({detail:'Program title and at least one valid question are required.'},400);const id=ID(),ts=N(),passing=Math.max(1,Math.min(100,Number(body.passing_score||80))),visibility=body.visibility==='private'?'private':'workspace',status=body.status==='active'?'active':'draft';await env.DB.prepare('INSERT INTO credential_programs(id,tenant_id,owner_user_id,title,description,issuer_name,questions_json,passing_score,visibility,status,accreditation_status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,"platform-issued",?,?)').bind(id,t,uid,S(body.title,180),S(body.description,3000),S(body.issuer_name||'I AM MAGNANIMOUS WAY',180),JSON.stringify(qs),passing,visibility,status,ts,ts).run();return J({program:safeProgram(await program(env,t,id),true),notice:'Created as a platform-issued credential program; external accreditation is not implied.'},201)}
 const pm=u.pathname.match(/^\/api\/credentials\/programs\/([^/]+)$/);
 if(pm&&request.method==='PATCH'){const row=await program(env,t,pm[1]);if(!row||String(row.owner_user_id)!==uid)return J({detail:'Credential program not found or not editable.'},404);const qs=body.questions===undefined?JSON.parse(row.questions_json||'[]'):questions(body.questions);if(!qs.length)return J({detail:'At least one valid question is required.'},400);const passing=body.passing_score===undefined?Number(row.passing_score):Math.max(1,Math.min(100,Number(body.passing_score))),visibility=body.visibility==='private'?'private':body.visibility==='workspace'?'workspace':row.visibility,status=['draft','active','archived'].includes(String(body.status))?String(body.status):row.status;await env.DB.prepare('UPDATE credential_programs SET title=?,description=?,issuer_name=?,questions_json=?,passing_score=?,visibility=?,status=?,updated_at=? WHERE id=? AND tenant_id=? AND owner_user_id=?').bind(S(body.title??row.title,180),S(body.description??row.description,3000),S(body.issuer_name??row.issuer_name,180),JSON.stringify(qs),passing,visibility,status,N(),row.id,t,uid).run();return J({program:safeProgram(await program(env,t,row.id),true)})}
 const quiz=u.pathname.match(/^\/api\/credentials\/programs\/([^/]+)\/quiz$/);
 if(quiz&&request.method==='GET'){const row=await program(env,t,quiz[1]);if(!row||!(row.status==='active'&&(row.visibility==='workspace'||String(row.owner_user_id)===uid)))return J({detail:'Credential quiz is not available.'},404);return J({program:quizProgram(row)})}
 const attempt=u.pathname.match(/^\/api\/credentials\/programs\/([^/]+)\/attempt$/);
 if(attempt&&request.method==='POST'){const row=await program(env,t,attempt[1]);if(!row||!(row.status==='active'&&(row.visibility==='workspace'||String(row.owner_user_id)===uid)))return J({detail:'Credential quiz is not available.'},404);const qs=JSON.parse(row.questions_json||'[]'),answers=Array.isArray(body.answers)?body.answers.slice(0,qs.length).map(Number):[];if(answers.length!==qs.length||!answers.every(Number.isInteger))return J({detail:'Answer every question before submitting.'},400);const correct=qs.reduce((n,q,i)=>n+(answers[i]===q.answer_index?1:0),0),score=qs.length?Math.round(correct/qs.length*10000)/100:0,passed=score>=Number(row.passing_score),aid=ID(),ts=N();await env.DB.prepare('INSERT INTO credential_attempts(id,tenant_id,user_id,program_id,score,passed,answers_json,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(aid,t,uid,row.id,score,passed?1:0,JSON.stringify(answers),ts).run();let award=null;if(passed){const wid=ID(),awardCode=code(),name=S(body.recipient_name||user.name||user.email||'Credential recipient',180);await env.DB.prepare('INSERT INTO credential_awards(id,tenant_id,user_id,program_id,attempt_id,award_code,recipient_name,issuer_name,credential_title,score,issued_at,expires_at,public_share,status,accreditation_status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,NULL,0,"active","platform-issued",?,?)').bind(wid,t,uid,row.id,aid,awardCode,name,row.issuer_name,row.title,score,ts,ts,ts).run();award=await env.DB.prepare('SELECT id,award_code,recipient_name,issuer_name,credential_title,score,issued_at,expires_at,public_share,status,accreditation_status FROM credential_awards WHERE id=? AND tenant_id=? AND user_id=?').bind(wid,t,uid).first()}return J({attempt:{id:aid,score,passed},award,notice:passed?'Platform-issued completion credential created. External accreditation is not implied.':'Passing score not reached; no credential was issued.'},201)}
 if(u.pathname==='/api/credentials/awards'&&request.method==='GET'){const{results=[]}=await env.DB.prepare('SELECT id,award_code,recipient_name,issuer_name,credential_title,score,issued_at,expires_at,public_share,status,accreditation_status FROM credential_awards WHERE tenant_id=? AND user_id=? ORDER BY issued_at DESC LIMIT 100').bind(t,uid).all();return J({awards:results.map(x=>({...x,public_share:Boolean(x.public_share)}))})}
 const am=u.pathname.match(/^\/api\/credentials\/awards\/([^/]+)$/);
 if(am&&request.method==='PATCH'){const share=body.public_share===true?1:0;const r=await env.DB.prepare('UPDATE credential_awards SET public_share=?,updated_at=? WHERE id=? AND tenant_id=? AND user_id=?').bind(share,N(),am[1],t,uid).run();if(!r.meta?.changes)return J({detail:'Credential award not found.'},404);return J({ok:true,id:am[1],public_share:Boolean(share)})}
 return J({detail:'Credential route not found.'},404)}
