const VIDEO_RENDERER_DEFAULT_URL = 'https://iammagnanimousway-js.onrender.com';
const TOOLS = [
  ['odin','Odin AI Orchestrator','Routes requests across configured AI providers and platform tools.'],
  ['ai-chat','AI Chat','General-purpose AI assistant.'],
  ['writing','Writing Helper','Create, rewrite, summarize and polish content.'],
  ['research','Research Helper','Organize research questions, sources and briefs.'],
  ['bible-study','Bible Study','Study Scripture and organize biblical topics.'],
  ['marketing','Marketing Helper','Create campaigns, captions, offers and content plans.'],
  ['business','Business Helper','Business planning, ideas and analysis.'],
  ['coding','Coding Helper','Explain, generate and troubleshoot code.'],
  ['video-studio','Text → Video Studio','Create creator-ready video content.'],
  ['social','Social Media Helper','Create platform-ready social posts and scripts.'],
  ['video-script','Video Script Helper','Create short- and long-form video scripts.'],
  ['travel','Travel Helper','Build travel plans and itineraries.'],
  ['customer-service','Customer Service Helper','Draft helpful customer responses.'],
].map(([id,name,description]) => ({id,name,description}));

const json = (data, status = 200) => new Response(JSON.stringify(data), {status, headers:{'content-type':'application/json; charset=utf-8'}});
const unauthorized = () => json({detail:'Admin login required'},401);
const now = () => Math.floor(Date.now()/1000);
async function hmac(secret, value) { const key = await crypto.subtle.importKey('raw', new TextEncoder().encode(secret), {name:'HMAC',hash:'SHA-256'}, false, ['sign']); const bytes = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(value)); return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join(''); }
async function session(email, env) { const exp=now()+86400; const payload=`${email}|${exp}`; return `${payload}|${await hmac(env.SESSION_SECRET,payload)}`; }
async function validSession(request, env) { const auth=request.headers.get('authorization')||''; if(!auth.startsWith('Bearer ')||!env.SESSION_SECRET||!env.ADMIN_EMAIL)return false; const token=auth.slice(7).split('|'); if(token.length!==3)return false; const [email,exp,sig]=token; if(email!==env.ADMIN_EMAIL||Number(exp)<now())return false; return sig===await hmac(env.SESSION_SECRET,`${email}|${exp}`); }
async function init(env) { await env.DB.batch([env.DB.prepare("CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL)"),env.DB.prepare("CREATE TABLE IF NOT EXISTS ads (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, url TEXT NOT NULL, label TEXT NOT NULL DEFAULT 'Sponsored', placement TEXT NOT NULL DEFAULT 'home', active INTEGER NOT NULL DEFAULT 1, created_at INTEGER NOT NULL)"),env.DB.prepare("CREATE TABLE IF NOT EXISTS crm_contacts (id INTEGER PRIMARY KEY AUTOINCREMENT, first_name TEXT NOT NULL, last_name TEXT NOT NULL DEFAULT '', email TEXT NOT NULL DEFAULT '', phone TEXT NOT NULL DEFAULT '', company TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'lead', source TEXT NOT NULL DEFAULT '', tags TEXT NOT NULL DEFAULT '', notes TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)"),env.DB.prepare("CREATE TABLE IF NOT EXISTS crm_activities (id INTEGER PRIMARY KEY AUTOINCREMENT, contact_id INTEGER NOT NULL, type TEXT NOT NULL DEFAULT 'note', title TEXT NOT NULL DEFAULT '', body TEXT NOT NULL DEFAULT '', due_at INTEGER, completed INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, FOREIGN KEY(contact_id) REFERENCES crm_contacts(id) ON DELETE CASCADE)"),env.DB.prepare("CREATE TABLE IF NOT EXISTS crm_opportunities (id INTEGER PRIMARY KEY AUTOINCREMENT, contact_id INTEGER, name TEXT NOT NULL, stage TEXT NOT NULL DEFAULT 'new', value REAL NOT NULL DEFAULT 0, probability REAL NOT NULL DEFAULT 0, expected_close_at INTEGER, notes TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, FOREIGN KEY(contact_id) REFERENCES crm_contacts(id) ON DELETE SET NULL)"),env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_crm_contacts_status ON crm_contacts(status)"),env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_crm_activities_contact ON crm_activities(contact_id)"),env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_crm_opportunities_stage ON crm_opportunities(stage)"),env.DB.prepare("INSERT OR IGNORE INTO settings(key,value) VALUES('site_name','I AM Magnanimous AI Platform')"),env.DB.prepare("INSERT OR IGNORE INTO settings(key,value) VALUES('tagline','Free AI tools, Odin orchestration, and creator tools in one place.')"),env.DB.prepare("INSERT OR IGNORE INTO settings(key,value) VALUES('canva_url','')")]); }
async function settings(env){const {results}=await env.DB.prepare('SELECT key,value FROM settings').all();const data=Object.fromEntries(results.map(r=>[r.key,r.value]));return {site_name:data.site_name||'I AM Magnanimous AI Platform',tagline:data.tagline||'',canva_url:data.canva_url||''};}
function rendererUrl(env){return (env.VIDEO_RENDERER_URL||VIDEO_RENDERER_DEFAULT_URL).replace(/\/$/,'');}

export default { async fetch(request,env){ try { await init(env); const url=new URL(request.url); const path=url.pathname; if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,PUT,DELETE,OPTIONS','access-control-allow-headers':'Content-Type, Authorization'}});
if(path==='/health')return json({status:'ok',service:'iamagnanimous-ai',version:'3.3.0-video-renderer-fallback'});
if(path==='/api/tools')return json({tools:TOOLS});
if(path==='/api/providers')return json({providers:[{id:'openai',name:'OpenAI',configured:Boolean(env.OPENAI_API_KEY)},{id:'cloudflare-ai',name:'Cloudflare Workers AI',configured:Boolean(env.AI)},{id:'video-renderer',name:'FFmpeg Video Renderer',configured:true}]});
if(path==='/api/video/render'&&request.method==='POST'){const target=`${rendererUrl(env)}/api/video/render`;const body=await request.text();const headers=new Headers({'content-type':request.headers.get('content-type')||'application/json'});if(env.VIDEO_RENDERER_TOKEN)headers.set('authorization',`Bearer ${env.VIDEO_RENDERER_TOKEN}`);const response=await fetch(target,{method:'POST',headers,body});const text=await response.text();return new Response(text,{status:response.status,headers:{'content-type':response.headers.get('content-type')||'application/json'}});}
if(path.startsWith('/api/video/download/')&&request.method==='GET'){const filename=path.split('/').pop();if(!filename||filename.includes('..')||!filename.endsWith('.mp4'))return json({detail:'Invalid video filename'},400);const target=`${rendererUrl(env)}/api/video/download/${encodeURIComponent(filename)}`;const headers=new Headers();if(env.VIDEO_RENDERER_TOKEN)headers.set('authorization',`Bearer ${env.VIDEO_RENDERER_TOKEN}`);return fetch(target,{headers});}
if(path==='/api/ads'&&request.method==='GET'){const placement=url.searchParams.get('placement')||'home';const {results}=await env.DB.prepare('SELECT id,title,url,label,placement,active FROM ads WHERE active=1 AND placement=? ORDER BY id DESC').bind(placement).all();return json({ads:results});}
if(path==='/api/admin/login'&&request.method==='POST'){const body=await request.json();if(!env.ADMIN_EMAIL||!env.ADMIN_PASSWORD||body.email!==env.ADMIN_EMAIL||body.password!==env.ADMIN_PASSWORD)return json({detail:'Invalid email or password'},401);return json({token:await session(body.email,env),email:body.email});}
if(path.startsWith('/api/crm/')){if(!(await validSession(request,env)))return unauthorized();if(path==='/api/crm/summary'&&request.method==='GET'){const [contacts,leads,customers,openOpps,activities]=await Promise.all([env.DB.prepare('SELECT COUNT(*) AS count FROM crm_contacts').first(),env.DB.prepare("SELECT COUNT(*) AS count FROM crm_contacts WHERE status IN ('lead','qualified')").first(),env.DB.prepare("SELECT COUNT(*) AS count FROM crm_contacts WHERE status='customer'").first(),env.DB.prepare("SELECT COALESCE(SUM(value),0) AS value FROM crm_opportunities WHERE stage NOT IN ('won','lost')").first(),env.DB.prepare("SELECT COUNT(*) AS count FROM crm_activities WHERE completed=0 AND (due_at IS NULL OR due_at<=?)").bind(now()).first()]);return json({contacts:contacts?.count||0,leads:leads?.count||0,customers:customers?.count||0,pipeline_value:openOpps?.value||0,overdue_tasks:activities?.count||0});}}
if(path.startsWith('/api/admin/')){if(!(await validSession(request,env)))return unauthorized();if(path==='/api/admin/settings'&&request.method==='GET')return json(await settings(env));}
if(path==='/api/chat'&&request.method==='POST'){const body=await request.json();if(!env.OPENAI_API_KEY)return json({output:'Odin is online, but no OpenAI API key is configured yet. Add OPENAI_API_KEY as a Cloudflare Worker secret to enable cloud AI.',provider:'local'});const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${env.OPENAI_API_KEY}`},body:JSON.stringify({model:body.model||env.OPENAI_MODEL||'gpt-5.6',input:String(body.message||'')})});const data=await response.json();if(!response.ok)return json({detail:data.error?.message||'AI provider error'},502);return json({output:data.output_text||'',provider:'openai'});}
if(env.ASSETS)return env.ASSETS.fetch(request);return new Response('Not Found',{status:404}); } catch(error){return json({detail:error instanceof Error?error.message:'Server error'},500);} } };