const VIDEO_RENDERER_DEFAULT_URL='https://iammagnanimousway-js.onrender.com';
const TOOLS=[['odin','Magnanimous AI Orchestrator','Routes requests across configured AI providers and platform tools.'],['ai-chat','AI Chat','General-purpose AI assistant.'],['writing','Writing Helper','Create, rewrite, summarize and polish content.'],['research','Research Helper','Organize research questions, sources and briefs.'],['bible-study','Bible Study','Study Scripture and organize biblical topics.'],['marketing','Marketing Helper','Create campaigns, captions, offers and content plans.'],['business','Business Helper','Business planning, ideas and analysis.'],['coding','Coding Helper','Explain, generate and troubleshoot code.'],['video-studio','Text → Video Studio','Create creator-ready video content.'],['social','Social Media Helper','Create platform-ready social posts and scripts.'],['video-script','Video Script Helper','Create short- and long-form video scripts.'],['travel','Travel Helper','Build travel plans and itineraries.'],['customer-service','Customer Service Helper','Draft helpful customer responses.']].map(([id,name,description])=>({id,name,description}));
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const now=()=>Math.floor(Date.now()/1000);
const id=()=>crypto.randomUUID();
const normEmail=e=>String(e||'').trim().toLowerCase();
async function digest(value){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function hmac(secret,value){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const b=await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(value));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function passwordHash(password,salt){return digest(`${salt}:${password}`);}
async function makeSession(user,env){const exp=now()+604800;const payload=`${user.id}|${user.tenant_id}|${user.role}|${exp}`;return `${payload}|${await hmac(env.SESSION_SECRET||'change-me',payload)}`;}
async function auth(request,env){const raw=request.headers.get('authorization')||'';if(!raw.startsWith('Bearer '))return null;const p=raw.slice(7).split('|');if(p.length!==5||Number(p[3])<now())return null;const [userId,tenantId,role,exp,sig]=p;if(sig!==await hmac(env.SESSION_SECRET||'change-me',`${userId}|${tenantId}|${role}|${exp}`))return null;const user=await env.DB.prepare('SELECT id,tenant_id,name,email,role,active FROM users WHERE id=? AND tenant_id=? AND active=1').bind(userId,tenantId).first();return user||null;}
function rendererUrl(env){return(env.VIDEO_RENDERER_URL||VIDEO_RENDERER_DEFAULT_URL).replace(/\/$/,'');}
async function init(env){
 const sql=[
 'CREATE TABLE IF NOT EXISTS tenants (id TEXT PRIMARY KEY,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,owner_user_id TEXT,created_at INTEGER NOT NULL)',
 'CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,name TEXT NOT NULL,email TEXT NOT NULL,role TEXT NOT NULL DEFAULT \'member\',password_hash TEXT NOT NULL,password_salt TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL,UNIQUE(tenant_id,email))',
 'CREATE TABLE IF NOT EXISTS tenant_settings (tenant_id TEXT NOT NULL,key TEXT NOT NULL,value TEXT NOT NULL,PRIMARY KEY(tenant_id,key))',
 'CREATE TABLE IF NOT EXISTS crm_contacts (id INTEGER PRIMARY KEY AUTOINCREMENT,tenant_id TEXT,first_name TEXT NOT NULL,last_name TEXT NOT NULL DEFAULT \'\',email TEXT NOT NULL DEFAULT \'\',phone TEXT NOT NULL DEFAULT \'\',company TEXT NOT NULL DEFAULT \'\',status TEXT NOT NULL DEFAULT \'lead\',source TEXT NOT NULL DEFAULT \'\',tags TEXT NOT NULL DEFAULT \'\',notes TEXT NOT NULL DEFAULT \'\',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)',
 'CREATE TABLE IF NOT EXISTS crm_activities (id INTEGER PRIMARY KEY AUTOINCREMENT,tenant_id TEXT,contact_id INTEGER NOT NULL,type TEXT NOT NULL DEFAULT \'note\',title TEXT NOT NULL DEFAULT \'\',body TEXT NOT NULL DEFAULT \'\',due_at INTEGER,completed INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL)',
 'CREATE TABLE IF NOT EXISTS crm_opportunities (id INTEGER PRIMARY KEY AUTOINCREMENT,tenant_id TEXT,contact_id INTEGER,name TEXT NOT NULL,stage TEXT NOT NULL DEFAULT \'new\',value REAL NOT NULL DEFAULT 0,probability REAL NOT NULL DEFAULT 0,expected_close_at INTEGER,notes TEXT NOT NULL DEFAULT \'\',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)',
 'CREATE TABLE IF NOT EXISTS ads (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,url TEXT NOT NULL,label TEXT NOT NULL DEFAULT \'Sponsored\',placement TEXT NOT NULL DEFAULT \'home\',active INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL)',
 'CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY,value TEXT NOT NULL)',
 'CREATE INDEX IF NOT EXISTS idx_contacts_tenant ON crm_contacts(tenant_id)',
 'CREATE INDEX IF NOT EXISTS idx_activities_tenant ON crm_activities(tenant_id)',
 'CREATE INDEX IF NOT EXISTS idx_opps_tenant ON crm_opportunities(tenant_id)'
 ];
 for(const q of sql)try{await env.DB.prepare(q).run()}catch(e){}
 let ownerTenant=null;
 if(env.ADMIN_EMAIL){ownerTenant=await env.DB.prepare('SELECT * FROM tenants WHERE slug=?').bind('owner').first();if(!ownerTenant){const t=id();await env.DB.prepare('INSERT INTO tenants(id,name,slug,created_at) VALUES(?,?,?,?)').bind(t,'I AM Magnanimous','owner',now()).run();ownerTenant=await env.DB.prepare('SELECT * FROM tenants WHERE id=?').bind(t).first();}
 const email=normEmail(env.ADMIN_EMAIL);let owner=await env.DB.prepare('SELECT * FROM users WHERE tenant_id=? AND email=?').bind(ownerTenant.id,email).first();if(!owner&&env.ADMIN_PASSWORD){const salt=id();const ph=await passwordHash(env.ADMIN_PASSWORD,salt);const uid=id();await env.DB.prepare('INSERT INTO users(id,tenant_id,name,email,role,password_hash,password_salt,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(uid,ownerTenant.id,'Owner',email,'owner',ph,salt,now()).run();await env.DB.prepare('UPDATE tenants SET owner_user_id=? WHERE id=?').bind(uid,ownerTenant.id).run();}}
 if(ownerTenant){for(const table of ['crm_contacts','crm_activities','crm_opportunities'])try{await env.DB.prepare(`UPDATE ${table} SET tenant_id=? WHERE tenant_id IS NULL`).bind(ownerTenant.id).run()}catch(e){}}
 await env.DB.batch([env.DB.prepare("INSERT OR IGNORE INTO settings(key,value) VALUES('site_name','I AM Magnanimous AI Platform')"),env.DB.prepare("INSERT OR IGNORE INTO settings(key,value) VALUES('tagline','Free-first AI tools, Magnanimous orchestration, and creator tools in one place.')")]);
}
function tenantRequired(user){return user?.tenant_id||null;}
export default {async fetch(request,env){try{await init(env);const u=new URL(request.url),path=u.pathname;if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,PUT,DELETE,OPTIONS','access-control-allow-headers':'Content-Type, Authorization'}});
if(path==='/health')return json({status:'ok',service:'iamagnanimous-ai',version:'4.0.0-multitenant'});
if(path==='/api/tools')return json({tools:TOOLS});
if(path==='/api/providers')return json({providers:[{id:'openai',name:'OpenAI',configured:Boolean(env.OPENAI_API_KEY)},{id:'cloudflare-ai',name:'Cloudflare Workers AI',configured:Boolean(env.AI)},{id:'video-renderer',name:'FFmpeg Video Renderer',configured:true},{id:'mux',name:'Mux Video',configured:Boolean(env.MUX_TOKEN_ID&&env.MUX_TOKEN_SECRET)}]});
if(path==='/api/auth/signup'&&request.method==='POST'){const b=await request.json();const email=normEmail(b.email),name=String(b.name||'').trim(),password=String(b.password||'');if(!name||!email||password.length<8)return json({detail:'Name, email, and a password of at least 8 characters are required.'},400);if(!env.SESSION_SECRET)return json({detail:'Authentication is not configured. Add SESSION_SECRET.'},503);if(await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first())return json({detail:'An account with that email already exists.'},409);let slug=String(b.workspace||name).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,40)||'workspace';if(await env.DB.prepare('SELECT id FROM tenants WHERE slug=?').bind(slug).first())slug=`${slug}-${Math.floor(Math.random()*9999)}`;const tid=id(),uid=id(),salt=id(),ph=await passwordHash(password,salt);await env.DB.prepare('INSERT INTO tenants(id,name,slug,owner_user_id,created_at) VALUES(?,?,?,?,?)').bind(tid,String(b.workspace||name),slug,uid,now()).run();await env.DB.prepare('INSERT INTO users(id,tenant_id,name,email,role,password_hash,password_salt,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(uid,tid,name,email,'member',ph,salt,now()).run();await env.DB.batch([env.DB.prepare("INSERT INTO tenant_settings(tenant_id,key,value) VALUES(?,?,?)").bind(tid,'site_name',String(b.workspace||'I AM Workspace')),env.DB.prepare("INSERT INTO tenant_settings(tenant_id,key,value) VALUES(?,?,?)").bind(tid,'tagline','Your private I AM workspace.')]);const user=await env.DB.prepare('SELECT id,tenant_id,name,email,role FROM users WHERE id=?').bind(uid).first();return json({token:await makeSession(user,env),user},201);}
if(path==='/api/auth/login'&&request.method==='POST'){const b=await request.json(),email=normEmail(b.email),user=await env.DB.prepare('SELECT * FROM users WHERE email=? AND active=1').bind(email).first();if(!user)return json({detail:'Invalid email or password'},401);if((await passwordHash(String(b.password||''),user.password_salt))!==user.password_hash)return json({detail:'Invalid email or password'},401);return json({token:await makeSession(user,env),user:{id:user.id,tenant_id:user.tenant_id,name:user.name,email:user.email,role:user.role}});}
const user=await auth(request,env);
if(path==='/api/auth/me'&&request.method==='GET')return user?json({user}):json({detail:'Not authenticated'},401);
if(path==='/api/auth/logout')return json({ok:true});
if(path==='/api/video/render'&&request.method==='POST'){const target=`${rendererUrl(env)}/api/video/render`;const body=await request.text(),h=new Headers({'content-type':request.headers.get('content-type')||'application/json'});if(env.VIDEO_RENDERER_TOKEN)h.set('authorization',`Bearer ${env.VIDEO_RENDERER_TOKEN}`);const r=await fetch(target,{method:'POST',headers:h,body});const text=await r.text();return new Response(text,{status:r.status,headers:{'content-type':r.headers.get('content-type')||'application/json'}});}
if(path.startsWith('/api/video/download/')&&request.method==='GET'){const filename=path.split('/').pop();if(!filename||filename.includes('..')||!filename.endsWith('.mp4'))return json({detail:'Invalid video filename'},400);const h=new Headers();if(env.VIDEO_RENDERER_TOKEN)h.set('authorization',`Bearer ${env.VIDEO_RENDERER_TOKEN}`);return fetch(`${rendererUrl(env)}/api/video/download/${encodeURIComponent(filename)}`,{headers:h});}
if(path==='/api/ads'&&request.method==='GET'){const placement=u.searchParams.get('placement')||'home';const {results}=await env.DB.prepare('SELECT id,title,url,label,placement,active FROM ads WHERE active=1 AND placement=? ORDER BY id DESC').bind(placement).all();return json({ads:results});}
if(path==='/api/chat'&&request.method==='POST'){const b=await request.json();if(!env.OPENAI_API_KEY)return json({output:'Magnanimous AI is online, but no AI provider is configured yet.',provider:'local'});const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${env.OPENAI_API_KEY}`},body:JSON.stringify({model:b.model||env.OPENAI_MODEL||'gpt-5.6',input:String(b.message||'')})});const d=await r.json();if(!r.ok)return json({detail:d.error?.message||'AI provider error'},502);return json({output:d.output_text||'',provider:'openai'});}
if(path.startsWith('/api/crm/')){if(!user)return json({detail:'Sign in required'},401);const tid=tenantRequired(user);if(path==='/api/crm/summary'&&request.method==='GET'){const [a,b,c,d,e]=await Promise.all([env.DB.prepare('SELECT COUNT(*) count FROM crm_contacts WHERE tenant_id=?').bind(tid).first(),env.DB.prepare("SELECT COUNT(*) count FROM crm_contacts WHERE tenant_id=? AND status IN ('lead','qualified')").bind(tid).first(),env.DB.prepare("SELECT COUNT(*) count FROM crm_contacts WHERE tenant_id=? AND status='customer'").bind(tid).first(),env.DB.prepare("SELECT COALESCE(SUM(value),0) value FROM crm_opportunities WHERE tenant_id=? AND stage NOT IN ('won','lost')").bind(tid).first(),env.DB.prepare('SELECT COUNT(*) count FROM crm_activities WHERE tenant_id=? AND completed=0 AND (due_at IS NULL OR due_at<=?)').bind(tid,now()).first()]);return json({contacts:a?.count||0,leads:b?.count||0,customers:c?.count||0,pipeline_value:d?.value||0,overdue_tasks:e?.count||0});}
if(path==='/api/crm/contacts'&&request.method==='GET'){const q=u.searchParams.get('q')||'',status=u.searchParams.get('status')||'';let sql='SELECT * FROM crm_contacts WHERE tenant_id=?',args=[tid];if(q){sql+=' AND (first_name LIKE ? OR last_name LIKE ? OR email LIKE ? OR phone LIKE ? OR company LIKE ?)';const x=`%${q}%`;args.push(x,x,x,x,x)}if(status){sql+=' AND status=?';args.push(status)}sql+=' ORDER BY id DESC';const {results}=await env.DB.prepare(sql).bind(...args).all();return json({contacts:results.map(c=>({...c,tags:String(c.tags||'').split(',').map(x=>x.trim()).filter(Boolean)}))});}
if(path==='/api/crm/contacts'&&request.method==='POST'){const b=await request.json(),t=now();const r=await env.DB.prepare('INSERT INTO crm_contacts(tenant_id,first_name,last_name,email,phone,company,status,source,tags,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(tid,b.first_name||'',b.last_name||'',b.email||'',b.phone||'',b.company||'',b.status||'lead',b.source||'',Array.isArray(b.tags)?b.tags.join(', '):(b.tags||''),b.notes||'',t,t).run();return json({id:r.meta.last_row_id},201);}
const cm=path.match(/^\/api\/crm\/contacts\/(\d+)$/);if(cm){const cid=Number(cm[1]);if(request.method==='PUT'){const b=await request.json();await env.DB.prepare('UPDATE crm_contacts SET first_name=?,last_name=?,email=?,phone=?,company=?,status=?,source=?,tags=?,notes=?,updated_at=? WHERE id=? AND tenant_id=?').bind(b.first_name||'',b.last_name||'',b.email||'',b.phone||'',b.company||'',b.status||'lead',b.source||'',Array.isArray(b.tags)?b.tags.join(', '):(b.tags||''),b.notes||'',now(),cid,tid).run();return json({ok:true});}if(request.method==='DELETE'){await env.DB.batch([env.DB.prepare('DELETE FROM crm_activities WHERE contact_id=? AND tenant_id=?').bind(cid,tid),env.DB.prepare('DELETE FROM crm_opportunities WHERE contact_id=? AND tenant_id=?').bind(cid,tid),env.DB.prepare('DELETE FROM crm_contacts WHERE id=? AND tenant_id=?').bind(cid,tid)]);return json({ok:true});}}
if(path==='/api/crm/opportunities'&&request.method==='GET'){const {results}=await env.DB.prepare('SELECT o.*,c.first_name,c.last_name,c.company FROM crm_opportunities o LEFT JOIN crm_contacts c ON c.id=o.contact_id AND c.tenant_id=o.tenant_id WHERE o.tenant_id=? ORDER BY o.updated_at DESC').bind(tid).all();return json({opportunities:results});}
if(path==='/api/crm/opportunities'&&request.method==='POST'){const b=await request.json(),t=now();const r=await env.DB.prepare('INSERT INTO crm_opportunities(tenant_id,contact_id,name,stage,value,probability,expected_close_at,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(tid,b.contact_id?Number(b.contact_id):null,String(b.name||'Untitled opportunity'),String(b.stage||'new'),Number(b.value||0),Number(b.probability||0),b.expected_close_at?Number(b.expected_close_at):null,String(b.notes||''),t,t).run();return json({ok:true,id:r.meta.last_row_id},201);}
if(path==='/api/crm/activities'&&request.method==='POST'){const b=await request.json();const r=await env.DB.prepare('INSERT INTO crm_activities(tenant_id,contact_id,type,title,body,due_at,completed,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(tid,Number(b.contact_id),String(b.type||'note'),String(b.title||''),String(b.body||''),b.due_at?Number(b.due_at):null,b.completed?1:0,now()).run();return json({ok:true,id:r.meta.last_row_id},201);}
const am=path.match(/^\/api\/crm\/activities\/(\d+)$/);if(am&&request.method==='PUT'){const b=await request.json();await env.DB.prepare('UPDATE crm_activities SET type=?,title=?,body=?,due_at=?,completed=? WHERE id=? AND tenant_id=?').bind(String(b.type||'task'),String(b.title||''),String(b.body||''),b.due_at?Number(b.due_at):null,b.completed?1:0,Number(am[1]),tid).run();return json({ok:true});}
return json({detail:'CRM route not found.'},404);}
return env.ASSETS?env.ASSETS.fetch(request):new Response('I AM Magnanimous AI Platform',{status:200});}catch(e){return json({detail:e instanceof Error?e.message:'Server error'},500)}}};
