import {currentUser} from './integrations.js';
const json=(d,s=200)=>Response.json(d,{status:s,headers:{'cache-control':'no-store'}}),now=()=>Math.floor(Date.now()/1000);
const text=(v,n=4000)=>String(v??'').trim().slice(0,n),num=v=>Number.isFinite(Number(v))?Number(v):0;
async function ensure(env){
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS magnanimous_workbooks(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)`).run();
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS magnanimous_sheets(id TEXT PRIMARY KEY,workbook_id TEXT NOT NULL,tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,name TEXT NOT NULL,position INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)`).run();
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS magnanimous_cells(sheet_id TEXT NOT NULL,tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,row_num INTEGER NOT NULL,col_num INTEGER NOT NULL,raw_value TEXT NOT NULL DEFAULT '',formula TEXT NOT NULL DEFAULT '',updated_at INTEGER NOT NULL,PRIMARY KEY(sheet_id,row_num,col_num))`).run();
 await env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_workbooks_user ON magnanimous_workbooks(tenant_id,user_id,updated_at DESC)').run();
 await env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_sheets_workbook ON magnanimous_sheets(tenant_id,user_id,workbook_id,position)').run();
}
function colIndex(s){let n=0;for(const ch of String(s).toUpperCase()){if(ch<'A'||ch>'Z')return-1;n=n*26+(ch.charCodeAt(0)-64)}return n-1}
function colName(n){let s='';for(n=Number(n)+1;n>0;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s}
function csvParse(input){const rows=[];let row=[],cell='',quoted=false;const s=String(input||'');for(let i=0;i<s.length;i++){const ch=s[i];if(quoted){if(ch==='"'&&s[i+1]==='"'){cell+='"';i++}else if(ch==='"')quoted=false;else cell+=ch}else if(ch==='"')quoted=true;else if(ch===','){row.push(cell);cell=''}else if(ch==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=ch}row.push(cell.replace(/\r$/,''));if(row.some(v=>v!==''))rows.push(row);return rows}
function csvCell(v){const s=String(v??'');return /[",\n\r]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
function arithmetic(src){const t=String(src).match(/\d+(?:\.\d+)?|[()+\-*/]/g)||[];let i=0;const factor=()=>{const x=t[i++];if(x==='-')return-factor();if(x==='('){const v=expr();if(t[i++]!==')')throw Error('formula parentheses');return v}const v=Number(x);if(!Number.isFinite(v))throw Error('formula number');return v};const term=()=>{let v=factor();while(t[i]==='*'||t[i]==='/'){const op=t[i++],r=factor();v=op==='*'?v*r:(r===0?NaN:v/r)}return v};const expr=()=>{let v=term();while(t[i]==='+'||t[i]==='-'){const op=t[i++],r=term();v=op==='+'?v+r:v-r}return v};const out=expr();if(i!==t.length||!Number.isFinite(out))throw Error('formula arithmetic');return out}
function computed(rows){const map=new Map(rows.map(r=>[r.row_num+':'+r.col_num,r])),memo=new Map(),active=new Set();const value=(row,col)=>{const key=row+':'+col;if(memo.has(key))return memo.get(key);if(active.has(key))throw Error('circular reference');active.add(key);const item=map.get(key);let out=item?.raw_value??'';if(item?.formula){let f=String(item.formula).replace(/^=/,'').toUpperCase();const atom=a=>{a=String(a).trim();const range=a.match(/^([A-Z]+)(\d+):([A-Z]+)(\d+)$/);if(range){const c1=colIndex(range[1]),r1=Number(range[2])-1,c2=colIndex(range[3]),r2=Number(range[4])-1,vals=[];for(let r=Math.min(r1,r2);r<=Math.max(r1,r2);r++)for(let c=Math.min(c1,c2);c<=Math.max(c1,c2);c++)vals.push(num(value(r,c)));return vals}const ref=a.match(/^([A-Z]+)(\d+)$/);if(ref)return num(value(Number(ref[2])-1,colIndex(ref[1])));return[num(a)]};let prev='';while(prev!==f){prev=f;f=f.replace(/(SUM|AVERAGE|MIN|MAX|COUNT)\(([^()]*)\)/g,(_,fn,args)=>{const vals=args.split(',').flatMap(atom);if(fn==='COUNT')return String(vals.length);if(!vals.length)return'0';if(fn==='SUM')return String(vals.reduce((a,b)=>a+b,0));if(fn==='AVERAGE')return String(vals.reduce((a,b)=>a+b,0)/vals.length);if(fn==='MIN')return String(Math.min(...vals));return String(Math.max(...vals))})}f=f.replace(/([A-Z]+)(\d+)/g,(_,cc,rr)=>String(num(value(Number(rr)-1,colIndex(cc)))));out=arithmetic(f)}active.delete(key);memo.set(key,out);return out};return rows.map(r=>{let v=r.raw_value;try{v=value(r.row_num,r.col_num)}catch(e){v='#ERROR'}return{row:Number(r.row_num),col:Number(r.col_num),address:colName(r.col_num)+(Number(r.row_num)+1),raw_value:r.raw_value,formula:r.formula,value:v}})}
async function workbook(env,user,id){return env.DB.prepare('SELECT * FROM magnanimous_workbooks WHERE id=? AND tenant_id=? AND user_id=?').bind(id,String(user.tenant_id),String(user.id)).first()}
async function sheet(env,user,wid,sid){return env.DB.prepare('SELECT * FROM magnanimous_sheets WHERE id=? AND workbook_id=? AND tenant_id=? AND user_id=?').bind(sid,wid,String(user.tenant_id),String(user.id)).first()}
export async function createSpreadsheetWorkbook(env,user,{name='Untitled Workbook',description=''}={}){
 await ensure(env);const tenant=String(user.tenant_id),uid=String(user.id),id=crypto.randomUUID(),sid=crypto.randomUUID(),ts=now(),safe=text(name,120)||'Untitled Workbook';
 await env.DB.batch([
  env.DB.prepare('INSERT INTO magnanimous_workbooks(id,tenant_id,user_id,name,description,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').bind(id,tenant,uid,safe,text(description,1000),ts,ts),
  env.DB.prepare('INSERT INTO magnanimous_sheets(id,workbook_id,tenant_id,user_id,name,position,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(sid,id,tenant,uid,'Sheet 1',0,ts,ts)
 ]);
 return{id,sheet_id:sid,name:safe};
}
async function snapshot(env,user,wid,sid=''){const wb=await workbook(env,user,wid);if(!wb)return null;const{results:sheets=[]}=await env.DB.prepare('SELECT * FROM magnanimous_sheets WHERE workbook_id=? AND tenant_id=? AND user_id=? ORDER BY position,id').bind(wid,String(user.tenant_id),String(user.id)).all();const selected=sheets.find(x=>x.id===sid)||sheets[0]||null;let cells=[];if(selected){const{results=[]}=await env.DB.prepare('SELECT row_num,col_num,raw_value,formula FROM magnanimous_cells WHERE sheet_id=? AND tenant_id=? AND user_id=? ORDER BY row_num,col_num').bind(selected.id,String(user.tenant_id),String(user.id)).all();cells=computed(results)}return{workbook:wb,sheets,selected_sheet:selected,cells,formula_support:['arithmetic','cell references','SUM','AVERAGE','MIN','MAX','COUNT'],limits:{rows:1000,columns:100,cells_per_write:1000,csv_cells:10000}}}
export async function handleSpreadsheets(request,env){const u=new URL(request.url),path=u.pathname;if(!path.startsWith('/api/spreadsheets'))return null;const user=await currentUser(request,env);if(!user)return json({detail:'Sign in to use Spreadsheet Studio.'},401);await ensure(env);const tenant=String(user.tenant_id),uid=String(user.id);
 if(path==='/api/spreadsheets'&&request.method==='GET'){const{results=[]}=await env.DB.prepare('SELECT * FROM magnanimous_workbooks WHERE tenant_id=? AND user_id=? ORDER BY updated_at DESC LIMIT 100').bind(tenant,uid).all();return json({workbooks:results,count:results.length})}
 if(path==='/api/spreadsheets'&&request.method==='POST'){const b=await request.json().catch(()=>({})),made=await createSpreadsheetWorkbook(env,user,{name:b.name,description:b.description});return json(await snapshot(env,user,made.id,made.sheet_id),201)}
 const m=path.match(/^\/api\/spreadsheets\/([^/]+)$/);if(m){const id=m[1];if(request.method==='GET'){const d=await snapshot(env,user,id,u.searchParams.get('sheet_id')||'');return d?json(d):json({detail:'Workbook not found.'},404)}if(request.method==='PATCH'){const wb=await workbook(env,user,id);if(!wb)return json({detail:'Workbook not found.'},404);const b=await request.json().catch(()=>({}));await env.DB.prepare('UPDATE magnanimous_workbooks SET name=?,description=?,updated_at=? WHERE id=? AND tenant_id=? AND user_id=?').bind(text(b.name??wb.name,120)||wb.name,text(b.description??wb.description,1000),now(),id,tenant,uid).run();return json(await snapshot(env,user,id))}}
 const sheets=path.match(/^\/api\/spreadsheets\/([^/]+)\/sheets$/);if(sheets&&request.method==='POST'){const wid=sheets[1],wb=await workbook(env,user,wid);if(!wb)return json({detail:'Workbook not found.'},404);const b=await request.json().catch(()=>({})),id=crypto.randomUUID(),ts=now(),count=await env.DB.prepare('SELECT COUNT(*) count FROM magnanimous_sheets WHERE workbook_id=? AND tenant_id=? AND user_id=?').bind(wid,tenant,uid).first();await env.DB.prepare('INSERT INTO magnanimous_sheets(id,workbook_id,tenant_id,user_id,name,position,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(id,wid,tenant,uid,text(b.name||'Sheet '+(Number(count?.count||0)+1),80),Number(count?.count||0),ts,ts).run();return json(await snapshot(env,user,wid,id),201)}
 const cells=path.match(/^\/api\/spreadsheets\/([^/]+)\/sheets\/([^/]+)\/cells$/);if(cells&&request.method==='PUT'){const[_,wid,sid]=cells,wb=await workbook(env,user,wid),sh=await sheet(env,user,wid,sid);if(!wb||!sh)return json({detail:'Workbook or sheet not found.'},404);const b=await request.json().catch(()=>({})),items=Array.isArray(b.cells)?b.cells:[];if(!items.length||items.length>1000)return json({detail:'Provide 1–1000 cells per save.'},400);const ts=now(),stmts=[];for(const item of items){const row=Math.floor(Number(item.row)),col=Math.floor(Number(item.col));if(row<0||row>=1000||col<0||col>=100)continue;let raw=text(item.value,12000),formula=text(item.formula,12000);if(!formula&&raw.startsWith('=')){formula=raw;raw=''}stmts.push(env.DB.prepare('INSERT INTO magnanimous_cells(sheet_id,tenant_id,user_id,row_num,col_num,raw_value,formula,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(sheet_id,row_num,col_num) DO UPDATE SET raw_value=excluded.raw_value,formula=excluded.formula,updated_at=excluded.updated_at').bind(sid,tenant,uid,row,col,raw,formula,ts))}for(let i=0;i<stmts.length;i+=100)await env.DB.batch(stmts.slice(i,i+100));await env.DB.prepare('UPDATE magnanimous_workbooks SET updated_at=? WHERE id=? AND tenant_id=? AND user_id=?').bind(ts,wid,tenant,uid).run();return json(await snapshot(env,user,wid,sid))}
 const imp=path.match(/^\/api\/spreadsheets\/([^/]+)\/sheets\/([^/]+)\/import-csv$/);if(imp&&request.method==='POST'){const[_,wid,sid]=imp,wb=await workbook(env,user,wid),sh=await sheet(env,user,wid,sid);if(!wb||!sh)return json({detail:'Workbook or sheet not found.'},404);const b=await request.json().catch(()=>({})),rows=csvParse(String(b.csv||''));const total=rows.reduce((n,r)=>n+r.length,0);if(total>10000||rows.length>1000||rows.some(r=>r.length>100))return json({detail:'CSV exceeds the 1,000-row, 100-column, or 10,000-cell import limit.'},413);await env.DB.prepare('DELETE FROM magnanimous_cells WHERE sheet_id=? AND tenant_id=? AND user_id=?').bind(sid,tenant,uid).run();const ts=now(),stmts=[];rows.forEach((r,ri)=>r.forEach((v,ci)=>stmts.push(env.DB.prepare('INSERT INTO magnanimous_cells(sheet_id,tenant_id,user_id,row_num,col_num,raw_value,formula,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(sid,tenant,uid,ri,ci,String(v).startsWith('=')?'':text(v,12000),String(v).startsWith('=')?text(v,12000):'',ts))));for(let i=0;i<stmts.length;i+=100)await env.DB.batch(stmts.slice(i,i+100));return json(await snapshot(env,user,wid,sid))}
 const exp=path.match(/^\/api\/spreadsheets\/([^/]+)\/sheets\/([^/]+)\/export-csv$/);if(exp&&request.method==='GET'){const[_,wid,sid]=exp,wb=await workbook(env,user,wid),sh=await sheet(env,user,wid,sid);if(!wb||!sh)return json({detail:'Workbook or sheet not found.'},404);const{results=[]}=await env.DB.prepare('SELECT row_num,col_num,raw_value,formula FROM magnanimous_cells WHERE sheet_id=? AND tenant_id=? AND user_id=?').bind(sid,tenant,uid).all(),vals=computed(results),maxR=Math.max(0,...vals.map(x=>x.row)),maxC=Math.max(0,...vals.map(x=>x.col)),map=new Map(vals.map(x=>[x.row+':'+x.col,x.value]));let out='';for(let r=0;r<=maxR;r++){const row=[];for(let c=0;c<=maxC;c++)row.push(csvCell(map.get(r+':'+c)??''));out+=row.join(',')+'\n'}return new Response(out,{status:200,headers:{'content-type':'text/csv; charset=utf-8','content-disposition':'attachment; filename="'+String(sh.name).replace(/[^a-z0-9_-]+/gi,'-')+'.csv"','cache-control':'no-store'}})}
 return json({detail:'Spreadsheet endpoint not found.'},404)}
