'use client';
import {useEffect,useState} from 'react';
import {getPlatformAuthToken} from '../../lib/magnanimous-session';
const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
type Overview={identity:string;activation:string;capabilities:{id:string;name:string}[];metrics:{open_cases:number;quotes:number;campaigns:number;territories:number};customer_health:Record<string,number>;predictive_readiness:{contacts:number;labeled_outcomes:number;won:number;lost:number;minimum_recommended:number;ready:boolean;reason:string}};
export default function AdvancedCRM(){
 const [data,setData]=useState<Overview|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const token=getPlatformAuthToken();if(!token){setError('Sign in to use CRM Advanced.');return}const r=await fetch(`${api}/api/operations/crm/advanced`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok){setError(j.detail||'Unable to load advanced CRM.');return}setData(j)}
 async function recalc(){const token=getPlatformAuthToken();if(!token)return;setBusy(true);setError('');try{const r=await fetch(`${api}/api/operations/crm/customer-health/recalculate`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:'{}'});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.detail||'Health calculation failed.')}await load()}catch(e:any){setError(e?.message||'Health calculation failed.')}finally{setBusy(false)}}
 useEffect(()=>{load()},[]);
 return <main className="wrap"><header><div><small>MAGNANIMOUS CRM</small><h1>Depth Activation Center</h1><p>Revenue, service, attribution, customer health and outreach governance in one owned CRM layer.</p></div><a href="/crm">← CRM Command Center</a></header>
 {error&&<div className="error">{error}</div>}
 {!data?<section className="card">Loading advanced CRM…</section>:<>
 <section className="grid">
  <Metric label="Open service cases" value={data.metrics.open_cases}/><Metric label="Quotes" value={data.metrics.quotes}/><Metric label="Campaigns" value={data.metrics.campaigns}/><Metric label="Territories" value={data.metrics.territories}/>
 </section>
 <section className="card"><div className="row"><div><small>CUSTOMER HEALTH</small><h2>Relationship risk engine</h2><p>Recalculate engagement, open-case, commercial-value and consent signals without pretending they are a trained churn model.</p></div><button disabled={busy} onClick={recalc}>{busy?'CALCULATING…':'RECALCULATE HEALTH'}</button></div><div className="health"><b>Healthy {data.customer_health.healthy||0}</b><b>Watch {data.customer_health.watch||0}</b><b>At risk {data.customer_health.at_risk||0}</b></div></section>
 <section className="card"><small>PREDICTIVE MODEL READINESS</small><h2>{data.predictive_readiness.ready?'Training data threshold reached':'Collect real outcomes first'}</h2><p>{data.predictive_readiness.reason}</p><div className="health"><b>{data.predictive_readiness.labeled_outcomes} labeled outcomes</b><b>{data.predictive_readiness.won} won</b><b>{data.predictive_readiness.lost} lost</b><b>Target {data.predictive_readiness.minimum_recommended}+</b></div></section>
 <section className="card"><small>ACTIVATED CAPABILITIES</small><h2>Advanced CRM operating layer</h2><div className="caps">{data.capabilities.map(x=><article key={x.id}><b>{x.name}</b><span>{x.id}</span></article>)}</div></section>
 <section className="card"><small>SAFE OUTREACH</small><h2>Communication windows are now CRM-native</h2><p>Sequence planning can honor the contact timezone, weekday/hour windows and existing channel consent/DNC state. The planner does not silently bypass permission gates or auto-send messages.</p></section>
 </>}
 <style jsx>{`
 .wrap{min-height:100vh;background:#07111d;color:#eef7ff;padding:28px;font-family:Arial,sans-serif}header,.row{display:flex;justify-content:space-between;gap:20px;align-items:center;max-width:1200px;margin:0 auto 24px}header h1{font-size:38px;margin:6px 0}header p,.card p{color:#a9bfd0;max-width:760px;line-height:1.6}a,button{background:#16d9c4;color:#031411;border:0;border-radius:12px;padding:12px 16px;font-weight:800;text-decoration:none;cursor:pointer}.grid,.card{max-width:1200px;margin:0 auto 18px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.metric,.card{background:#0d1d2b;border:1px solid #1f3b4e;border-radius:18px;padding:20px}.metric span,.card small{color:#7f9db3;font-size:11px;font-weight:900;letter-spacing:1.4px}.metric strong{display:block;font-size:32px;margin-top:8px}.health{display:flex;gap:12px;flex-wrap:wrap;margin-top:14px}.health b{background:#102b3b;padding:10px 12px;border-radius:10px}.caps{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.caps article{padding:16px;border:1px solid #214357;border-radius:14px;background:#091722}.caps b,.caps span{display:block}.caps span{color:#6e91a9;margin-top:6px;font-size:12px}.error{max-width:1200px;margin:0 auto 18px;background:#4a1820;padding:14px;border-radius:12px}@media(max-width:760px){.wrap{padding:18px}.grid,.caps{grid-template-columns:1fr 1fr}header,.row{align-items:flex-start;flex-direction:column}header h1{font-size:30px}}@media(max-width:480px){.grid,.caps{grid-template-columns:1fr}}
 `}</style></main>
}
function Metric({label,value}:{label:string;value:number}){return <div className="metric"><span>{label.toUpperCase()}</span><strong>{value}</strong></div>}
