'use client';
import {useEffect,useMemo,useState} from 'react';
import {getPlatformAuthToken} from '../lib/magnanimous-session';

const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
async function read(r:Response){const t=await r.text();try{return JSON.parse(t)}catch{return{detail:t||`Request failed (${r.status})`}}}

export default function ReservationsPage(){
 const[token,setToken]=useState(''),[data,setData]=useState<any>(null),[error,setError]=useState(''),[provider,setProvider]=useState(''),[product,setProduct]=useState('air'),[action,setAction]=useState('reserve'),[preflight,setPreflight]=useState<any>(null),[busy,setBusy]=useState(false),[family,setFamily]=useState('all');
 useEffect(()=>{const t=getPlatformAuthToken();if(!t){location.href='/login';return}setToken(t)},[]);
 async function get(path:string){const r=await fetch(`${api}${path}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'}),d=await read(r);if(!r.ok)throw new Error(d.detail||'Request failed.');return d}
 useEffect(()=>{if(!token)return;get('/api/b2b/reservations').then(setData).catch(e=>setError(e.message))},[token]);
 async function runPreflight(){setBusy(true);setError('');try{const r=await fetch(`${api}/api/b2b/reservations/preflight`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({provider,product,action})}),d=await read(r);if(!r.ok)throw new Error(d.detail||'Preflight failed.');setPreflight(d.preflight)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const families=useMemo(()=>[...new Set((data?.providers||[]).map((x:any)=>x.family))].sort(),[data]);
 const providers=(data?.providers||[]).filter((x:any)=>family==='all'||x.family===family);
 return <main className="page">
  <header><div><small>MAGNANIMOUS RESERVATION SERVICE</small><h1>Search → Reserve → Fulfill → Service</h1><p>Magnanimous owns the reservation record, routing, policy, audit trail and servicing history. Airlines, GDS/NDC rails, bedbanks, marketplaces, payment systems and settlement networks remain replaceable authorized providers.</p></div><nav><a href="/b2b">B2B Network</a><a href="/business-ai">Business AI</a><a href="/connections">Connections</a></nav></header>
  {error&&<div className="error">{error}</div>}
  <section className="stats">
   <article><small>PROVIDER GRAPH</small><b>{data?.summary?.providers||0}</b></article>
   <article><small>RESERVATION SKILLS</small><b>{data?.summary?.skills||0}</b></article>
   <article><small>CAPABILITY CONTRACTS</small><b>{data?.summary?.capabilities||0}</b></article>
   <article><small>LIFECYCLE STAGES</small><b>{data?.summary?.lifecycle_stages||0}</b></article>
   <article><small>NORMALIZED OBJECTS</small><b>{data?.summary?.normalized_objects||0}</b></article>
  </section>
  <section className="grid">
   <article className="panel"><small>TRANSACTION PREFLIGHT</small><h2>Check the path before Magnanimous acts</h2><div className="fields"><select value={product} onChange={e=>setProduct(e.target.value)}><option>air</option><option>hotel</option><option>car</option><option>transfer</option><option>activities</option><option>rail</option><option>cruise</option></select><select value={provider} onChange={e=>setProvider(e.target.value)}><option value="">Choose provider</option>{(data?.providers||[]).map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={action} onChange={e=>setAction(e.target.value)}>{['search','revalidate','hold','reserve','ticket','change','cancel','refund','settle'].map(x=><option key={x}>{x}</option>)}</select></div><button onClick={runPreflight} disabled={busy}>{busy?'Checking…':'Run reservation preflight'}</button>{preflight&&<div className="preflight"><b>{preflight.consequential?'CONSEQUENTIAL ACTION':'READ / PLANNING ACTION'}</b><p>{preflight.rule}</p>{(preflight.missing||[]).map((x:string)=><span key={x}>Missing: {x}</span>)}</div>}</article>
   <article className="panel"><small>SAFETY RULE</small><h2>Credentials do not equal authority</h2><p>A connected API key may allow search while still lacking booking, ticketing, refund, void or settlement rights. Magnanimous revalidates price and availability, checks the exact action authority, and reconciles ambiguous responses before retrying.</p></article>
  </section>
  <section className="panel lifecycle"><small>RESERVATION LIFECYCLE</small><h2>One Magnanimous record across outside rails</h2><div className="steps">{(data?.lifecycle||[]).map((x:any,i:number)=><article key={x.id}><span>{i+1}</span><div><b>{x.name}</b><p>{x.purpose}</p><em>{x.risk}</em></div></article>)}</div></section>
  <section className="panel providers"><div className="head"><div><small>PROVIDER CONNECTION GRAPH</small><h2>Inventory, booking, fulfillment, payment and settlement roles</h2></div><select value={family} onChange={e=>setFamily(e.target.value)}><option value="all">All families</option>{families.map((x:any)=><option key={x} value={x}>{x}</option>)}</select></div><p className="muted">Public supplier relationships are recorded when documented. Private commercial partner lists are never invented.</p><div className="cards">{providers.map((p:any)=><article key={p.id}><b>{p.name}</b><span>{p.family}</span><p><strong>Roles:</strong> {p.connection_role.join(', ')}</p><p><strong>Products:</strong> {p.products.join(', ')}</p><p><strong>Upstream:</strong> {p.upstream.join('; ')}</p><p><strong>Downstream:</strong> {p.downstream.join('; ')}</p><p><strong>Authority:</strong> {p.authority}</p></article>)}</div></section>
  <section className="panel skills"><small>RESERVATION SKILL LIBRARY</small><h2>Reusable skills inside the Magnanimous brain</h2><div className="skillgrid">{(data?.skills||[]).map((s:any)=><article key={s.id}><b>{s.id.replaceAll('-',' ')}</b><span>{s.category}</span><p>{s.description}</p></article>)}</div></section>
  <style jsx>{`
   .page{min-height:100vh;background:#05090d;color:#edf7fa;font-family:Inter,system-ui,sans-serif;padding:28px}header{max-width:1320px;margin:auto;display:flex;justify-content:space-between;gap:24px;align-items:end;padding:30px 0}header small,.panel small{color:#63e9b0;font-weight:900;letter-spacing:.14em}h1{font-size:clamp(38px,5vw,68px);margin:6px 0}header p,.muted,.panel>p{color:#93a9b3;line-height:1.6;max-width:880px}nav{display:flex;gap:8px;flex-wrap:wrap}a{color:#d8edf4;text-decoration:none;border:1px solid #29404b;padding:10px;border-radius:9px}.stats{max-width:1320px;margin:auto;display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.stats article,.panel{border:1px solid #203a46;background:#081118;border-radius:16px;padding:18px}.stats small{display:block;color:#62e7b0;font-size:9px;letter-spacing:.12em}.stats b{display:block;font-size:30px;margin-top:8px}.grid{max-width:1320px;margin:14px auto;display:grid;grid-template-columns:1fr 1fr;gap:14px}.panel{max-width:1284px;margin:14px auto}.panel h2{margin:6px 0 12px}.fields{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px}select,button{box-sizing:border-box;width:100%;padding:11px;border:1px solid #2a4652;border-radius:10px;background:#07151d;color:#eef9fc}button{margin-top:8px;background:#12462f;border-color:#2c845c;color:#c9ffe5;font-weight:900;cursor:pointer}.preflight{margin-top:12px;border-top:1px solid #20333c;padding-top:10px}.preflight span{display:block;color:#e6a66a;font-size:12px;margin:4px 0}.steps{display:grid;grid-template-columns:1fr 1fr;gap:8px}.steps article{display:flex;gap:10px;border:1px solid #263943;border-radius:11px;padding:10px;background:#071018}.steps>article>span{min-width:26px;height:26px;border-radius:50%;display:grid;place-items:center;background:#123929;color:#80e8b4;font-weight:900}.steps b,.steps em{display:block}.steps p,.cards p,.skillgrid p{color:#91a5ae;font-size:11px;line-height:1.5}.steps em{font-style:normal;color:#d9a15d;font-size:9px;text-transform:uppercase}.head{display:flex;justify-content:space-between;gap:16px;align-items:end}.head select{max-width:280px}.cards,.skillgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.cards article,.skillgrid article{border:1px solid #263943;border-radius:11px;padding:11px;background:#071018}.cards b,.cards span,.skillgrid b,.skillgrid span{display:block}.cards span,.skillgrid span{color:#70d9ad;font-size:10px;margin-top:3px}.skillgrid b{text-transform:capitalize}.error{max-width:1320px;margin:0 auto 12px;border:1px solid #793b49;background:#2b1018;padding:12px;border-radius:10px}@media(max-width:1050px){.stats{grid-template-columns:repeat(3,1fr)}.cards,.skillgrid{grid-template-columns:1fr 1fr}}@media(max-width:720px){.page{padding:16px}header{display:block}.stats,.grid,.cards,.skillgrid,.steps,.fields{grid-template-columns:1fr}.head{display:block}.head select{max-width:none;margin-top:10px}}
  `}</style>
 </main>
}
