export type InteractionResource={label:string;url:string;note:string};
export type InteractionTopic={key:string;title:string;summary:string;whatHappens:string;internal:string[];keywords:string[];resources:InteractionResource[]};

export const interactionTopics:InteractionTopic[]=[
 {key:'start',title:'Start & navigation',summary:'Find the right workspace without needing to understand the platform architecture first.',whatHappens:'Navigation links move you to a real workspace. Use the Start Here and Solutions areas when you are unsure which tool fits the goal.',internal:['/start','/solutions','/','/free-tools','/ai-apps'],keywords:['start','dashboard','home','solutions','open','workspace','platform','menu','navigate'],resources:[{label:'SBA Business Guide',url:'https://www.sba.gov/business-guide',note:'Official U.S. small-business guide covering planning, launch, management and growth.'}]},
 {key:'magnanimous',title:'MAGNANIMOUS AI & agents',summary:'Use MAGNANIMOUS or a specialist agent to plan, write, research, organize and reason through work.',whatHappens:'AI buttons prepare or run an AI request. Review generated material before sending, publishing, filing or relying on it for consequential decisions.',internal:['/ai-chat','/agents','/ai-apps','/virtual-assistant','/free-tools'],keywords:['ai','magnanimous','agent','assistant','helper','operator','chat','brain','prompt','generate','research helper','writing helper'],resources:[{label:'NIST AI Risk Management Framework',url:'https://www.nist.gov/itl/ai-risk-management-framework',note:'Official NIST framework for understanding and managing AI risks and trustworthy use.'},{label:'NIST Generative AI Profile',url:'https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence',note:'NIST guidance focused specifically on generative-AI risks and controls.'}]},
 {key:'business-plan',title:'Business planning & LaunchPlan',summary:'Build, challenge and adapt a business case for lenders, investors, grants, partners, expansion or internal planning.',whatHappens:'The free intake creates a planning draft. Professional finalization runs deeper review and audience adaptation. Funding, approval and business success are never guaranteed.',internal:['/launchplan','/business-plan','/business','/professional'],keywords:['business plan','launchplan','startup','founder','lender','investor','grant','expansion','partnership','funding','loan','immigration'],resources:[{label:'SBA Business Guide',url:'https://www.sba.gov/business-guide',note:'Official planning and business-startup guidance.'},{label:'SBA Funding Programs',url:'https://www.sba.gov/funding-programs',note:'Official overview of SBA loans, investment capital, disaster assistance and related funding programs.'},{label:'Grants.gov',url:'https://www.grants.gov/search-grants',note:'Official U.S. federal grant opportunity search.'},{label:'SAM.gov Contract Opportunities',url:'https://sam.gov/opportunities',note:'Official federal procurement opportunity search.'},{label:'USCIS Entrepreneur Resources',url:'https://www.uscis.gov/working-in-the-united-states/entrepreneur-employment-pathways',note:'Official U.S. immigration information for entrepreneur employment pathways; eligibility depends on individual facts.'}]},
 {key:'business',title:'Business command & operations',summary:'Turn ideas into practical strategy, offers, market research, sales plans and operating priorities.',whatHappens:'Business workflow buttons select a planning mode or run a business analysis. Results are decision support, not professional legal, accounting or financing approval.',internal:['/business','/professional','/business-plan','/knowledge','/crm'],keywords:['business','growth','offer','market','strategy','sales','customer strategy','operations','professional'],resources:[{label:'SBA Manage Your Business',url:'https://www.sba.gov/business-guide/manage-your-business',note:'Official guidance for operating and growing a small business.'},{label:'SCORE',url:'https://www.score.org/',note:'Nonprofit small-business mentoring and education supported by the SBA.'}]},
 {key:'crm',title:'CRM, leads & sales follow-up',summary:'Organize contacts, leads, customers, statuses and follow-up work.',whatHappens:'CRM actions create, update, search or organize customer records in the signed-in workspace. Outreach should follow consent, marketing and privacy rules that apply to the user and recipient.',internal:['/crm','/leads','/professional','/assistant-actions','/business-email'],keywords:['crm','lead','leads','contact','customer','pipeline','sales','follow-up','deal'],resources:[{label:'FTC CAN-SPAM Compliance Guide',url:'https://www.ftc.gov/business-guidance/resources/can-spam-act-compliance-guide-business',note:'Official U.S. requirements for commercial email.'},{label:'FTC Advertising & Marketing Guidance',url:'https://www.ftc.gov/business-guidance/advertising-marketing',note:'Official U.S. business guidance for advertising and marketing practices.'}]},
 {key:'email',title:'Business email & connected outreach',summary:'Connect supported email accounts, prepare messages and perform authorized email work.',whatHappens:'Email actions may draft, read or send through a connected account when the account is authorized and the action is supported. Sending should be intentional and compliant with applicable commercial-email rules.',internal:['/business-email','/assistant-actions?focus=email','/connections','/professional'],keywords:['email','inbox','message','send','draft','gmail','outlook','mail','outreach'],resources:[{label:'FTC CAN-SPAM Compliance Guide',url:'https://www.ftc.gov/business-guidance/resources/can-spam-act-compliance-guide-business',note:'Official U.S. commercial-email compliance guidance.'}]},
 {key:'calling',title:'Phone, call center & AI receptionist',summary:'Use browser calling, carrier calling, AI reception, scripts, QA and call-center workflows.',whatHappens:'Calling controls can prepare or place calls only when the required carrier connection and permissions are present. AI-assisted calls should disclose automation where required and honor consent and do-not-call obligations.',internal:['/phone','/ai-receptionist','/call-center-health','/crm','/agents'],keywords:['phone','call','calling','dial','carrier','receptionist','call center','voice','twilio','number'],resources:[{label:'FCC Robocalls & Robotexts',url:'https://www.fcc.gov/consumers/guides/stop-unwanted-robocalls-and-texts',note:'Official FCC consumer and compliance context for automated calls and texts.'},{label:'FTC National Do Not Call Registry',url:'https://www.donotcall.gov/',note:'Official U.S. Do Not Call resource.'}]},
 {key:'video',title:'Video & creator media',summary:'Create scripts, visuals, video outputs and creator workflows while keeping source rights and claims in mind.',whatHappens:'Creator controls can generate, render, review or route media work. Users remain responsible for rights to source material, likeness permissions, advertising claims and final publication.',internal:['/video-studio','/agent-video','/social-media','/ai-apps'],keywords:['video','studio','media','creator','image','render','cinematic','avatar','script','mux'],resources:[{label:'U.S. Copyright Office — What Is Copyright?',url:'https://www.copyright.gov/what-is-copyright/',note:'Official copyright basics and ownership information.'},{label:'FTC Advertising & Marketing Guidance',url:'https://www.ftc.gov/business-guidance/advertising-marketing',note:'Official advertising guidance for claims and promotions.'}]},
 {key:'social',title:'Social media & marketing',summary:'Plan campaigns, create posts and move content into social and marketing workflows.',whatHappens:'Social controls create or prepare content. Connected-account publishing, where supported, should happen only after authorization and review.',internal:['/social-media','/assistant-actions','/connections','/video-studio','/business'],keywords:['social','facebook','instagram','tiktok','youtube','linkedin','marketing','campaign','post','content','promotion'],resources:[{label:'FTC Endorsements, Influencers & Reviews',url:'https://www.ftc.gov/business-guidance/advertising-marketing/endorsements-influencers-reviews',note:'Official guidance on endorsements, influencers, testimonials and reviews.'},{label:'FTC Advertising & Marketing Guidance',url:'https://www.ftc.gov/business-guidance/advertising-marketing',note:'Official advertising and marketing compliance guidance.'}]},
 {key:'connections',title:'Connections & integrations',summary:'Authorize optional outside services so platform workflows can use supported account capabilities.',whatHappens:'Connection buttons start or manage an authorization flow. Connecting a service does not transfer ownership of that service to I Am Magnanimous Way™; the outside provider keeps its own terms and controls.',internal:['/connections','/owner-integrations','/security','/privacy'],keywords:['connect','connection','integration','authorize','account','provider','oauth','settings'],resources:[{label:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Official NIST cybersecurity risk-management framework.'}]},
 {key:'knowledge',title:'Knowledge, research & sources',summary:'Search current information, save useful sources and maintain private workspace knowledge.',whatHappens:'Research controls can search configured sources and save selected findings. Source links should open the original material so users can verify claims rather than relying only on a generated summary.',internal:['/knowledge','/ai-chat?mode=Research','/business','/professional'],keywords:['knowledge','research','source','memory','learn','news','web','feed','rss','search'],resources:[{label:'NIST Information Resources',url:'https://www.nist.gov/',note:'Official standards and technology reference source.'},{label:'USA.gov',url:'https://www.usa.gov/',note:'Official U.S. government information directory for finding primary public-sector sources.'}]},
 {key:'finance-people',title:'Finance & people operations',summary:'Organize business finance, staffing and people-related operating information.',whatHappens:'Finance and people controls support internal records and planning. Tax, payroll, employment and accounting obligations vary by jurisdiction and should be verified with the appropriate authority or professional.',internal:['/finance-people','/professional','/business','/business-plan'],keywords:['finance','people','employee','staff','payroll','expense','revenue','budget','cash','accounting','tax'],resources:[{label:'IRS Small Business and Self-Employed',url:'https://www.irs.gov/businesses/small-businesses-self-employed',note:'Official U.S. federal tax resources for small businesses and self-employed people.'},{label:'U.S. Department of Labor',url:'https://www.dol.gov/general/topic/wages',note:'Official U.S. wage and workplace information; requirements vary by location and worker classification.'}]},
 {key:'billing',title:'Pricing, payments & subscriptions',summary:'Understand free access, paid plans, recurring billing, payment status and subscription management.',whatHappens:'Payment buttons open secure Stripe-hosted checkout or subscription management. Recurring plans continue according to the disclosed billing interval until canceled, subject to payment success and Stripe/account settings.',internal:['/pricing','/billing-support','/owner-billing','/business-plan'],keywords:['pricing','price','payment','billing','stripe','subscribe','subscription','monthly','cancel','manage plan','upgrade'],resources:[{label:'FTC Consumer Advice — Subscriptions',url:'https://consumer.ftc.gov/articles/getting-and-out-subscriptions',note:'Official U.S. consumer guidance on recurring subscriptions and cancellation.'}]},
 {key:'security',title:'Security, privacy & trust',summary:'Understand workspace isolation, provider boundaries, data handling, permissions and account controls.',whatHappens:'Security and privacy links explain what the platform controls, what connected providers control, and what users should review before authorizing outside services or sensitive actions.',internal:['/security','/privacy','/terms','/connections','/support'],keywords:['security','privacy','data','trust','permission','credential','terms','legal','policy'],resources:[{label:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Official cybersecurity risk-management framework.'},{label:'FTC Privacy & Security Guidance',url:'https://www.ftc.gov/business-guidance/privacy-security',note:'Official U.S. business privacy and data-security guidance.'}]},
 {key:'support',title:'Support, reviews & feedback',summary:'Get help, report issues, leave feedback and understand how public reviews are handled.',whatHappens:'Support controls create or manage support requests. Review controls submit user feedback for moderation before public display; moderation should not be represented as independent verification of every claim.',internal:['/support','/reviews','/security','/pricing'],keywords:['support','help','feedback','review','rating','ticket','issue','report'],resources:[{label:'FTC Endorsements, Influencers & Reviews',url:'https://www.ftc.gov/business-guidance/advertising-marketing/endorsements-influencers-reviews',note:'Official guidance relevant to testimonials and review practices.'}]},
 {key:'advertising',title:'Advertising & monetization',summary:'Understand sponsored placements, advertiser responsibilities and revenue-related platform controls.',whatHappens:'Advertising actions open the disclosed sponsorship or advertiser flow. Sponsored placement is separate from AI answers and does not guarantee traffic, sales or return on ad spend.',internal:['/advertise','/pricing','/owner-billing','/solutions'],keywords:['advertise','advertising','ad','sponsored','revenue','monetization','promotion'],resources:[{label:'FTC Advertising & Marketing Guidance',url:'https://www.ftc.gov/business-guidance/advertising-marketing',note:'Official U.S. rules and guidance for truthful advertising and marketing.'}]},
 {key:'owner',title:'Owner administration',summary:'Manage protected platform-level settings, users, integrations, billing, reviews and operational health.',whatHappens:'Owner controls are restricted administration actions. They should remain separate from normal customer workspaces and may change platform configuration or review protected records.',internal:['/owner-center','/owner-integrations','/owner-leads','/owner-billing','/owner-feedback','/owner-reviews'],keywords:['owner','admin','administration','platform settings','registered users','owner center'],resources:[{label:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Useful reference for access control, governance and operational security practices.'}]}
];

const routeTopic:Record<string,string>={
 '/':'start','/start':'start','/solutions':'start','/free-tools':'magnanimous','/ai-apps':'magnanimous','/ai-chat':'magnanimous','/agents':'magnanimous','/virtual-assistant':'magnanimous',
 '/business-plan':'business-plan','/launchplan':'business-plan','/business':'business','/professional':'business','/crm':'crm','/leads':'crm','/business-email':'email','/assistant-actions':'email',
 '/phone':'calling','/ai-receptionist':'calling','/call-center-health':'calling','/video-studio':'video','/agent-video':'video','/mux':'video','/social-media':'social','/connections':'connections',
 '/knowledge':'knowledge','/finance-people':'finance-people','/pricing':'billing','/billing-support':'billing','/owner-billing':'billing','/security':'security','/privacy':'security','/terms':'security',
 '/support':'support','/reviews':'support','/advertise':'advertising','/owner-center':'owner','/owner-integrations':'owner','/owner-leads':'owner','/owner-feedback':'owner','/owner-reviews':'owner','/owner-login':'owner'
};

export function topicByKey(key?:string|null){return interactionTopics.find(t=>t.key===key)||interactionTopics[0]}
export function topicFor(pathname:string,text=''){
 const clean=(pathname||'/').replace(/\/+$/,'')||'/';
 const routed=routeTopic[clean];
 if(routed)return topicByKey(routed);
 const hay=String(text||'').toLowerCase();
 let best=interactionTopics[0],score=0;
 for(const topic of interactionTopics){let s=0;for(const keyword of topic.keywords)if(hay.includes(keyword.toLowerCase()))s+=keyword.length>8?3:1;if(s>score){score=s;best=topic}}
 return best;
}
export function guideHref(topicKey:string,sourcePath='',label=''){
 const p=new URLSearchParams();p.set('topic',topicKey);if(sourcePath)p.set('source',sourcePath);if(label)p.set('label',label.slice(0,180));return `/guide?${p.toString()}`;
}
