import React from 'react';

export default function RootLayout({children}:{children:React.ReactNode}){
  return <html lang="en"><body>{children}<script dangerouslySetInnerHTML={{__html:`(function(){
var ready=false,overlay=null;
function make(){
 var p=location.pathname;
 if(ready||p==='/login'||p==='/signup'||p==='/owner-login')return;
 if(localStorage.getItem('iam_account_token')||localStorage.getItem('odin_admin_token')){ready=true;return;}
 if(document.getElementById('iam-entry-gate'))return;
 overlay=document.createElement('div');overlay.id='iam-entry-gate';
 overlay.innerHTML='<div class="iam-gate-bg"><div class="iam-gate-grid"></div><div class="iam-gate-orb">✦</div></div><div class="iam-gate-card"><div class="iam-gate-logo">✦</div><div class="iam-gate-kicker">I AM MAGNANIMOUS WAY™</div><h1>Welcome to I AM</h1><p id="iam-gate-copy">Create your free account or sign in to enter the platform.</p><div id="iam-gate-fields"><input id="iam-gate-name" placeholder="Your name" autocomplete="name"><input id="iam-gate-workspace" placeholder="Workspace name" autocomplete="organization"><input id="iam-gate-email" type="email" placeholder="Email address" autocomplete="email"><input id="iam-gate-password" type="password" placeholder="Password" autocomplete="current-password"></div><button id="iam-gate-submit">Create Free Account</button><button id="iam-gate-switch" class="iam-gate-link">Already have an account? Sign in</button><button id="iam-gate-owner" class="iam-gate-owner">OWNER / ADMIN LOGIN →</button><div id="iam-gate-error"></div><small>Customer accounts and owner administration are kept separate.</small></div>';
 var s=document.createElement('style');s.textContent='#iam-entry-gate{position:fixed;inset:0;z-index:2147483647;background:#050812;color:#fff;font-family:Inter,system-ui,sans-serif;display:flex;align-items:center;justify-content:center;overflow:hidden}.iam-gate-bg{position:absolute;inset:0;background:radial-gradient(circle at 50% 45%,rgba(0,210,255,.18),transparent 32%),linear-gradient(135deg,#03050b,#071522 55%,#03050b)}.iam-gate-grid{position:absolute;inset:-20%;opacity:.2;background-image:linear-gradient(rgba(80,220,255,.15) 1px,transparent 1px),linear-gradient(90deg,rgba(80,220,255,.15) 1px,transparent 1px);background-size:45px 45px;transform:perspective(500px) rotateX(55deg);animation:iamgrid 12s linear infinite}.iam-gate-orb{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);font-size:180px;color:#7be8ff;opacity:.12;text-shadow:0 0 80px #00d9ff;animation:iamorb 4s ease-in-out infinite}@keyframes iamgrid{to{transform:perspective(500px) rotateX(55deg) translateY(45px)}}@keyframes iamorb{50%{transform:translate(-50%,-50%) scale(1.08);opacity:.2}}.iam-gate-card{position:relative;width:min(440px,calc(100% - 32px));padding:34px;border:1px solid rgba(123,232,255,.35);border-radius:24px;background:rgba(7,14,25,.88);box-shadow:0 25px 100px rgba(0,0,0,.6),0 0 50px rgba(0,210,255,.12);backdrop-filter:blur(18px);text-align:center}.iam-gate-logo{font-size:38px;color:#7be8ff;text-shadow:0 0 25px #00d9ff}.iam-gate-kicker{font-size:11px;letter-spacing:3px;color:#7be8ff;margin:8px 0}.iam-gate-card h1{margin:8px 0;font-size:32px}.iam-gate-card p{color:#b8c8d8;margin:0 0 22px}.iam-gate-card input{box-sizing:border-box;width:100%;margin:6px 0;padding:13px 14px;border-radius:12px;border:1px solid #294255;background:#0b1622;color:#fff;outline:none}.iam-gate-card input:focus{border-color:#69ddff;box-shadow:0 0 0 2px rgba(105,221,255,.12)}#iam-gate-submit{width:100%;margin-top:10px;padding:14px;border:0;border-radius:12px;background:linear-gradient(90deg,#00b9e8,#7b61ff);color:#fff;font-weight:800;cursor:pointer}.iam-gate-link,.iam-gate-owner{display:block;width:100%;margin:14px 0 4px;background:none;border:0;cursor:pointer}.iam-gate-link{color:#7be8ff}.iam-gate-owner{margin-top:14px;padding:14px;border:1px solid rgba(185,199,255,.45);border-radius:12px;color:#d8dfff;font-weight:900;letter-spacing:.08em;background:rgba(105,92,255,.10);box-shadow:0 0 22px rgba(123,97,255,.12)}.iam-gate-owner:hover{box-shadow:0 0 30px rgba(123,97,255,.28);border-color:#b9c7ff}.iam-gate-card small{display:block;color:#718396;margin-top:14px}.iam-gate-card #iam-gate-error{min-height:20px;color:#ff8d9d;font-size:13px;margin-top:8px}';document.head.appendChild(s);document.body.appendChild(overlay);
 var signup=true,submit=document.getElementById('iam-gate-submit'),sw=document.getElementById('iam-gate-switch'),owner=document.getElementById('iam-gate-owner'),copy=document.getElementById('iam-gate-copy');
 function mode(){document.getElementById('iam-gate-name').style.display=signup?'block':'none';document.getElementById('iam-gate-workspace').style.display=signup?'block':'none';submit.textContent=signup?'Create Free Account':'Sign In';sw.textContent=signup?'Already have an account? Sign in':'Need an account? Create one';copy.textContent=signup?'Create your free account or sign in to enter the platform.':'Sign in with your I AM account to enter the platform.';}
 sw.onclick=function(){signup=!signup;document.getElementById('iam-gate-error').textContent='';mode()};
 owner.onclick=function(){location.href='/owner-login'};
 submit.onclick=async function(){var error=document.getElementById('iam-gate-error');error.textContent='';submit.disabled=true;submit.textContent='Working…';try{var email=document.getElementById('iam-gate-email').value.trim(),password=document.getElementById('iam-gate-password').value,name=document.getElementById('iam-gate-name').value.trim(),workspace=document.getElementById('iam-gate-workspace').value.trim();if(!email||!password||(signup&&!name))throw new Error('Please complete the required fields.');var endpoint='/api/auth/'+(signup?'signup':'login');var r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name,email:email,password:password,workspace:workspace||name})});var text=await r.text(),d;try{d=JSON.parse(text)}catch(e){throw new Error('The account service returned an invalid response. Please try again.')}if(!r.ok||!d.token)throw new Error(d.detail||'Unable to continue');localStorage.setItem('iam_account_token',d.token);var verify=await fetch('/api/auth/me',{headers:{Authorization:'Bearer '+d.token}});if(!verify.ok)throw new Error('Your account was created, but the session could not be verified. Please sign in again.');ready=true;overlay.remove();location.replace('/')}catch(e){error.textContent=e.message||'Unable to continue'}finally{submit.disabled=false;mode()}};
 mode();
}
window.addEventListener('load',make);setTimeout(make,250);
})();`}} /><script dangerouslySetInnerHTML={{__html:`(function(){var routes={'AI Chat':'/ai-chat','AI Apps':'/ai-apps','Video Studio':'/video-studio','Free Tools':'/free-tools','CRM':'/crm'};document.addEventListener('click',function(e){var el=e.target&&e.target.closest?e.target.closest('button'):null;if(!el)return;var label=(el.textContent||'').trim();if(routes[label]){e.preventDefault();e.stopImmediatePropagation();location.href=routes[label]}},true)})();`}} /></body></html>
}
