'use client';
import {useEffect,useMemo,useState} from 'react';

const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
type Capability={id:string;name:string;mode:string};
type Connection={configured:boolean;configured_fields:number;required_fields:number};
type Adapter={id:string;name:string;state:string;live_via:string;docs:string;capabilities:Capability[];connection:Connection;notes?:string[]};
type RegistrarData={adapters?:Adapter[];billable_execution_enabled?:boolean};

async function read(r:Response){const text=await r.text();try{return JSON.parse(text)}catch{return{detail:text||`HTTP ${r.status}`}}}

export default function OwnerRegistrars(){
 const[data,setData]=useState<RegistrarData>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[domain,setDomain]=useState(''),[result,setResult]=useState<any>(null);
 const token=useMemo(()=>typeof window==='undefined'?'':localStorage.getItem('magnanimous_admin_token')||localStorage.getItem('odin_admin_token')||localStorage.getItem('iam_account_token')||'',[]);
 async function call(path:string,init?:RequestInit){const r=await fetch(`${api}${path}`,{...init,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(init?.headers||{})},cache:'no-store'});const d=await read(r);if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);return d;}
 async function load(){setBusy(true);setError('');try{setData(await call('/api/magnanimous/registrar/adapters'))}catch(e:any){setError(e.message||String(e))}finally{setBusy(false)}}
 useEffect(()=>{load()},[]);
 async function search(){if(!query.trim())return;setBusy(true);setError('');try{setResult(await call(`/api/magnanimous/registrar/cloudflare/search?q=${encodeURIComponent(query.trim())}&limit=10`))}catch(e:any){setError(e.message||String(e))}finally{setBusy(false)}}
 async function check(){if(!domain.trim())return;setBusy(true);setError('');try{setResult(await call('/api/magnanimous/registrar/cloudflare/check',{method:'POST',body:JSON.stringify({domains:[domain.trim()]})}))}catch(e:any){setError(e.message||String(e))}finally{setBusy(false)}}
 async function porkbunPortfolio(){setBusy(true);setError('');try{setResult(await call('/api/magnanimous/registrar/porkbun/domains'))}catch(e:any){setError(e.message||String(e))}finally{setBusy(false)}}
 return <main className="page">
  <header><div><small>OWNER CONTROL • REGISTRARS</small><h1>Magnanimous Registrar Control Plane</h1><p>One Magnanimous-owned layer for registrar research, account inspection and guarded domain operations.</p></div><a href="/owner-dns">← DNS & Domain Control</a></header>
  <section className="notice"><b>Paid actions remain locked.</b> Domain registration, renewal, transfer, restoration and other chargeable registrar actions are not executed from this console. Live reads use only connected owner credentials.</section>
  {error&&<section className="error">{error}</section>}
  <section className="live"><article><h2>Live Cloudflare Registrar research</h2><div className="row"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search idea, e.g. magnanimous ai"/><button disabled={busy} onClick={search}>Search domains</button></div><div className="row"><input value={domain} onChange={e=>setDomain(e.target.value)} placeholder="Check domain, e.g. example.com"/><button disabled={busy} onClick={check}>Authoritative check</button></div></article><article><h2>Live Porkbun portfolio</h2><p>Uses the existing encrypted registrar connection and hardened DNS runtime.</p><button disabled={busy} onClick={porkbunPortfolio}>Read domain portfolio</button></article></section>
  {result&&<section className="result"><div><h2>Live result</h2><button onClick={()=>setResult(null)}>Clear</button></div><pre>{JSON.stringify(result,null,2)}</pre></section>}
  <section><div className="title"><h2>Absorbed registrar adapters</h2><button disabled={busy} onClick={load}>{busy?'Checking…':'Refresh'}</button></div><div className="grid">{(data.adapters||[]).map(a=><article key={a.id}><div className="head"><h3>{a.name}</h3><span className={a.connection?.configured?'on':'off'}>{a.connection?.configured?'CONNECTED':a.state.toUpperCase()}</span></div><p><b>Runtime:</b> {a.live_via}</p><p><b>Connection:</b> {a.connection?.configured_fields||0}/{a.connection?.required_fields||0} required server-side fields configured</p><div className="caps">{a.capabilities.map(c=><span key={c.id} className={c.mode}>{c.name}{c.mode==='spend'?' • paid':''}</span>)}</div>{a.notes?.map(n=><small key={n}>{n}</small>)}</article>)}</div></section>
  <footer>Magnanimous AI remains the identity, reasoning, memory and authorization layer. Registrars remain replaceable infrastructure.</footer>
  <style jsx>{`
   *{box-sizing:border-box}.page{min-height:100vh;background:#031128;color:#edfaff;font-family:Inter,system-ui,sans-serif;padding:28px;max-width:1500px;margin:auto}header{display:flex;justify-content:space-between;gap:24px;align-items:flex-start;border-bottom:1px solid #205b83;padding-bottom:20px}header small{color:#68e7ff;letter-spacing:.15em;font-weight:800}h1{margin:6px 0 8px;font-size:36px}p{color:#b8d5e5;line-height:1.55}a{color:#79eaff;text-decoration:none}.notice,.error,.result,.live article,.grid article{border:1px solid #1d688e;background:#071c38;border-radius:12px;padding:16px}.notice{margin:20px 0;border-color:#b18a38}.error{margin:14px 0;border-color:#b85d62;color:#ffd6d6}.live{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:22px}.row{display:flex;gap:8px;margin-top:8px}input{flex:1;background:#031126;border:1px solid #286c92;border-radius:8px;padding:11px;color:#fff}button{background:#123a59;border:1px solid #51d8ff;color:#eefdff;border-radius:8px;padding:10px 13px;font-weight:800;cursor:pointer}button:disabled{opacity:.5}.title,.head,.result>div{display:flex;align-items:center;justify-content:space-between;gap:12px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.grid h3{margin:0}.head span{font-size:10px;font-weight:900;letter-spacing:.08em;padding:5px 8px;border-radius:20px}.head .on{background:#103f2d;color:#70f2ac}.head .off{background:#352f20;color:#eacb7b}.caps{display:flex;flex-wrap:wrap;gap:6px;margin:12px 0}.caps span{font-size:10px;border:1px solid #2a5e7d;border-radius:20px;padding:5px 8px;color:#bfeaff}.caps .write{border-color:#a6783e;color:#f1ca8f}.caps .spend{border-color:#a64f58;color:#ffabb2}.grid small{display:block;color:#9bb8c7;margin-top:6px}.result{margin-bottom:22px}.result pre{white-space:pre-wrap;word-break:break-word;max-height:520px;overflow:auto;background:#020c1b;padding:12px;border-radius:8px;color:#bdeaff}footer{margin-top:26px;color:#7ea6bb;font-size:12px}@media(max-width:850px){.live,.grid{grid-template-columns:1fr}header{display:grid}.row{display:grid}}
  `}</style>
 </main>
}
