'use client';
import {useEffect,useState} from 'react';
const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
const tok=()=>typeof window==='undefined'?'':(localStorage.getItem('iam_account_token')||localStorage.getItem('magnanimous_admin_token')||localStorage.getItem('odin_admin_token')||'');
async function call(path:string,init:RequestInit={}){const headers:any={'content-type':'application/json',...(init.headers||{})};const t=tok();if(t)headers.Authorization=`Bearer ${t}`;const r=await fetch(`${api}${path}`,{...init,headers});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.detail||`Request failed (${r.status})`);return x}
export default function ToolFoundry(){const[data,setData]=useState<any>({gaps:[],tools:[]}),[need,setNeed]=useState(''),[name,setName]=useState(''),[purpose,setPurpose]=useState(''),[msg,setMsg]=useState('');const load=()=>call('/api/magnanimous/tool-foundry').then(setData).catch(e=>setMsg(e.message));useEffect(()=>{load()},[]);const post=async(path:string,body:any)=>{try{const r=await call(path,{method:'POST',body:JSON.stringify(body)});setMsg(JSON.stringify(r));await load()}catch(e:any){setMsg(e.message)}};
 return <main><header><div><small>MAGNANIMOUS AI • NATIVE TOOL CREATION</small><h1>Tool Foundry</h1><p>Teach Magnanimous recurring capability gaps, turn them into reusable native tool specifications, and learn from outcomes.</p></div><a href="/">← Dashboard</a></header>
 <section className="hero"><h2>Connectors are tools. Magnanimous is the brain.</h2><p>The Foundry records what Magnanimous repeatedly needs, proposes reusable tools after repeated gaps, tracks success, and keeps external authorization boundaries intact.</p></section>
 <section className="grid"><article><h3>Teach a missing capability</h3><textarea value={need} onChange={e=>setNeed(e.target.value)} placeholder="Example: reconcile customer subscriptions against carrier usage automatically"/><button onClick={()=>post('/api/magnanimous/tool-foundry/observe',{capability:need,example_task:need})} disabled={!need.trim()}>Record Capability Gap</button><p className="hint">Repeated needs are automatically promoted into tool proposals.</p></article><article><h3>Create a native tool specification</h3><input value={name} onChange={e=>setName(e.target.value)} placeholder="Tool name"/><textarea value={purpose} onChange={e=>setPurpose(e.target.value)} placeholder="What should this tool accomplish?"/><button onClick={()=>post('/api/magnanimous/tool-foundry/spec',{name,purpose,family:'native',risk:'low'})} disabled={!purpose.trim()}>Create Tool Spec</button></article></section>
 <section className="panel"><h2>Learned capability gaps</h2><div className="cards">{data.gaps?.map((g:any)=><div key={g.capability}><b>{g.capability}</b><span>{g.count} observations • {g.status}</span><p>{g.example_task}</p></div>)}</div></section>
 <section className="panel"><h2>Magnanimous native tool library</h2><div className="cards">{data.tools?.map((t:any)=><div key={t.id}><b>{t.name}</b><span>{t.status} • risk {t.risk} • {t.successes}/{t.uses} successes</span><p>{t.purpose}</p>{t.status!=='ready'&&t.risk!=='high'&&<button onClick={()=>post('/api/magnanimous/tool-foundry/promote',{name:t.name})}>Promote to Ready</button>}</div>)}</div></section>{msg&&<pre>{msg}</pre>}<footer>Magnanimous can create and learn reusable tool recipes and connector specifications. External accounts still require authorization, and high-impact tools remain review-gated.</footer>
 <style jsx>{`*{box-sizing:border-box}main{min-height:100vh;background:#07101b;color:#eef8ff;font-family:Inter,system-ui;padding:32px;max-width:1400px;margin:auto}header{display:flex;justify-content:space-between;gap:20px}header small{color:#7cecff;letter-spacing:.18em;font-weight:800}h1{font-size:clamp(38px,6vw,72px);margin:5px 0}p{color:#9bb0c2}a{color:#8cefff;text-decoration:none}.hero,.panel,article{border:1px solid #24415b;background:#0b1827;border-radius:18px;padding:22px}.hero{margin:24px 0;background:linear-gradient(120deg,#0d2942,#231734)}.hero h2{font-size:32px;margin:0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.panel{margin-top:16px}input,textarea{width:100%;padding:12px;border-radius:10px;border:1px solid #294760;background:#06101c;color:#fff;margin:6px 0}textarea{min-height:105px}button{border:0;border-radius:10px;padding:10px 14px;background:linear-gradient(90deg,#75eaff,#c282ff);font-weight:900;color:#06101c;cursor:pointer}.hint,footer{font-size:12px;color:#7e93a7}.cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.cards>div{background:#07121f;border:1px solid #1d3850;border-radius:12px;padding:13px}.cards b,.cards span{display:block}.cards span{font-size:11px;color:#7ce7ff;margin-top:4px}pre{white-space:pre-wrap;background:#04090f;padding:12px;border-radius:10px;margin-top:14px}footer{margin-top:18px}@media(max-width:800px){main{padding:18px}.grid,.cards{grid-template-columns:1fr}header{display:block}}`}</style></main>}
