'use client';
import {useEffect,useState} from 'react';
const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
async function readResponse(r:Response){const text=await r.text();try{return JSON.parse(text)}catch{return{detail:text.startsWith('<')?`The server returned an HTML page instead of Odin's API (${r.status}).`:text||`Request failed (${r.status})`}}}
export default function AIChat(){
 const [message,setMessage]=useState(''),[output,setOutput]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState('CHECKING'),[provider,setProvider]=useState('');
 useEffect(()=>{fetch(`${api}/api/odin/health`).then(async r=>({r,d:await readResponse(r)})).then(({r,d})=>{if(r.ok&&d.workers_ai_bound){setStatus('ODIN ONLINE');setProvider('Cloudflare Workers AI')}else if(r.ok){const p=(d.providers||[]).find((x:any)=>x.configured&&x.enabled);setStatus(p?'ODIN ONLINE':'ODIN NEEDS PROVIDER');setProvider(p?.id||'')}else setStatus('ODIN OFFLINE')}).catch(()=>setStatus('ODIN OFFLINE'))},[]);
 async function ask(){if(!message.trim()||busy)return;setBusy(true);setOutput('Odin is thinking…');try{const r=await fetch(`${api}/api/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,provider:'auto'})});const d=await readResponse(r);if(!r.ok)throw new Error(d.detail||`Odin request failed (${r.status})`);setProvider(d.provider_name||d.provider||provider);setStatus('ODIN ONLINE');setOutput(d.output||'Odin returned an empty response.')}catch(e:any){setStatus('ODIN ERROR');setOutput(e?.message||'Unable to reach the AI service.')}finally{setBusy(false)}}
 return <main className="module-page"><header className="module-header"><a href="/">← Back to I AM Magnanimous</a><span className="module-status">● {status}</span></header><section className="module-hero"><div className="module-icon">◉</div><div><span className="eyebrow">INTELLIGENCE CORE</span><h1>AI Chat</h1><p>Talk directly with Odin and turn ideas into practical work.</p>{provider&&<small>Active provider: {provider}</small>}</div></section><section className="module-grid"><div className="module-panel large"><div className="panel-title"><span>ODIN CONSOLE</span><b>{busy?'THINKING':status.replace('ODIN ','')}</b></div><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Ask Odin anything…"/><button onClick={ask} disabled={busy}>{busy?'Odin is working…':'Send to Odin →'}</button>{output&&<div className="module-output">{output}</div>}</div><div className="module-panel visual"><div className="pulse-ring">✦</div><h3>Agent Core</h3><p>Reasoning • Planning • Creation • Automation</p><div className="signal"><i/><i/><i/><i/><i/><i/></div></div></section></main>
}
