-- Magnanimous CRM depth activation: service, CPQ, attribution, territories, health and safe communication planning.
-- Make the migration self-contained: this table previously existed only in runtime schema bootstrapping.
CREATE TABLE IF NOT EXISTS crm_contact_preferences (id INTEGER PRIMARY KEY AUTOINCREMENT,tenant_id TEXT NOT NULL,contact_id INTEGER NOT NULL,email_status TEXT NOT NULL DEFAULT 'unknown',sms_status TEXT NOT NULL DEFAULT 'unknown',phone_status TEXT NOT NULL DEFAULT 'unknown',whatsapp_status TEXT NOT NULL DEFAULT 'unknown',do_not_contact INTEGER NOT NULL DEFAULT 0,lawful_basis TEXT NOT NULL DEFAULT '',consent_source TEXT NOT NULL DEFAULT '',consent_note TEXT NOT NULL DEFAULT '',updated_at INTEGER NOT NULL,UNIQUE(tenant_id,contact_id));
CREATE TABLE IF NOT EXISTS crm_cases(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,contact_id INTEGER,account_id INTEGER,subject TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',priority TEXT NOT NULL DEFAULT 'normal',channel TEXT NOT NULL DEFAULT '',owner_user_id TEXT NOT NULL DEFAULT '',sla_due_at INTEGER,resolved_at INTEGER,description TEXT NOT NULL DEFAULT '',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS crm_quotes(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,deal_id INTEGER,contact_id INTEGER,account_id INTEGER,quote_number TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'draft',currency TEXT NOT NULL DEFAULT 'USD',subtotal REAL NOT NULL DEFAULT 0,discount REAL NOT NULL DEFAULT 0,tax REAL NOT NULL DEFAULT 0,total REAL NOT NULL DEFAULT 0,valid_until INTEGER,approval_status TEXT NOT NULL DEFAULT 'not_required',notes TEXT NOT NULL DEFAULT '',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,UNIQUE(tenant_id,quote_number));
CREATE TABLE IF NOT EXISTS crm_quote_items(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,quote_id TEXT NOT NULL,name TEXT NOT NULL,sku TEXT NOT NULL DEFAULT '',quantity REAL NOT NULL DEFAULT 1,unit_price REAL NOT NULL DEFAULT 0,discount REAL NOT NULL DEFAULT 0,total REAL NOT NULL DEFAULT 0,metadata_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS crm_campaigns(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,name TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',channel TEXT NOT NULL DEFAULT '',budget REAL NOT NULL DEFAULT 0,start_at INTEGER,end_at INTEGER,utm_source TEXT NOT NULL DEFAULT '',utm_medium TEXT NOT NULL DEFAULT '',utm_campaign TEXT NOT NULL DEFAULT '',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS crm_campaign_touches(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,campaign_id TEXT NOT NULL,contact_id INTEGER NOT NULL,deal_id INTEGER,touch_type TEXT NOT NULL DEFAULT 'engagement',occurred_at INTEGER NOT NULL,value REAL NOT NULL DEFAULT 0,metadata_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS crm_territories(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,name TEXT NOT NULL,owner_user_id TEXT NOT NULL DEFAULT '',criteria_json TEXT NOT NULL DEFAULT '{}',quota REAL NOT NULL DEFAULT 0,period_start INTEGER,period_end INTEGER,active INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS crm_health_snapshots(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,contact_id INTEGER NOT NULL,health_score REAL NOT NULL DEFAULT 0,risk_level TEXT NOT NULL DEFAULT 'unknown',signals_json TEXT NOT NULL DEFAULT '[]',calculated_at INTEGER NOT NULL);
ALTER TABLE crm_contact_preferences ADD COLUMN local_timezone TEXT NOT NULL DEFAULT '';
ALTER TABLE crm_contact_preferences ADD COLUMN quiet_hours_json TEXT NOT NULL DEFAULT '{}';
CREATE INDEX IF NOT EXISTS idx_crm_cases_tenant_status ON crm_cases(tenant_id,status,priority);
CREATE INDEX IF NOT EXISTS idx_crm_quotes_tenant_deal ON crm_quotes(tenant_id,deal_id,status);
CREATE INDEX IF NOT EXISTS idx_crm_quote_items_quote ON crm_quote_items(tenant_id,quote_id);
CREATE INDEX IF NOT EXISTS idx_crm_campaign_touches_contact ON crm_campaign_touches(tenant_id,contact_id,occurred_at);
CREATE INDEX IF NOT EXISTS idx_crm_territories_tenant ON crm_territories(tenant_id,active);
CREATE INDEX IF NOT EXISTS idx_crm_health_contact ON crm_health_snapshots(tenant_id,contact_id,calculated_at);
