"use client";
import {useEffect,useState} from "react";
const modes=[["Song","song"],["Instrumental","instrumental"],["Sound / Loop","sound"],["Remix / Extend","remix"],["Advanced Studio","studio"]] as const;
function token(){return localStorage.getItem("iam_token")||localStorage.getItem("token")||""}
export default function MusicStudio(){
 const [mode,setMode]=useState("song"),[title,setTitle]=useState(""),[idea,setIdea]=useState(""),[lyrics,setLyrics]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[engine,setEngine]=useState(false),[projects,setProjects]=useState<any[]>([]);
 async function call(path:string,init:RequestInit={}){const h:any={"content-type":"application/json",...(init.headers||{})};const t=token();if(t)h.authorization="Bearer "+t;const r=await fetch(path,{...init,headers:h});const d=await r.json().catch(()=>({detail:"Invalid server response"}));if(!r.ok&&r.status!==202)throw new Error(d.detail||"Request failed");return d}
 async function refresh(){try{const c=await call("/api/music/capabilities");setEngine(Boolean(c.engines?.audioGeneration));const p=await call("/api/music/projects");setProjects(p.projects||[])}catch{}}
 useEffect(()=>{refresh()},[]);
 async function prepare(e:any){e.preventDefault();if(!idea.trim()&&!lyrics.trim()){setNotice("Describe what you want to create or add lyrics first.");return}setBusy(true);try{const p=await call("/api/music/projects",{method:"POST",body:JSON.stringify({title:title||"Untitled Music Project",mode,creative_brief:idea,lyrics,rights_status:"original"})});const op=mode==="sound"?"sounds":mode==="remix"?"remix":"generate";const g=await call("/api/music/"+op,{method:"POST",body:JSON.stringify({project_id:p.project.id,source_rights:"original"})});setNotice(g.status==="queued"?"Music project saved and generation queued.":"Project saved. The audio engine is not configured yet, so no charge was made and no fake audio was returned.");await refresh()}catch(err:any){setNotice(err.message||"Could not save the project.")}finally{setBusy(false)}}
 return <main className="page"><header><a href="/">← Dashboard</a><small>I AM MAGNANIMOUS WAY™ · MAGNANIMOUS AI</small><h1>Music Studio</h1><p>Create and manage music projects with Magnanimous as the brain.</p><div className={engine?"status on":"status"}>{engine?"● Audio engine connected":"○ Audio engine awaiting configuration"}</div></header>
 <section className="modes">{modes.map(([label,id])=><button key={id} type="button" onClick={()=>setMode(id)} className={mode===id?"active":""}><b>{label}</b></button>)}</section>
 <section className="grid"><form onSubmit={prepare}><label>Project title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="My new song"/></label><label>Describe the music<textarea rows={6} value={idea} onChange={e=>setIdea(e.target.value)} placeholder="Genre, mood, instruments, tempo, structure, message, vocal direction…"/></label><label>Lyrics / words<textarea rows={9} value={lyrics} onChange={e=>setLyrics(e.target.value)} placeholder="Write lyrics or describe what the lyrics should communicate."/></label><button className="primary" disabled={busy}>{busy?"Saving…":"Create Music Project →"}</button>{notice&&<div className="notice">{notice}</div>}</form>
 <aside><h2>Your projects</h2>{projects.length?projects.slice(0,8).map(p=><div className="project" key={p.id}><b>{p.title}</b><span>{p.mode}</span></div>):<p>No saved music projects yet.</p>}<h3>Protected by design</h3><p>Projects are account/tenant scoped. Remix and source-audio operations require rights confirmation; voice profiles require consent.</p><a href="/video-studio">Video Studio →</a></aside></section>
 <style jsx>{`.page{min-height:100vh;background:#060810;color:#f4f7ff;padding:28px;font-family:Inter,system-ui}header,.modes,.grid{max-width:1200px;margin:auto}a{color:#7ce8d1;text-decoration:none}header small{display:block;margin-top:22px;color:#7ce8d1;letter-spacing:.18em;font-size:10px}h1{font-size:clamp(48px,8vw,88px);margin:6px 0;line-height:.95}header p,aside p{color:#9ca9bc;line-height:1.6}.status{display:inline-block;border:1px solid #5a3d3d;padding:7px 10px;border-radius:99px;font-size:11px}.status.on{border-color:#376a5d;color:#7ce8d1}.modes{display:grid;grid-template-columns:repeat(5,1fr);gap:9px;margin-top:22px}.modes button,form,aside{background:#0b101b;border:1px solid #26334a;border-radius:16px;color:inherit;padding:16px;text-align:left}.modes button.active{border-color:#7ce8d1}.grid{display:grid;grid-template-columns:1fr 340px;gap:12px;margin-top:12px}form label{display:grid;gap:6px;margin:12px 0;font-size:12px;font-weight:800}input,textarea{box-sizing:border-box;width:100%;background:#060a12;border:1px solid #2a3952;border-radius:11px;color:white;padding:12px}.primary{width:100%;padding:14px;border:0;border-radius:11px;background:#7ce8d1;color:#04110e;font-weight:900}.primary:disabled{opacity:.55}.notice{margin-top:12px;border:1px solid #335848;background:#091610;padding:12px;border-radius:10px;font-size:12px}.project{display:flex;justify-content:space-between;gap:8px;border-bottom:1px solid #202b3d;padding:10px 0;font-size:12px}.project span{color:#7ce8d1}@media(max-width:900px){.modes{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}}@media(max-width:520px){.page{padding:16px}.modes{grid-template-columns:1fr}}`}</style></main>
}