'use client';
import {useEffect,useState} from 'react';
const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
const token=()=>typeof window==='undefined'?'':(localStorage.getItem('iam_account_token')||localStorage.getItem('magnanimous_admin_token')||localStorage.getItem('odin_admin_token')||'');
async function call(path:string,init:RequestInit={}){const headers:any={'content-type':'application/json',...(init.headers||{})};const t=token();if(t)headers.Authorization=`Bearer ${t}`;const r=await fetch(`${api}${path}`,{...init,headers});const text=await r.text();let data:any={};try{data=JSON.parse(text)}catch{}if(!r.ok)throw new Error(data.detail||`Request failed (${r.status})`);return data}
export default function Wellness(){const[data,setData]=useState<any>(null),[goal,setGoal]=useState('Improve my overall wellness'),[habit,setHabit]=useState(''),[research,setResearch]=useState(''),[result,setResult]=useState<any>(null),[busy,setBusy]=useState('');
 const load=async()=>{try{setData(await call('/api/wellness/summary'))}catch(e:any){setResult({error:e.message})}};useEffect(()=>{load()},[]);
 const post=async(path:string,body:any,label:string)=>{setBusy(label);try{const r=await call(path,{method:'POST',body:JSON.stringify(body)});setResult(r);await load()}catch(e:any){setResult({error:e.message})}finally{setBusy('')}};
 return <main><header><div><small>MAGNANIMOUS AI • NATIVE WORKSPACE</small><h1>Wellness Command Center</h1><p>Plan, track, research, and improve everyday wellness in one private workspace.</p></div><a href="/">← Dashboard</a></header>
 <section className="hero"><div><h2>Your plan should adapt to your real life.</h2><p>Magnanimous keeps goals, habits, check-ins, plans and sourced research together so progress can be reviewed instead of guessed.</p></div><div className="badge">FREE-FIRST<br/><b>PRIVATE WORKSPACE</b></div></section>
 <section className="grid">
  <article><h3>Create a wellness plan</h3><input value={goal} onChange={e=>setGoal(e.target.value)} placeholder="What do you want to improve?"/><button onClick={()=>post('/api/wellness/plan',{goal},'plan')} disabled={!!busy}>{busy==='plan'?'Creating…':'Build My Plan'}</button>{data?.plan?.plan&&<div className="box"><b>{data.plan.title}</b>{data.plan.plan.daily?.map((x:any,i:number)=><p key={i}><strong>{x.time}:</strong> {x.action}</p>)}</div>}</article>
  <article><h3>Add a goal</h3><input value={goal} onChange={e=>setGoal(e.target.value)}/><button onClick={()=>post('/api/wellness/goals',{title:goal,category:'wellness'},'goal')}>Save Goal</button><div className="chips">{data?.goals?.map((g:any)=><span key={g.id}>{g.title}</span>)}</div></article>
  <article><h3>Build a habit</h3><input value={habit} onChange={e=>setHabit(e.target.value)} placeholder="Walk 20 minutes, drink water…"/><button onClick={()=>post('/api/wellness/habits',{title:habit,frequency:'daily'},'habit')} disabled={!habit.trim()}>Add Habit</button><div className="chips">{data?.habits?.map((h:any)=><span key={h.id}>{h.title}</span>)}</div></article>
  <article><h3>Daily check-in</h3><div className="row"><input id="mood" type="number" min="0" max="10" placeholder="Mood 0-10"/><input id="energy" type="number" min="0" max="10" placeholder="Energy 0-10"/></div><div className="row"><input id="sleep" type="number" min="0" step="0.5" placeholder="Sleep hours"/><input id="move" type="number" min="0" placeholder="Movement min"/></div><button onClick={()=>post('/api/wellness/checkins',{mood:Number((document.getElementById('mood') as HTMLInputElement)?.value||0),energy:Number((document.getElementById('energy') as HTMLInputElement)?.value||0),sleep_hours:Number((document.getElementById('sleep') as HTMLInputElement)?.value||0),movement_minutes:Number((document.getElementById('move') as HTMLInputElement)?.value||0)},'checkin')}>Save Check-in</button><small>{data?.checkins?.length||0} recent check-ins loaded</small></article>
 </section>
 <section className="research"><div><small>SOURCED WELLNESS RESEARCH</small><h2>Ask Magnanimous to research it</h2><p>Workspace knowledge is combined with live sources when your search provider is configured.</p></div><div><textarea value={research} onChange={e=>setResearch(e.target.value)} placeholder="Example: What does current evidence say about improving sleep consistency?"/><button onClick={()=>post('/api/wellness/research',{query:research,web:true,remember:true},'research')} disabled={!research.trim()}>{busy==='research'?'Researching…':'Research'}</button></div></section>
 {result&&<pre>{JSON.stringify(result,null,2)}</pre>}<footer>Educational wellness support only. Magnanimous does not diagnose or replace licensed medical care. Severe or urgent symptoms need appropriate professional or emergency care.</footer>
 <style jsx>{`*{box-sizing:border-box}main{min-height:100vh;background:#07101b;color:#edf8ff;font-family:Inter,system-ui;padding:32px;max-width:1400px;margin:auto}header{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}header small,.research small{letter-spacing:.18em;color:#7ce7ff;font-weight:800}h1{font-size:clamp(34px,5vw,64px);margin:6px 0}p{color:#9bb0c4}a{color:#8cf1ff;text-decoration:none}.hero{margin:26px 0;display:flex;justify-content:space-between;gap:30px;padding:28px;border:1px solid #25516f;border-radius:20px;background:linear-gradient(120deg,#0f2740,#15172b)}.hero h2{font-size:32px;margin:0}.badge{text-align:right;color:#88a8bd}.badge b{color:#8fffc7}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}article,.research{border:1px solid #203b55;background:#0b1827;border-radius:16px;padding:20px}h3{margin-top:0}input,textarea{width:100%;background:#07111f;border:1px solid #29445f;color:#eef9ff;padding:12px;border-radius:10px;margin:6px 0}textarea{min-height:110px;resize:vertical}button{border:0;background:linear-gradient(90deg,#6ee7ff,#bd7aff);color:#08101b;font-weight:900;padding:11px 16px;border-radius:10px;cursor:pointer;margin-top:8px}.row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.chips{display:flex;flex-wrap:wrap;gap:7px;margin-top:12px}.chips span{background:#10263b;border:1px solid #284760;border-radius:999px;padding:7px 10px;font-size:12px}.box{margin-top:12px;padding:12px;background:#07121f;border-radius:12px}.box p{font-size:13px}.research{display:grid;grid-template-columns:1fr 1fr;gap:22px;margin-top:18px}pre{white-space:pre-wrap;background:#050a11;border:1px solid #1d3348;border-radius:14px;padding:16px;overflow:auto}footer{margin-top:20px;color:#7f93a7;font-size:12px}@media(max-width:800px){main{padding:18px}.grid,.research{grid-template-columns:1fr}.hero,header{display:block}.badge{text-align:left;margin-top:18px}}`}</style></main>}
