'use client';

import {useEffect,useMemo,useState} from 'react';

type Device={id:string;name:string;hostname:string;platform:string;status:string;online:boolean;last_seen_at:number;capabilities:string[]};
type Overview={ready:boolean;policy:Record<string,unknown>;devices:Device[];pending_tasks:number;actions:Record<string,{risk:string;confirmation:boolean;family:string}>};

export default function LocalBridgePage(){
 const [token,setToken]=useState(''),[overview,setOverview]=useState<Overview|null>(null),[pairCode,setPairCode]=useState(''),[expires,setExpires]=useState(0),[notice,setNotice]=useState(''),[busy,setBusy]=useState('');
 const api='';
 const headers=(json=false)=>{const h:Record<string,string>={Authorization:`Bearer ${token}`};if(json)h['Content-Type']='application/json';return h};
 async function read(r:Response){const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||d.error||`HTTP ${r.status}`);return d}
 async function refresh(t=token){if(!t)return;try{const d=await read(await fetch(`${api}/api/magnanimous/local-bridge`,{headers:{Authorization:`Bearer ${t}`},cache:'no-store'}));setOverview(d)}catch(e:any){setNotice(e?.message||'Could not load Local Bridge status.')}}
 useEffect(()=>{const saved=localStorage.getItem('magnanimous_admin_token')||localStorage.getItem('odin_admin_token')||localStorage.getItem('iam_account_token')||'';if(!saved){location.replace('/login?returnTo=%2Flocal-bridge');return}setToken(saved);void refresh(saved)},[]);
 async function createPairing(){if(!token||busy)return;setBusy('pair');setNotice('');try{const d=await read(await fetch(`${api}/api/magnanimous/local-bridge/pairings`,{method:'POST',headers:headers(true),body:JSON.stringify({name:'My Magnanimous Computer'})}));setPairCode(d.pairing_code||'');setExpires(Number(d.expires_at||0));setNotice('One-time pairing code created. It expires in about 10 minutes.')}catch(e:any){setNotice(e?.message||'Could not create pairing code.')}finally{setBusy('')}}
 async function health(device:Device){setBusy(device.id);setNotice('');try{const d=await read(await fetch(`${api}/api/magnanimous/local-bridge/tasks`,{method:'POST',headers:headers(true),body:JSON.stringify({device_id:device.id,action:'health',payload:{}})}));setNotice(`Health check queued as ${d.id}. The bridge will return evidence when the computer polls it.`);setTimeout(()=>refresh(),1500)}catch(e:any){setNotice(e?.message||'Could not queue health check.')}finally{setBusy('')}}
 const windowsCommand=useMemo(()=>pairCode?`powershell -ExecutionPolicy Bypass -Command "$d=Join-Path $env:TEMP 'install-magnanimous-bridge.ps1'; Invoke-WebRequest 'https://raw.githubusercontent.com/IAMGodmatters/IAMMagnanimousway.js/main/local-bridge/install.ps1' -OutFile $d; & $d -PairingCode '${pairCode}' -WorkspaceRoot 'C:\\YOUR\\PROJECT'"`:'',[pairCode]);
 return <main className="page">
  <header><a href="/owner-center">← Owner Center</a><span>PRIVATE OWNER • LOCAL EXECUTION</span><a href="/god-coding">God Coding →</a></header>
  <section className="hero"><small>I AM MAGNANIMOUS WAY™ • MAGNANIMOUS AI</small><h1>Local Bridge</h1><p>Connect an authorized computer to Magnanimous through outbound HTTPS only. No inbound port, no generic remote shell, explicit workspace roots, hashed server-side tokens, and separate confirmation before source mutations.</p><div className="badges"><b>{overview?.ready?'READY LOCAL':'LOCAL BRIDGE REQUIRED'}</b><span>{overview?.devices?.filter(x=>x.online).length||0} online device(s)</span><span>{overview?.pending_tasks||0} pending task(s)</span></div></section>
  {notice&&<div className="notice" role="status">{notice}</div>}
  <section className="grid">
   <article className="card"><small>PAIR A COMPUTER</small><h2>One-time setup</h2><p>Create a pairing code, then run the Windows command on the computer you want Magnanimous to use. Replace the workspace path with the folder you authorize.</p><button onClick={createPairing} disabled={busy==='pair'}>{busy==='pair'?'CREATING…':'CREATE PAIRING CODE'}</button>{pairCode&&<div className="pair"><b>{pairCode}</b><span>expires {expires?new Date(expires*1000).toLocaleTimeString():'soon'}</span><textarea readOnly value={windowsCommand}/><p>The command downloads the bridge agent from this repository, pairs it once, and starts an outbound scheduled task. The bridge token is not shown here after pairing.</p></div>}</article>
   <article className="card"><small>SECURITY MODEL</small><h2>Capability-scoped, not remote shell</h2><ul><li>No inbound listener.</li><li>No arbitrary shell/process endpoint.</li><li>Workspace-root filesystem boundary.</li><li>Protected default branch.</li><li>Mutation tasks require separate confirmation.</li><li>Netwalk remains read-only and scope-authorized.</li></ul></article>
  </section>
  <section className="card devices"><div className="head"><div><small>PAIRED DEVICES</small><h2>Execution surfaces</h2></div><button onClick={()=>refresh()} disabled={!token}>REFRESH</button></div>{!overview?.devices?.length?<p>No paired computer yet.</p>:overview.devices.map(d=><article key={d.id}><div><b>{d.name}</b><span className={d.online?'online':'offline'}>{d.online?'ONLINE':'OFFLINE'}</span></div><p>{d.hostname} • {d.platform}</p><small>{d.capabilities.join(' • ')||'No executable capabilities advertised'}</small><div className="actions">{d.online&&d.capabilities.includes('health')&&<button onClick={()=>health(d)} disabled={busy===d.id}>{busy===d.id?'QUEUING…':'RUN HEALTH CHECK'}</button>}</div></article>)}</section>
  <style jsx>{`
   *{box-sizing:border-box}.page{min-height:100vh;background:#05080c;color:#eafaff;padding:24px 28px 70px;font-family:Inter,system-ui,sans-serif;background-image:radial-gradient(circle at 80% 0,rgba(54,210,255,.12),transparent 28%)}header,.hero,.grid,.card,.notice{max-width:1400px;margin-left:auto;margin-right:auto}header{display:flex;justify-content:space-between;font-size:9px;letter-spacing:.15em;color:#6d8994}a{color:#74dff2;text-decoration:none}.hero{margin-top:26px;padding:30px;border:1px solid #205267;border-radius:22px;background:#07141c}.hero h1{font-size:clamp(42px,7vw,76px);margin:6px 0}.hero p{max-width:950px;color:#8ca6b0;line-height:1.6}.badges{display:flex;gap:8px;flex-wrap:wrap}.badges>*{border:1px solid #24596b;border-radius:999px;padding:8px 11px;font-size:9px}.notice{margin-top:12px;padding:12px;border:1px solid #5b4927;background:#171208;border-radius:10px;color:#efd18d}.grid{display:grid;grid-template-columns:1.2fr .8fr;gap:10px;margin-top:12px}.card{margin-top:12px;padding:20px;border:1px solid #173b49;border-radius:16px;background:#071118}.grid .card{margin-top:0}.card small{color:#63d8f1;letter-spacing:.14em;font-size:9px}.card p,.card li{color:#7896a1;font-size:11px;line-height:1.55}.card button{border:1px solid #2b687b;background:#0c2c37;color:#d5f9ff;border-radius:10px;padding:10px 13px;cursor:pointer}.pair{margin-top:14px;padding:14px;border:1px solid #245365;border-radius:12px;background:#050c11}.pair b{display:block;font-family:monospace;font-size:18px;color:#a9f5ff}.pair span{font-size:9px;color:#6d8b96}.pair textarea{width:100%;min-height:120px;margin-top:12px;background:#020609;border:1px solid #163b48;color:#dffaff;border-radius:8px;padding:10px;font-family:monospace;font-size:10px}.head{display:flex;justify-content:space-between;align-items:center}.devices>article{margin-top:8px;padding:14px;border:1px solid #153844;border-radius:11px}.devices>article>div:first-child{display:flex;justify-content:space-between}.online{color:#7ef0b8}.offline{color:#dd9d78}.actions{margin-top:9px}@media(max-width:850px){.grid{grid-template-columns:1fr}.page{padding:18px 12px}}`}</style>
 </main>
}
