'use client';
import {useEffect,useMemo,useState} from 'react';
import {getPlatformAuthToken} from '../../lib/magnanimous-session';

const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
type Row=Record<string,any>;
async function read(r:Response){const t=await r.text();try{return JSON.parse(t)}catch{return{detail:t||`Request failed (${r.status})`}}}
const DEST:Record<string,string>={
 'branded-ai':'/white-label/branded-ai',crm:'/crm',inbox:'/inbox',booking:'/agency-command?tab=booking',
 funnel:'/agency-command?tab=funnels',reputation:'/agency-command?tab=reputation',automations:'/agency-automations',
 'work-engine':'/work-engine',receptionist:'/ai-receptionist','video-agents':'/video-agents',rebilling:'/agency-command?tab=billing'
};

export default function ClientApps(){
 const[token,setToken]=useState(''),[clients,setClients]=useState<Row[]>([]),[clientId,setClientId]=useState(''),[apps,setApps]=useState<Row[]>([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 const client=useMemo(()=>clients.find(x=>x.id===clientId)||null,[clients,clientId]);
 const[query,setQuery]=useState(''),[group,setGroup]=useState('all');
 useEffect(()=>{const t=getPlatformAuthToken();if(!t){location.replace('/login?returnTo=%2Fwhite-label%2Fclient-apps');return}setToken(t);(async()=>{try{
   const b=await fetch(api+'/api/billing/status',{headers:{Authorization:'Bearer '+t},cache:'no-store'}),bd=await read(b);if(!b.ok)throw Error(bd.detail||'Could not verify White Label access.');if(!['agency','agency_pro'].includes(bd.plan)){location.replace('/white-label#plans');return}
   const r=await fetch(api+'/api/agency/clients',{headers:{Authorization:'Bearer '+t},cache:'no-store'}),d=await read(r);if(!r.ok)throw Error(d.detail||'Could not load clients.');const list=d.clients||[];setClients(list);if(list[0]?.id)setClientId(list[0].id);
  }catch(e:any){setMsg(e.message)}})()},[]);
 useEffect(()=>{if(token&&clientId)load(clientId)},[token,clientId]);
 async function load(id=clientId){try{const r=await fetch(api+'/api/white-label-os/client-apps?client_id='+encodeURIComponent(id),{headers:{Authorization:'Bearer '+token},cache:'no-store'}),d=await read(r);if(!r.ok)throw Error(d.detail||'Could not load client apps.');setApps((d.apps||[]).sort((a:Row,b:Row)=>Number(a.sort_order)-Number(b.sort_order)));setMsg('')}catch(e:any){setMsg(e.message)}}
 function toggle(id:string){setApps(v=>v.map(x=>x.app_id===id?{...x,enabled:!x.enabled}:x))}
 function label(id:string,value:string){setApps(v=>v.map(x=>x.app_id===id?{...x,label:value}:x))}
 async function save(){if(!clientId)return;setBusy(true);try{const r=await fetch(api+'/api/white-label-os/client-apps?client_id='+encodeURIComponent(clientId),{method:'PUT',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({apps})}),d=await read(r);if(!r.ok)throw Error(d.detail||'Could not save client apps.');setMsg('Client app menu saved.');await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 const visible=apps.filter(x=>(group==='all'||x.group===group)&&(!query.trim()||(String(x.name)+' '+String(x.label)).toLowerCase().includes(query.toLowerCase())));const groups=Array.from(new Set(apps.map(x=>x.group||'core'))).sort();const dest=(id:string)=>id.startsWith('business-ai:')?'/business-ai?tool='+encodeURIComponent(id.slice('business-ai:'.length)):(DEST[id]||'/white-label');
 return <main className="page">
  <header><a href="/white-label">← White Label</a><b>CLIENT APPS</b><a href="/white-label-os">White Label OS →</a></header>
  <section className="hero"><small>ONE CLIENT • ONLY THE TOOLS THEY NEED</small><h1>Choose the apps this client sees.</h1><p>This controls the client app menu and package visibility inside your White Label workspace. It does not grant outside-account permissions, bypass provider requirements, or act as a security authorization boundary until a signed-in client user is mapped to that client account.</p></section>
  {msg&&<div className="msg">{msg}</div>}
  <section className="bar"><label>Client<select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">Choose client</option>{clients.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><strong>{client?.name||'No client selected'}</strong></section><section className="filters"><label htmlFor="client-app-search">Find app<input id="client-app-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search apps and AI tools"/></label><label htmlFor="client-app-group">Group<select id="client-app-group" value={group} onChange={e=>setGroup(e.target.value)}><option value="all">All</option>{groups.map((g:any)=><option key={g} value={g}>{g==='business-ai'?'Business AI':'Core apps'}</option>)}</select></label><strong>{visible.length} of {apps.length}</strong></section>
  <section className="grid">{visible.map((x,i)=><article key={x.app_id} className={x.enabled?'on':''}><div><small>{String(i+1).padStart(2,'0')}</small><h2>{x.name}</h2></div><label className="switch"><input type="checkbox" checked={!!x.enabled} onChange={()=>toggle(x.app_id)}/> {x.enabled?'Enabled':'Hidden'}</label><label>Client-facing label<input value={x.label||x.name} onChange={e=>label(x.app_id,e.target.value)}/></label><a href={dest(x.app_id)}>Open tool →</a></article>)}</section>
  <button className="save" onClick={save} disabled={busy||!clientId}>{busy?'Saving…':'Save client apps'}</button>
  <p className="fine">The app menu is tenant- and client-scoped. AI Receptionist, Video Agents, external messaging, telecom, and other provider-dependent tools still require their real permissions/configuration before they can perform those external actions.</p>
  <style jsx>{`
   *{box-sizing:border-box}.page{min-height:100vh;background:#060a10;color:#eff9ff;padding:24px 28px 80px;font-family:Inter,system-ui,sans-serif}header,.hero,.bar,.filters,.grid,.msg,.save,.fine{max-width:1250px;margin-left:auto;margin-right:auto}header{display:flex;justify-content:space-between;font-size:10px;letter-spacing:.12em}a{color:#7ae3ff;text-decoration:none}.hero{padding:52px 0 24px}.hero small{color:#d6b96e;letter-spacing:.15em;font-size:9px}.hero h1{font-size:clamp(44px,7vw,76px);line-height:.96;margin:8px 0}.hero p,.fine{color:#8ca3af;line-height:1.6}.msg{border:1px solid #335268;background:#0b1721;border-radius:10px;padding:11px}.bar{display:flex;justify-content:space-between;align-items:end;gap:14px;border:1px solid #253a48;border-radius:14px;padding:14px;background:#09121a}.filters{display:grid;grid-template-columns:1fr 260px auto;gap:10px;align-items:end;margin-top:10px}.filters label{font-size:9px;color:#7994a2}.filters input,.filters select{width:100%;display:block;margin-top:5px;border:1px solid #31505e;border-radius:9px;background:#040a0f;color:#f2faff;padding:10px}.filters strong{font-size:10px;color:#8ba6b3;padding-bottom:10px}.bar label{font-size:9px;color:#7994a2}.bar select,.grid input{display:block;margin-top:5px;border:1px solid #31505e;border-radius:9px;background:#040a0f;color:#f2faff;padding:10px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:12px}.grid article{border:1px solid #263945;border-radius:16px;background:#09121a;padding:16px;opacity:.65}.grid article.on{opacity:1;border-color:#3e7185}.grid article>div{display:flex;justify-content:space-between;gap:10px}.grid small{color:#638493}.grid h2{font-size:18px;margin:0}.grid label{display:block;font-size:9px;color:#8198a4;margin-top:12px}.grid input[type=text],.grid input:not([type]){width:100%}.switch input{width:auto;margin:0 5px 0 0;display:inline}.grid a{display:inline-block;margin-top:12px;font-size:10px;font-weight:900}.save{display:block;width:min(1250px,calc(100% - 0px));margin-top:14px;border:0;border-radius:11px;background:#72e2fa;color:#05151b;padding:13px;font-weight:950;cursor:pointer}.fine{font-size:10px;margin-top:12px}@media(max-width:900px){.grid{grid-template-columns:1fr 1fr}.filters{grid-template-columns:1fr 1fr}}@media(max-width:620px){.page{padding:18px 12px 70px}.grid{grid-template-columns:1fr}.bar{display:block}.bar strong{display:block;margin-top:10px}}`}</style>
 </main>
}