'use client';
import {useEffect,useState} from 'react';
import {getPlatformAuthToken} from '../lib/magnanimous-session';

const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
async function read(r:Response){const t=await r.text();try{return JSON.parse(t)}catch{return{detail:t||`Request failed (${r.status})`}}}
const auth=()=>({Authorization:`Bearer ${getPlatformAuthToken()}`,'Content-Type':'application/json'});
function fmt(v:any){const n=Number(v||0);return Number.isFinite(n)?Intl.NumberFormat().format(Math.round(n)):String(v||'')}

export default function CreatorGrowth(){
 const[cfg,setCfg]=useState<any>(null),[tab,setTab]=useState('ideas'),[topic,setTopic]=useState(''),[channel,setChannel]=useState(''),[video,setVideo]=useState(''),[title,setTitle]=useState(''),[comment,setComment]=useState(''),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(''),[error,setError]=useState('');
 useEffect(()=>{const t=getPlatformAuthToken();if(!t){location.replace('/login?returnTo=%2Fcreator-growth');return}fetch(`${api}/api/creator-growth/capabilities`,{headers:{Authorization:`Bearer ${t}`},cache:'no-store'}).then(read).then(setCfg).catch(()=>setError('Creator Growth could not load.'))},[]);
 async function post(path:string,body:any){setBusy(path);setError('');setResult(null);try{const r=await fetch(`${api}${path}`,{method:'POST',headers:auth(),body:JSON.stringify(body)}),d=await read(r);if(!r.ok)throw new Error(d.detail||'Request failed.');setResult(d)}catch(e:any){setError(e?.message||'Request failed.')}finally{setBusy('')}}
 async function get(path:string){setBusy(path);setError('');setResult(null);try{const r=await fetch(`${api}${path}`,{headers:{Authorization:`Bearer ${getPlatformAuthToken()}`},cache:'no-store'}),d=await read(r);if(!r.ok)throw new Error(d.detail||'Request failed.');setResult(d)}catch(e:any){setError(e?.message||'Request failed.')}finally{setBusy('')}}
 const tabs=[['ideas','Ideas & titles'],['research','Keyword research'],['outliers','Outliers'],['channel','Channel'],['video','Video'],['comments','Comments'],['analytics','Analytics'],['library','Saved & competitors']];
 return <main className="page">
  <header><a href="/social-media">← Social Studio</a><span>MAGNANIMOUS CREATOR GROWTH</span><a href="/movie-maker">Movie Maker →</a></header>
  <section className="hero"><small>YOUTUBE INTELLIGENCE • MAGNANIMOUS AI</small><h1>Research what works. Build what comes next.</h1><p>Creator Growth combines official channel/video data, Magnanimous-owned scoring, your own analytics, and history Magnanimous collects over time. It does not invent private search-volume data or pretend to own another company’s index.</p><div className="status"><b>{cfg?.public_youtube_data_ready?'PUBLIC DATA READY':'PUBLIC DATA SETUP NEEDED'}</b><b>{cfg?.owned_youtube_connected?'CHANNEL CONNECTED':'CHANNEL NOT CONNECTED'}</b><b>{cfg?.analytics_ready?'ANALYTICS READY':'ANALYTICS RECONNECT MAY BE NEEDED'}</b></div></section>
  <nav>{tabs.map(([id,label])=><button key={id} className={tab===id?'on':''} onClick={()=>{setTab(id);setResult(null);setError('')}}>{label}</button>)}</nav>
  {error&&<div className="error">{error}</div>}
  <section className="work">
   <div className="controls">
    {tab==='ideas'&&<><label>Topic<input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Example: grow a YouTube ministry channel"/></label><label>Title to score<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Paste a title"/></label><div className="buttons"><button disabled={!!busy||!title.trim()} onClick={()=>post('/api/creator-growth/title-score',{title,type:'long'})}>Score title</button><button disabled={!!busy||!topic.trim()} onClick={()=>post('/api/creator-growth/title-ideas',{topic,type:'long',count:12})}>Generate title ideas</button><button disabled={!!busy||!topic.trim()} onClick={()=>post('/api/creator-growth/thumbnail-brief',{title:title||topic,topic})}>Thumbnail brief</button><button disabled={!!busy||!topic.trim()} onClick={()=>post('/api/creator-growth/script-plan',{topic,minutes:10})}>Script plan</button></div></>}
    {tab==='research'&&<><label>Keyword/topic<input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Topic to research"/></label><div className="buttons"><button disabled={!!busy||!topic.trim()} onClick={()=>post('/api/creator-growth/keyword-research',{keyword:topic,region_code:'US'})}>Research demand</button><button disabled={!!busy||!topic.trim()} onClick={()=>post('/api/creator-growth/search',{query:topic,limit:15,order:'relevance'})}>Search videos</button><button disabled={!!busy||!topic.trim()} onClick={()=>post('/api/creator-growth/channel-search',{query:topic,limit:15})}>Search channels</button><button disabled={!!busy||!topic.trim()} onClick={()=>post('/api/creator-growth/bookmarks',{kind:'keyword',external_id:topic,title:topic,payload:{keyword:topic}})}>Save keyword</button><button disabled={!!busy} onClick={()=>get('/api/creator-growth/trending?region=US&limit=20')}>Trending now</button></div></>}
    {tab==='outliers'&&<><label>Niche or topic<input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Topic"/></label><button disabled={!!busy||!topic.trim()} onClick={()=>post('/api/creator-growth/outliers',{keyword:topic,limit:5})}>Find breakout videos</button></>}
    {tab==='channel'&&<><label>Channel ID, handle, URL — or leave blank for your connected channel<input value={channel} onChange={e=>setChannel(e.target.value)} placeholder="@channel"/></label><div className="buttons"><button disabled={!!busy} onClick={()=>post('/api/creator-growth/channel-stats',{channel})}>Channel stats</button><button disabled={!!busy} onClick={()=>post('/api/creator-growth/channel-videos',{channel,limit:25})}>Recent videos</button><button disabled={!!busy} onClick={()=>post('/api/creator-growth/similar-channels',{channel,limit:20})}>Similar channels</button><button disabled={!!busy} onClick={()=>post('/api/creator-growth/competitors',{channel})}>Track competitor</button><button disabled={!!busy} onClick={()=>post('/api/creator-growth/best-time',{channel})}>Best historical posting windows</button></div></>}
    {tab==='video'&&<><label>YouTube video ID<input value={video} onChange={e=>setVideo(e.target.value)} placeholder="Video ID"/></label><div className="buttons"><button disabled={!!busy||!video.trim()} onClick={()=>post('/api/creator-growth/video-stats',{video_id:video})}>Video stats</button><button disabled={!!busy||!video.trim()} onClick={()=>post('/api/creator-growth/similar-videos',{video_id:video,limit:20})}>Similar videos</button><button disabled={!!busy||!video.trim()} onClick={()=>get(`/api/creator-growth/change-history?video_id=${encodeURIComponent(video)}`)}>Observed title/thumbnail history</button><button disabled={!!busy||!video.trim()} onClick={()=>get(`/api/creator-growth/performance-history?video_id=${encodeURIComponent(video)}`)}>Growth history</button></div></>}
    {tab==='comments'&&<><label>Video ID<input value={video} onChange={e=>setVideo(e.target.value)} placeholder="Video ID"/></label><div className="buttons"><button disabled={!!busy||!video.trim()} onClick={()=>post('/api/creator-growth/comments',{video_id:video,limit:100})}>Load comments</button><button disabled={!!busy||!video.trim()} onClick={()=>post('/api/creator-growth/comment-insights',{video_id:video,limit:100})}>Audience insights</button></div><label>Viewer comment to answer<input value={comment} onChange={e=>setComment(e.target.value)} placeholder="Paste one comment"/></label><button disabled={!!busy||!comment.trim()} onClick={()=>post('/api/creator-growth/comment-replies',{comment,tones:['warm','helpful','concise']})}>Draft replies</button></>}
    {tab==='analytics'&&<><label>Optional video ID for retention<input value={video} onChange={e=>setVideo(e.target.value)} placeholder="Video ID"/></label><div className="buttons"><button disabled={!!busy} onClick={()=>post('/api/creator-growth/analytics',{report:'overview'})}>28-day overview</button><button disabled={!!busy} onClick={()=>post('/api/creator-growth/analytics',{report:'traffic_sources'})}>Traffic sources</button><button disabled={!!busy} onClick={()=>post('/api/creator-growth/analytics',{report:'geography'})}>Audience geography</button><button disabled={!!busy} onClick={()=>post('/api/creator-growth/analytics',{report:'top_videos'})}>Top videos</button><button disabled={!!busy||!video.trim()} onClick={()=>post('/api/creator-growth/analytics',{report:'retention',video_id:video})}>Retention curve</button></div><p className="hint">If analytics says reconnect, open Social Connections once and reconnect YouTube to grant the new read-only analytics scope.</p></>}
    {tab==='library'&&<><div className="buttons"><button disabled={!!busy} onClick={()=>get('/api/creator-growth/bookmarks?limit=50')}>Saved research</button><button disabled={!!busy} onClick={()=>get('/api/creator-growth/competitors')}>Tracked competitors</button></div><p className="hint">Saved creator research stays in your Magnanimous workspace instead of depending on an outside bookmark library.</p></>}
   </div>
   <aside><h2>Native capability map</h2><div className="caps">{(cfg?.capabilities||[]).map((c:any)=><div key={c.id}><b>{c.name}</b><span>{String(c.implementation).replaceAll('-',' ')}</span></div>)}</div></aside>
  </section>
  <section className="result"><div className="resultHead"><small>RESULT</small>{busy&&<span>WORKING…</span>}</div>{!result?<p>Choose a creator task above. Results will appear here.</p>:Array.isArray(result.titles)?<div className="cards">{result.titles.map((x:any)=><article key={x.title}><b>{x.score}</b><h3>{x.title}</h3><span>{x.length} characters</span></article>)}</div>:Array.isArray(result.videos)?<div className="cards">{result.videos.map((v:any)=><article key={v.video_id}><img src={v.thumbnail_url} alt=""/><h3>{v.title}</h3><span>{fmt(v.views)} views · {fmt(v.views_per_hour)} VPH</span>{v.breakout_score&&<b>{v.breakout_score}× breakout</b>}</article>)}</div>:<pre>{JSON.stringify(result,null,2)}</pre>}</section>
  <style jsx>{`
  *{box-sizing:border-box}.page{min-height:100vh;background:#06100e;color:#eefff8;padding:24px 30px 70px;font-family:Inter,system-ui,sans-serif;background-image:radial-gradient(circle at 12% 20%,rgba(60,255,178,.10),transparent 28%),radial-gradient(circle at 90% 45%,rgba(80,105,255,.12),transparent 30%)}header,.hero,nav,.work,.result,.error{max-width:1450px;margin-left:auto;margin-right:auto}header{display:flex;justify-content:space-between;color:#729789;font-size:9px;letter-spacing:.14em}header a{color:#aef9dc;text-decoration:none}.hero{padding:44px 0 26px}.hero small{letter-spacing:.18em;color:#5ce2aa;font-weight:900}.hero h1{font-size:clamp(42px,6vw,76px);line-height:.94;margin:10px 0;max-width:1000px}.hero p{max-width:960px;color:#8eaa9e;line-height:1.6}.status{display:flex;gap:8px;flex-wrap:wrap;margin-top:16px}.status b{font-size:8px;border:1px solid #315344;border-radius:999px;padding:7px 9px;color:#9ee8c7}nav{display:flex;gap:7px;flex-wrap:wrap;border-bottom:1px solid #1c3a2e;padding-bottom:13px}nav button{border:1px solid #25483a;background:#0a1813;color:#91b2a4;border-radius:9px;padding:9px 11px;cursor:pointer}nav button.on{background:#55e9aa;color:#062016;border-color:#55e9aa}.error{padding:12px;border:1px solid #6b3444;background:#250e17;color:#ffc1ce;border-radius:10px;margin-top:10px}.work{display:grid;grid-template-columns:1fr 360px;gap:12px;margin-top:12px}.controls,aside,.result{border:1px solid #1f4235;background:#081711;border-radius:17px;padding:18px}.controls label{display:grid;gap:6px;color:#8faf9f;font-size:10px;margin-bottom:10px}.controls input{border:1px solid #27503e;background:#06100c;color:#fff;border-radius:9px;padding:11px}.buttons{display:flex;gap:7px;flex-wrap:wrap}.controls button{border:1px solid #326148;background:#0b2218;color:#cdf9e2;border-radius:9px;padding:10px 12px;font-weight:800;cursor:pointer}.controls button:disabled{opacity:.4}.hint{font-size:9px;color:#6f8d80}.caps{display:grid;gap:7px}.caps div{border-bottom:1px solid #1b352c;padding:7px 0}.caps b,.caps span{display:block}.caps b{font-size:10px}.caps span{font-size:8px;color:#6f8f81;margin-top:3px;text-transform:uppercase}.result{margin-top:12px;min-height:260px}.resultHead{display:flex;justify-content:space-between;color:#6bdca8;font-size:9px}.result>p{color:#789789}.result pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#050c09;border-radius:10px;padding:14px;color:#bfead5}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:12px}.cards article{border:1px solid #214235;border-radius:12px;padding:12px;background:#07140f}.cards img{width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:8px}.cards h3{font-size:14px}.cards span{font-size:9px;color:#799b8c}.cards b{display:block;color:#64e7ac;margin-top:5px}@media(max-width:900px){.page{padding:18px 13px 50px}.work{grid-template-columns:1fr}.cards{grid-template-columns:1fr}header span{display:none}}
  `}</style>
 </main>
}
