'use client';

import {useEffect,useState} from 'react';
const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';

type Provider={id:string;name:string;ready:boolean;tier:string;native_audio:boolean;best_for:string};
function token(){return localStorage.getItem('magnanimous_admin_token')||localStorage.getItem('odin_admin_token')||localStorage.getItem('iam_account_token')||''}
async function read(r:Response){const t=await r.text();try{return JSON.parse(t)}catch{return{detail:t||`Request failed (${r.status})`}}}

export default function CinemaEngine(){
 const[providers,setProviders]=useState<Provider[]>([]),[provider,setProvider]=useState('auto'),[mode,setMode]=useState('cinematic'),[format,setFormat]=useState('16:9'),[title,setTitle]=useState('Magnanimous AI Motion Picture'),[transcript,setTranscript]=useState('Welcome to I AM Magnanimous Way. I am Magnanimous AI, here to help you learn, create, work, serve, grow, and make a difference.'),[direction,setDirection]=useState('Friendly white and silver Magnanimous AI robot in a cinematic neon futuristic city, expressive cyan digital face, polished motion-picture lighting, smooth natural movement, coherent character continuity.'),[status,setStatus]=useState('Ready'),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[nativeAudio,setNativeAudio]=useState(true);
 useEffect(()=>{fetch(`${api}/api/video-agents/providers?mode=cinematic`).then(read).then(d=>setProviders(d.providers||[])).catch(()=>{})},[]);
 async function start(){const auth=token();if(!auth){location.replace('/login');return}setBusy(true);setStatus('Magnanimous Auto Director is selecting the best configured engine…');setResult(null);try{const r=await fetch(`${api}/api/video-agents/generate`,{method:'POST',headers:{Authorization:`Bearer ${auth}`,'Content-Type':'application/json'},body:JSON.stringify({provider,mode,format,title,transcript,visual_direction:direction,character:'magnanimous-ai',native_audio:nativeAudio,duration:5,resolution:'720p'})});const d=await read(r);if(!r.ok)throw new Error(d.detail||'Generation could not start.');setResult(d);setStatus(d.provider==='browser'?'Free-first motion-picture route ready. Open All-in-One AI Video to render the complete browser version.':`${String(d.provider||'AI').toUpperCase()} generation started.`)}catch(e:any){setStatus(e?.message||'Generation failed.')}finally{setBusy(false)}}
 const ready=providers.filter(p=>p.ready&&p.id!=='auto');
 return <main className="wrap"><header><div><a href="/ai-video">← All-in-One AI Video</a><small>I AM MAGNANIMOUS WAY™</small><h1>Magnanimous Cinema Engine</h1><p>One director for text-to-video, agent motion, AI assistants, voice, sound, captions and written scripts. Auto mode chooses the strongest configured provider and keeps the free-first renderer as the fallback.</p></div><img src="/magnanimous-motion.svg" alt="Magnanimous AI"/></header>
 <section className="grid"><div className="panel"><label>Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Written script / transcript<textarea value={transcript} onChange={e=>setTranscript(e.target.value)}/></label><label>Visual and motion direction<textarea className="small" value={direction} onChange={e=>setDirection(e.target.value)}/></label><div className="row"><label>Provider<select value={provider} onChange={e=>setProvider(e.target.value)}>{providers.map(p=><option key={p.id} value={p.id}>{p.name}{p.id!=='auto'?(p.ready?' · READY':' · NOT CONFIGURED'):''}</option>)}</select></label><label>Mode<select value={mode} onChange={e=>setMode(e.target.value)}><option value="cinematic">Cinematic motion picture</option><option value="assistant">AI assistant / agent</option><option value="presenter">Talking presenter</option><option value="avatar">Avatar / lip-sync</option></select></label><label>Format<select value={format} onChange={e=>setFormat(e.target.value)}><option>16:9</option><option>9:16</option></select></label></div><label className="check"><input type="checkbox" checked={nativeAudio} onChange={e=>setNativeAudio(e.target.checked)}/> Prefer native generated dialogue/sound when supported</label><button disabled={busy} onClick={start}>{busy?'STARTING…':'DIRECT & GENERATE'}</button><p className="status">{status}</p>{result&&<pre>{JSON.stringify(result,null,2)}</pre>}</div>
 <div className="panel"><h2>Available engines</h2><p className="muted">Configured now: {ready.length}. Magnanimous automatically avoids unconfigured paid providers.</p><div className="providers">{providers.filter(p=>p.id!=='auto').map(p=><article key={p.id} className={p.ready?'on':'off'}><b>{p.name}</b><span>{p.ready?'READY':'OPTIONAL'}</span><p>{p.best_for}</p><small>{p.tier}{p.native_audio?' · native audio':''}</small></article>)}</div><a className="vault" href="/owner-integrations">Owner Provider Vault →</a></div></section>
 <style jsx>{`*{box-sizing:border-box}.wrap{min-height:100vh;padding:30px;background:radial-gradient(circle at 80% 8%,#173573 0,transparent 30%),#060a12;color:#eefcff;font-family:Inter,system-ui,sans-serif}header,.grid{max-width:1300px;margin:auto}header{display:grid;grid-template-columns:1.4fr .6fr;gap:28px;align-items:center}header a,.vault{color:#64eaff;text-decoration:none}header small{display:block;margin-top:18px;letter-spacing:.18em;color:#7089a7;font-weight:900}h1{font-size:clamp(42px,6vw,82px);line-height:.95;margin:10px 0;background:linear-gradient(90deg,#fff,#5cf0ff,#ef5dff);-webkit-background-clip:text;color:transparent}header p,.muted{color:#9eb0c5;line-height:1.6}header img{width:100%;border-radius:24px;border:1px solid #284a6b}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:24px}.panel{background:rgba(8,15,27,.92);border:1px solid #203b56;border-radius:20px;padding:20px}label{display:block;color:#8ea4bd;font-size:11px;text-transform:uppercase;letter-spacing:.08em;margin-bottom:13px}input,textarea,select{width:100%;margin-top:7px;padding:12px;border-radius:10px;border:1px solid #29445e;background:#0b1625;color:#fff;font:inherit;text-transform:none;letter-spacing:normal}textarea{min-height:210px;line-height:1.55}.small{min-height:90px}.row{display:grid;grid-template-columns:1.2fr 1fr .7fr;gap:9px}.check{display:flex;align-items:center;gap:8px;text-transform:none;letter-spacing:normal}.check input{width:auto;margin:0}button{width:100%;padding:15px;border:0;border-radius:11px;background:linear-gradient(90deg,#26dff5,#755dff,#ed5dff);color:#fff;font-weight:900;cursor:pointer}.status{text-align:center;color:#6fefff;font-size:12px}pre{white-space:pre-wrap;word-break:break-word;background:#06101c;border:1px solid #203b56;padding:12px;border-radius:10px;max-height:300px;overflow:auto;font-size:11px}.providers{display:grid;gap:9px}.providers article{border:1px solid #273e55;border-radius:12px;padding:13px;background:#0c1724}.providers article.on{border-color:#2a9b82}.providers b{display:block}.providers span{float:right;margin-top:-18px;font-size:9px;font-weight:900;color:#75efb8}.providers .off span{color:#8292a6}.providers p{font-size:11px;color:#9aacc0;line-height:1.45}.providers small{color:#6f849c}.vault{display:block;margin-top:16px;font-weight:800}@media(max-width:800px){header,.grid,.row{grid-template-columns:1fr}.wrap{padding:18px}header img{max-height:330px;object-fit:contain}}`}</style></main>}
