'use client';
import {useEffect,useState} from 'react';
const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
export default function Leads(){
 const[token,setToken]=useState(''),[leads,setLeads]=useState<any[]>([]),[q,setQ]=useState(''),[filter,setFilter]=useState(''),[seed,setSeed]=useState(''),[count,setCount]=useState(10),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(t=token){if(!t)return;const r=await fetch(`${api}/api/leads?q=${encodeURIComponent(q)}&filter=${encodeURIComponent(filter)}`,{headers:{Authorization:`Bearer ${t}`}});if(r.ok)setLeads((await r.json()).leads||[]);}
 useEffect(()=>{const t=localStorage.getItem('iam_account_token')||'';setToken(t);if(t)load(t)},[]);
 useEffect(()=>{if(token)load()},[q,filter]);
 async function generate(){setBusy(true);setMessage('');const r=await fetch(`${api}/api/leads/generate`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({seed,count})});const d=await r.json();setBusy(false);setMessage(r.ok?`Generated ${d.generated} leads.`:(d.detail||'Unable to generate leads.'));load()}
 return <main style={{maxWidth:1100,margin:'40px auto',padding:24,fontFamily:'system-ui'}}><p style={{opacity:.6}}>I AM MAGNANIMOUS WAY™</p><h1>Automatic Lead Generator</h1><p>Generate prospect records, score them automatically, remove duplicates, and filter hot, warm, and cold leads.</p><section style={{display:'grid',gridTemplateColumns:'2fr 1fr 120px',gap:10,margin:'24px 0'}}><input placeholder="Industry, niche, or campaign" value={seed} onChange={e=>setSeed(e.target.value)}/><input type="number" min={1} max={50} value={count} onChange={e=>setCount(Number(e.target.value))}/><button onClick={generate} disabled={busy}>{busy?'Working…':'Generate'}</button></section>{message&&<p>{message}</p>}<section style={{display:'flex',gap:10,marginBottom:18}}><input style={{flex:1}} placeholder="Search leads" value={q} onChange={e=>setQ(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All</option><option value="hot">Hot</option><option value="warm">Warm</option><option value="cold">Cold</option></select></section><div style={{display:'grid',gap:10}}>{leads.map(l=><article key={l.id} style={{border:'1px solid #ddd',borderRadius:12,padding:16}}><b>{l.first_name} {l.last_name}</b><span style={{float:'right'}}>{l.status.toUpperCase()} · {l.score}/100</span><div>{l.company}</div><small>{l.email||'No email'} · {l.phone||'No phone'} · {l.source}</small><p>{l.notes}</p></article>)}</div><p style={{marginTop:30}}><a href="/crm">Open CRM</a> · <a href="/phone">Open I AM Phone</a></p></main>;
}
