'use client';
import {useEffect,useState} from 'react';

const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
type Asset={id:string;status:string;duration?:number;created_at?:string;playback_ids?:{id:string;policy:string}[]};

async function read(r:Response){const t=await r.text();try{return JSON.parse(t)}catch{return{detail:t||`Request failed (${r.status})`}}}
function authToken(){return localStorage.getItem('odin_admin_token')||localStorage.getItem('iam_account_token')||''}

export default function MuxPage(){
 const[connected,setConnected]=useState(false),[tokenId,setTokenId]=useState(''),[tokenSecret,setTokenSecret]=useState(''),[envKey,setEnvKey]=useState(''),[label,setLabel]=useState('My Mux Account'),[assets,setAssets]=useState<Asset[]>([]),[file,setFile]=useState<File|null>(null),[inputUrl,setInputUrl]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 function headers(json=false){const token=authToken();return{...(json?{'Content-Type':'application/json'}:{}),Authorization:`Bearer ${token}`}}
 async function status(){const token=authToken();if(!token){location.replace('/login');return}try{const r=await fetch(`${api}/api/mux/status`,{headers:headers()});const d=await read(r);if(r.status===401){location.replace('/login');return}if(!r.ok)throw new Error(d.detail||'Unable to load Mux status.');setConnected(!!d.connected);setEnvKey(d.env_key||'');if(d.connected)await loadAssets()}catch(e:any){setError(e.message||'Unable to load Mux status.')}}
 async function connect(){setBusy(true);setError('');setMessage('');try{const r=await fetch(`${api}/api/mux/connect`,{method:'POST',headers:headers(true),body:JSON.stringify({token_id:tokenId,token_secret:tokenSecret,env_key:envKey,label})});const d=await read(r);if(!r.ok)throw new Error(d.detail||'Mux connection failed.');setConnected(true);setTokenId('');setTokenSecret('');setMessage('Mux account verified and connected securely.');await loadAssets()}catch(e:any){setError(e.message||'Mux connection failed.')}finally{setBusy(false)}}
 async function disconnect(){setBusy(true);try{await fetch(`${api}/api/mux/disconnect`,{method:'DELETE',headers:headers()});setConnected(false);setAssets([]);setMessage('Mux disconnected.')}finally{setBusy(false)}}
 async function loadAssets(){try{const r=await fetch(`${api}/api/mux/assets?limit=30`,{headers:headers()});const d=await read(r);if(r.ok)setAssets(d.assets||[])}catch{}}
 async function uploadFile(){if(!file)return;setBusy(true);setError('');setMessage('Creating secure Mux upload…');try{const r=await fetch(`${api}/api/mux/uploads`,{method:'POST',headers:headers(true),body:JSON.stringify({cors_origin:location.origin})});const d=await read(r);if(!r.ok||!d.upload?.url)throw new Error(d.detail||'Unable to create Mux upload.');setMessage('Uploading directly to Mux…');const up=await fetch(d.upload.url,{method:'PUT',body:file,headers:{'Content-Type':file.type||'application/octet-stream'}});if(!up.ok)throw new Error(`Mux upload failed (${up.status}).`);setMessage('Upload complete. Mux is processing the video; refresh assets shortly.');setFile(null);setTimeout(loadAssets,1500)}catch(e:any){setError(e.message||'Upload failed.')}finally{setBusy(false)}}
 async function createFromUrl(){if(!inputUrl.trim())return;setBusy(true);setError('');try{const r=await fetch(`${api}/api/mux/assets`,{method:'POST',headers:headers(true),body:JSON.stringify({input_url:inputUrl.trim()})});const d=await read(r);if(!r.ok)throw new Error(d.detail||'Unable to create Mux asset.');setInputUrl('');setMessage('Mux asset created and processing.');await loadAssets()}catch(e:any){setError(e.message||'Unable to create Mux asset.')}finally{setBusy(false)}}
 useEffect(()=>{status()},[]);
 return <main style={{minHeight:'100vh',background:'#060911',color:'#eef4ff',padding:24,fontFamily:'Inter,system-ui,sans-serif'}}><div style={{maxWidth:1180,margin:'0 auto'}}>
  <header style={{display:'flex',justifyContent:'space-between',gap:18,alignItems:'end',flexWrap:'wrap'}}><div><a href="/video-studio" style={{color:'#7de5ff',textDecoration:'none'}}>← Video Studio</a><p style={{fontSize:11,letterSpacing:'.18em',color:'#74dfff',fontWeight:800}}>I AM MAGNANIMOUS WAY™ • VIDEO</p><h1 style={{fontSize:'clamp(32px,6vw,58px)',margin:'6px 0'}}>Mux Video</h1><p style={{maxWidth:720,color:'#9eacc0',lineHeight:1.6}}>Connect your own Mux account, upload video directly, and manage your Mux assets. Each I AM account stores its own Mux connection separately.</p></div><span style={{padding:'9px 12px',borderRadius:999,border:'1px solid #29465a',color:connected?'#8ff2ad':'#ffc786'}}>{connected?'● Mux Connected':'○ Not Connected'}</span></header>
  {error&&<div style={{marginTop:18,padding:13,border:'1px solid #65303a',borderRadius:12,color:'#ffb8c1',background:'#1a0d12'}}>{error}</div>}{message&&<div style={{marginTop:18,padding:13,border:'1px solid #28513b',borderRadius:12,color:'#a8f4c0',background:'#09160f'}}>{message}</div>}
  {!connected?<section style={{marginTop:26,padding:22,border:'1px solid #1e3448',borderRadius:18,background:'#0a111c'}}><h2>Connect Mux</h2><p style={{color:'#9eacc0'}}>In Mux Dashboard, open <b>Settings → Access Tokens</b> and create a token with Mux Video Read + Write. Mux requires both the Token ID and Token Secret. The Mux Data Environment Key is optional and is used for analytics, not API authentication.</p><div style={{display:'grid',gap:11,maxWidth:650}}><input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Connection name" style={input}/><input value={tokenId} onChange={e=>setTokenId(e.target.value)} placeholder="Mux Access Token ID" style={input}/><input value={tokenSecret} onChange={e=>setTokenSecret(e.target.value)} type="password" autoComplete="off" placeholder="Mux Access Token Secret" style={input}/><input value={envKey} onChange={e=>setEnvKey(e.target.value)} placeholder="Mux Data Environment Key (optional)" style={input}/><button disabled={busy||!tokenId||!tokenSecret} onClick={connect} style={button}>{busy?'Verifying…':'Verify & Connect Mux'}</button></div><p style={{fontSize:12,color:'#74859a'}}>Your Token ID and Secret are sent only to the server, verified with Mux, encrypted before storage, and never returned to the browser.</p></section>:
  <><section style={{marginTop:26,display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:16}}><article style={card}><h2>Upload a Video</h2><p style={muted}>The file uploads directly from your browser to Mux using a short-lived signed URL.</p><input type="file" accept="video/*" onChange={e=>setFile(e.target.files?.[0]||null)} style={{...input,padding:10}}/><button disabled={busy||!file} onClick={uploadFile} style={button}>{busy?'Working…':'Upload to Mux'}</button></article><article style={card}><h2>Import Video URL</h2><p style={muted}>Give Mux a publicly accessible MP4/MOV/video URL and it will ingest and process it.</p><input value={inputUrl} onChange={e=>setInputUrl(e.target.value)} placeholder="https://example.com/video.mp4" style={input}/><button disabled={busy||!inputUrl.trim()} onClick={createFromUrl} style={button}>Create Mux Asset</button></article><article style={card}><h2>Connection</h2><p style={muted}>{envKey?'Mux Data analytics key is saved for this workspace.':'Mux Data environment key is optional.'}</p><button onClick={loadAssets} style={secondary}>Refresh Assets</button><button onClick={disconnect} disabled={busy} style={{...secondary,borderColor:'#66313a',color:'#ffb3bc'}}>Disconnect Mux</button></article></section>
  <section style={{marginTop:24,padding:20,border:'1px solid #1e3448',borderRadius:18,background:'#0a111c'}}><h2>Your Mux Assets</h2>{assets.length===0?<p style={muted}>No assets returned yet. Upload a video or refresh after Mux finishes processing.</p>:<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:16}}>{assets.map(a=>{const pid=a.playback_ids?.find(p=>p.policy==='public')?.id||a.playback_ids?.[0]?.id;return <article key={a.id} style={{border:'1px solid #1b3042',borderRadius:14,overflow:'hidden',background:'#070d15'}}>{pid?<iframe src={`https://player.mux.com/${encodeURIComponent(pid)}`} allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture" allowFullScreen style={{width:'100%',aspectRatio:'16/9',border:0}}/>:<div style={{aspectRatio:'16/9',display:'grid',placeItems:'center',color:'#718398'}}>Processing…</div>}<div style={{padding:13}}><b>{a.status||'unknown'}</b><div style={{fontSize:11,color:'#718398',wordBreak:'break-all',marginTop:6}}>{a.id}</div></div></article>})}</div>}</section></>}
 </div></main>
}
const input:React.CSSProperties={width:'100%',boxSizing:'border-box',padding:'13px 14px',borderRadius:11,border:'1px solid #294156',background:'#08111a',color:'#fff'};
const button:React.CSSProperties={padding:'13px 16px',border:0,borderRadius:11,background:'linear-gradient(90deg,#00b9e8,#6b62ff)',color:'#fff',fontWeight:800,cursor:'pointer'};
const secondary:React.CSSProperties={display:'block',width:'100%',marginTop:10,padding:'11px 14px',border:'1px solid #304861',borderRadius:10,background:'#0c1623',color:'#dff6ff',cursor:'pointer'};
const card:React.CSSProperties={padding:20,border:'1px solid #1e3448',borderRadius:18,background:'#0a111c'};
const muted:React.CSSProperties={color:'#93a3b8',lineHeight:1.55};
