'use client';
import {FormEvent,useEffect,useState} from 'react';
import {getPlatformAuthToken} from '../lib/magnanimous-session';

const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
async function read(r:Response){const t=await r.text();try{return JSON.parse(t)}catch{return{detail:t||`Request failed (${r.status})`}}}

export default function EnterprisePage(){
 const[token,setToken]=useState(''),[overview,setOverview]=useState<any>(null),[accounts,setAccounts]=useState<any[]>([]),[contracts,setContracts]=useState<any[]>([]),[opps,setOpps]=useState<any[]>([]),[providers,setProviders]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState('');
 const[accountForm,setAccountForm]=useState({name:'',industry:'',country:'',primary_contact_name:'',primary_contact_email:''});
 const[oppForm,setOppForm]=useState({name:'',account_id:'',estimated_monthly_value_usd:'',estimated_setup_value_usd:'',probability_percent:'25',next_action:''});
 const[contractForm,setContractForm]=useState({account_id:'',title:'',monthly_commitment_usd:'',setup_fee_usd:'',included_usage_usd:'',service_lines:'customer service, contact center, BPO operations'});
 async function authed(path:string,init:RequestInit={}){return fetch(`${api}${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(init.headers||{})},cache:'no-store'})}
 async function get(path:string){const r=await authed(path),d=await read(r);if(!r.ok)throw new Error(d.detail||'Request failed.');return d}
 async function load(){try{const[o,a,c,p,v]=await Promise.all([get('/api/enterprise/overview'),get('/api/enterprise/accounts'),get('/api/enterprise/contracts'),get('/api/enterprise/opportunities'),get('/api/enterprise/providers')]);setOverview(o);setAccounts(a.accounts||[]);setContracts(c.contracts||[]);setOpps(p.opportunities||[]);setProviders(v.providers||[]);setError('')}catch(e:any){setError(e?.message||'Unable to load Enterprise Command.')}}
 useEffect(()=>{const t=getPlatformAuthToken();if(!t){location.href='/login';return}setToken(t)},[]);
 useEffect(()=>{if(token)load()},[token]);
 async function post(path:string,body:any){const r=await authed(path,{method:'POST',body:JSON.stringify(body)}),d=await read(r);if(!r.ok)throw new Error(d.detail||'Request failed.');return d}
 async function createAccount(e:FormEvent){e.preventDefault();setBusy('account');try{await post('/api/enterprise/accounts',accountForm);setAccountForm({name:'',industry:'',country:'',primary_contact_name:'',primary_contact_email:''});await load()}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function createOpp(e:FormEvent){e.preventDefault();setBusy('opp');try{await post('/api/enterprise/opportunities',{...oppForm,estimated_monthly_value_usd:Number(oppForm.estimated_monthly_value_usd||0),estimated_setup_value_usd:Number(oppForm.estimated_setup_value_usd||0),probability_percent:Number(oppForm.probability_percent||10)});setOppForm({name:'',account_id:'',estimated_monthly_value_usd:'',estimated_setup_value_usd:'',probability_percent:'25',next_action:''});await load()}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function createContract(e:FormEvent){e.preventDefault();setBusy('contract');try{await post('/api/enterprise/contracts',{...contractForm,monthly_commitment_usd:Number(contractForm.monthly_commitment_usd||0),setup_fee_usd:Number(contractForm.setup_fee_usd||0),included_usage_usd:Number(contractForm.included_usage_usd||0),service_lines:contractForm.service_lines.split(',').map(x=>x.trim()).filter(Boolean),target_gross_margin_percent:20,payment_terms_days:15});setContractForm({account_id:'',title:'',monthly_commitment_usd:'',setup_fee_usd:'',included_usage_usd:'',service_lines:'customer service, contact center, BPO operations'});await load()}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function topup(){setBusy('topup');try{const d=await post('/api/enterprise/usage-wallet/topup',{});location.href=d.url}catch(e:any){setError(e.message);setBusy('')}}
 const money=(n:any)=>`$${Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;
 return <main className="page">
  <header><div><small>MAGNANIMOUS ENTERPRISE</small><h1>Enterprise Command</h1><p>Turn the platform into contracted, customer-funded BPO and contact-center revenue without sacrificing the free-first core.</p></div><nav><a href="/contact-center">CX Command</a><a href="/bpo-operations">BPO Ops</a><a href="/pricing">Pricing</a></nav></header>
  {error&&<div className="error">{error}</div>}
  <section className="stats"><article><small>CONTRACTED MRR</small><b>{money(overview?.contracted_mrr_usd)}</b></article><article><small>WEIGHTED PIPELINE</small><b>{money(overview?.weighted_pipeline_usd)}</b></article><article><small>OPEN OPPORTUNITIES</small><b>{overview?.open_opportunities||0}</b></article><article><small>PREPAID USAGE</small><b>{money(overview?.usage?.prepaid_balance_usd)}</b><button onClick={topup} disabled={busy==='topup'}>{busy==='topup'?'Opening…':'Add credits'}</button></article></section>
  <section className="grid">
   <article className="panel"><h2>Enterprise accounts</h2><form onSubmit={createAccount}><input required placeholder="Client / prospect name" value={accountForm.name} onChange={e=>setAccountForm({...accountForm,name:e.target.value})}/><div className="two"><input placeholder="Industry" value={accountForm.industry} onChange={e=>setAccountForm({...accountForm,industry:e.target.value})}/><input placeholder="Country" value={accountForm.country} onChange={e=>setAccountForm({...accountForm,country:e.target.value})}/></div><div className="two"><input placeholder="Primary contact" value={accountForm.primary_contact_name} onChange={e=>setAccountForm({...accountForm,primary_contact_name:e.target.value})}/><input type="email" placeholder="Contact email" value={accountForm.primary_contact_email} onChange={e=>setAccountForm({...accountForm,primary_contact_email:e.target.value})}/></div><button disabled={busy==='account'}>Create enterprise account</button></form><div className="list">{accounts.map(a=><div key={a.id}><b>{a.name}</b><span>{a.industry||'Enterprise'} · {a.country||'Global'} · {a.status}</span></div>)}</div></article>
   <article className="panel"><h2>Revenue pipeline</h2><form onSubmit={createOpp}><input required placeholder="Opportunity name" value={oppForm.name} onChange={e=>setOppForm({...oppForm,name:e.target.value})}/><select value={oppForm.account_id} onChange={e=>setOppForm({...oppForm,account_id:e.target.value})}><option value="">No account yet</option>{accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select><div className="two"><input type="number" min="0" placeholder="Monthly value $" value={oppForm.estimated_monthly_value_usd} onChange={e=>setOppForm({...oppForm,estimated_monthly_value_usd:e.target.value})}/><input type="number" min="0" placeholder="Setup value $" value={oppForm.estimated_setup_value_usd} onChange={e=>setOppForm({...oppForm,estimated_setup_value_usd:e.target.value})}/></div><input placeholder="Next action" value={oppForm.next_action} onChange={e=>setOppForm({...oppForm,next_action:e.target.value})}/><button disabled={busy==='opp'}>Add opportunity</button></form><div className="list">{opps.map(o=><div key={o.id}><b>{o.name}</b><span>{o.stage} · {money(o.estimated_monthly_value_usd)}/mo · {o.probability_percent}%</span></div>)}</div></article>
   <article className="panel"><h2>Contracts</h2><form onSubmit={createContract}><select required value={contractForm.account_id} onChange={e=>setContractForm({...contractForm,account_id:e.target.value})}><option value="">Choose enterprise account</option>{accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select><input required placeholder="Contract / statement of work title" value={contractForm.title} onChange={e=>setContractForm({...contractForm,title:e.target.value})}/><div className="two"><input type="number" min="0" placeholder="Monthly commitment $" value={contractForm.monthly_commitment_usd} onChange={e=>setContractForm({...contractForm,monthly_commitment_usd:e.target.value})}/><input type="number" min="0" placeholder="Setup fee $" value={contractForm.setup_fee_usd} onChange={e=>setContractForm({...contractForm,setup_fee_usd:e.target.value})}/></div><input type="number" min="0" placeholder="Included premium usage $" value={contractForm.included_usage_usd} onChange={e=>setContractForm({...contractForm,included_usage_usd:e.target.value})}/><input placeholder="Service lines, comma separated" value={contractForm.service_lines} onChange={e=>setContractForm({...contractForm,service_lines:e.target.value})}/><button disabled={busy==='contract'}>Create draft contract</button></form><div className="list">{contracts.map(c=><div key={c.id}><b>{c.title}</b><span>{c.account_name} · {money(c.monthly_commitment_usd)}/mo · {c.status}</span></div>)}</div></article>
   <article className="panel providers"><h2>Provider fabric</h2><p>Free-first engines stay preferred. Metered infrastructure activates only when configured and funded.</p><div className="providerGrid">{providers.map(p=><div key={p.id} className={p.configured?'on':''}><b>{p.name}</b><span>{p.category} · {p.cost_model}</span><em>{p.configured?'READY':'OPTIONAL / NEEDS AUTH'}</em></div>)}</div></article>
  </section>
  <section className="principles"><b>Enterprise rule</b><p>Banking, healthcare and regulated clients stay isolated by client/program. Their private systems are accessed only through credentials and APIs the client explicitly authorizes. No contract or connection is treated as active merely because a record exists here.</p></section>
  <style jsx>{`
   .page{min-height:100vh;background:#05090d;color:#eaf4f7;font-family:Inter,system-ui,sans-serif;padding:28px}header{max-width:1300px;margin:auto;display:flex;justify-content:space-between;gap:24px;align-items:end;padding:30px 0}header small{color:#62e7b0;letter-spacing:.16em;font-weight:900}h1{font-size:clamp(38px,6vw,72px);margin:5px 0}header p{color:#91a7b3;max-width:760px;line-height:1.6}nav{display:flex;gap:8px;flex-wrap:wrap}nav a{color:#d9ecf3;text-decoration:none;border:1px solid #29404b;padding:10px;border-radius:9px}.error{max-width:1300px;margin:0 auto 14px;padding:12px;border:1px solid #713846;background:#2b1018;border-radius:10px}.stats{max-width:1300px;margin:auto;display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.stats article,.panel,.principles{border:1px solid #203944;background:#081118;border-radius:16px;padding:18px}.stats small{display:block;color:#6edeb5;font-size:9px;letter-spacing:.12em}.stats b{display:block;font-size:28px;margin-top:8px}.stats button{margin-top:9px}.grid{max-width:1300px;margin:14px auto;display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.panel h2{margin-top:0}.panel p,.principles p{color:#91a7b3;line-height:1.55}form{display:grid;gap:9px;margin-bottom:16px}.two{display:grid;grid-template-columns:1fr 1fr;gap:9px}input,select,button{box-sizing:border-box;width:100%;padding:11px 12px;border:1px solid #29434f;border-radius:9px;background:#07151d;color:#eef9fc}button{background:#12442f;border-color:#2a815a;color:#bdfbdd;font-weight:900;cursor:pointer}.list{display:grid;gap:7px}.list>div{display:flex;justify-content:space-between;gap:12px;padding:9px;border-top:1px solid #172a33}.list span{font-size:11px;color:#8ba0ab;text-align:right}.providerGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.providerGrid>div{padding:10px;border:1px solid #2b3339;border-radius:10px;display:grid;gap:4px}.providerGrid>div.on{border-color:#286447}.providerGrid span{color:#91a7b3;font-size:10px}.providerGrid em{font-size:9px;color:#da9c60;font-style:normal}.providerGrid .on em{color:#68e7a9}.principles{max-width:1264px;margin:14px auto}.principles b{color:#ffcd70}@media(max-width:900px){header{display:block}.stats,.grid{grid-template-columns:1fr 1fr}.providerGrid{grid-template-columns:1fr}}@media(max-width:620px){.page{padding:16px}.stats,.grid,.two{grid-template-columns:1fr}.list>div{display:grid}.list span{text-align:left}}
  `}</style>
 </main>
}
