'use client';
import {useEffect,useRef,useState} from 'react';
import {getPlatformAuthToken} from '../lib/magnanimous-session';
import {speakTextNaturally,stopNaturalSpeech} from '../../lib/natural-speech';

const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
type Config={plan:string;policy:any;pricing:any;studio:any;monetization:any};
type Asset={asset_url?:string|null;download_url?:string|null;watch_url?:string|null;social_publish_url?:string|null;data_uri?:string|null;content_type?:string;watermarked?:boolean};
async function read(r:Response){const t=await r.text();try{return JSON.parse(t)}catch{return{detail:t||`Request failed (${r.status})`}}}
function fileData(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}

export default function MovieMakerPage(){
 const[token,setToken]=useState(''),[config,setConfig]=useState<Config|null>(null),[title,setTitle]=useState('My Magnanimous Movie'),[prompt,setPrompt]=useState(''),[style,setStyle]=useState('cinematic'),[kind,setKind]=useState<'image'|'video'>('video'),[mode,setMode]=useState<'free'|'studio'>('free'),[imageQuality,setImageQuality]=useState('balanced'),[videoQuality,setVideoQuality]=useState('economy'),[aspect,setAspect]=useState('16:9'),[size,setSize]=useState('2K'),[resolution,setResolution]=useState('720p'),[seconds,setSeconds]=useState(6),[references,setReferences]=useState<string[]>([]),[asset,setAsset]=useState<Asset|null>(null),[job,setJob]=useState(''),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[scenes,setScenes]=useState<any[]>([]),[narration,setNarration]=useState(''),[voiceAsset,setVoiceAsset]=useState<Asset|null>(null);
 const pollRef=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{const t=getPlatformAuthToken();if(!t){location.replace('/login?returnTo=%2Fmovie-maker');return}setToken(t);void load(t);return()=>{if(pollRef.current)clearTimeout(pollRef.current);stopNaturalSpeech()}},[]);
 async function load(t=token){const r=await fetch(api+'/api/movie-maker/config',{headers:{Authorization:'Bearer '+t},cache:'no-store'}),d=await read(r);if(!r.ok){setMessage(d.detail||'Movie Maker could not load.');return}setConfig(d)}
 function headers(){return{'Content-Type':'application/json',Authorization:'Bearer '+token}}
 async function picked(files:FileList|null){if(!files)return;const list=[] as string[];for(const f of Array.from(files).slice(0,14)){if(f.size>8_000_000){setMessage('Reference images must be 8 MB or smaller.');continue}list.push(await fileData(f))}setReferences(list)}
 async function plan(){if(!prompt.trim())return;setBusy('plan');setMessage('');const r=await fetch(api+'/api/movie-maker/plan',{method:'POST',headers:headers(),body:JSON.stringify({title,script:prompt,max_scenes:12})}),d=await read(r);setBusy('');if(!r.ok){setMessage(d.detail||'Movie planning failed.');return}setScenes(d.scenes||[]);setNarration((d.scenes||[]).map((x:any)=>x.narration).join(' '));setMessage('Storyboard ready. You can create a finished image or video from any idea, or use the scenes as your production plan.')}
 async function create(){if(!prompt.trim())return;setBusy('create');setMessage('Magnanimous is creating your '+kind+'…');setAsset(null);setScenes([]);const body:any={title,prompt,style,mode,quality:kind==='image'?imageQuality:videoQuality,aspect_ratio:aspect,image_size:size,resolution,seconds,reference_images:references};if(kind==='video'&&references[0])body.reference_image=references[0];const r=await fetch(api+`/api/movie-maker/${kind}`,{method:'POST',headers:headers(),body:JSON.stringify(body)}),d=await read(r);if(!r.ok){setBusy('');setMessage(d.detail||'Creation failed.');return}if(d.job_id){setJob(d.job_id);setMessage('Studio movie started. Magnanimous is rendering it now…');poll(d.job_id);return}setAsset(d.asset||null);setBusy('');setMessage(d.policy?.watermark_required?'Finished with the plan-required Magnanimous watermark.':'Finished clean export ready.')}
 async function poll(id:string){const r=await fetch(api+`/api/movie-maker/jobs/${id}`,{headers:{Authorization:'Bearer '+token},cache:'no-store'}),d=await read(r);if(r.ok&&d.status==='completed'){setAsset(d.asset||null);setBusy('');setJob('');setMessage('Studio movie finished.');return}if(!r.ok||['failed','billing_reconciliation_failed'].includes(d.status)){setBusy('');setMessage(d.detail||'Studio movie could not finish.');return}pollRef.current=setTimeout(()=>poll(id),3500)}
 function speak(){const text=(narration||prompt).trim();if(!text||typeof window==='undefined'||!('speechSynthesis'in window)){setMessage('Browser narration is not available on this device.');return}stopNaturalSpeech();speakTextNaturally(text,{maxChunkChars:260,interChunkDelayMs:50,configure:(u)=>{u.rate=.96;u.pitch=1;u.volume=1;const voices=window.speechSynthesis.getVoices();const v=voices.find(x=>/^en/i.test(x.lang)&&/premium|enhanced|natural|neural|siri|google|microsoft/i.test(x.name))||voices.find(x=>/^en/i.test(x.lang));if(v)u.voice=v}})}
 async function studioVoice(quality:'economy'|'max'='max'){const text=(narration||prompt).trim();if(!text)return;setBusy('voice');setVoiceAsset(null);setMessage('Creating studio narration…');const r=await fetch(api+'/api/movie-maker/voice',{method:'POST',headers:headers(),body:JSON.stringify({title,text,quality})}),d=await read(r);setBusy('');if(!r.ok){setMessage(d.detail||'Studio narration failed.');return}setVoiceAsset(d.asset||null);setMessage(d.billing?.billing_mode==='free'?'Generated narration ready on the configured free voice tier.':`Studio narration ready. Retail reference at origin cost + 20%: ${Number(d.billing?.retail_reference_usd||0).toFixed(4)}.`)}
 async function copyLink(){const value=asset?.watch_url||asset?.asset_url||asset?.data_uri||'';if(!value)return;await navigator.clipboard.writeText(value);setMessage('Share link copied.')}
 async function share(){const url=asset?.watch_url||asset?.asset_url||'';if(!url)return;if(navigator.share){await navigator.share({title,text:title,url});return}await navigator.clipboard.writeText(url);setMessage('Share link copied.')}
 function social(){const u=asset?.social_publish_url;if(u)location.href=u;else if(asset?.asset_url)location.href=`/social-connect?video_url=${encodeURIComponent(asset.asset_url)}&title=${encodeURIComponent(title)}`}
 const watermark=config?.policy?.watermark_required,studioAllowed=config?.policy?.premium_studio_allowed;
 return <main className="page"><header><a href="/">← Dashboard</a><div><small>I AM MAGNANIMOUS WAY™</small><h1>Magnanimous Movie Maker</h1><p>Write an idea, upload references, build scenes, create pictures or movies, hear narration, download, copy, share, and publish through your connected social accounts.</p></div><a href="/social-connect">Social Connections →</a></header>
 <section className="status"><b>{config?config.plan.toUpperCase():'LOADING'}</b><span>{watermark?'Magnanimous watermark on exports':'Clean exports'}</span><span>20% markup only on funded studio usage</span><span>{studioAllowed?'Studio enabled by plan':'Free-first creator mode'}</span></section>
 <section className="grid"><div className="panel"><label>Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Story, image, or movie idea<textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Describe realistic people, animated characters, camera movement, dialogue, setting, emotion, lighting, action, and ending…"/></label>
 <div className="row"><label>Output<select value={kind} onChange={e=>setKind(e.target.value as any)}><option value="video">Movie / Video</option><option value="image">Picture / Poster</option></select></label><label>Mode<select value={mode} onChange={e=>setMode(e.target.value as any)}><option value="free">Free-first</option><option value="studio" disabled={!studioAllowed}>Studio quality{!studioAllowed?' · Business+':''}</option></select></label><label>Aspect<select value={aspect} onChange={e=>setAspect(e.target.value)}><option>16:9</option><option>9:16</option><option>1:1</option><option>4:5</option><option>3:2</option><option>2:3</option><option>21:9</option></select></label></div>
 <div className="row"><label>Style<select value={style} onChange={e=>setStyle(e.target.value)}><option>cinematic</option><option>realistic</option><option>animated</option><option>business</option><option>social</option><option>faith</option><option>nature</option></select></label>{kind==='image'?<><label>Studio quality<select value={imageQuality} onChange={e=>setImageQuality(e.target.value)}><option value="economy">Economy</option><option value="balanced">Balanced</option><option value="max">Maximum</option></select></label><label>Image pixels<select value={size} onChange={e=>setSize(e.target.value)}><option>0.5K</option><option>1K</option><option>2K</option><option>4K</option></select></label></>:<><label>Studio quality<select value={videoQuality} onChange={e=>setVideoQuality(e.target.value)}><option value="economy">Economy</option><option value="fast">Fast</option><option value="editable">Editable</option><option value="max">Maximum / 4K</option></select></label><label>Resolution<select value={resolution} onChange={e=>setResolution(e.target.value)}><option>720p</option><option>1080p</option><option>4k</option></select></label><label>Seconds<input type="number" min={3} max={mode==='studio'?10:60} value={seconds} onChange={e=>setSeconds(Number(e.target.value))}/></label></>}</div>
 <label className="upload">Reference images — up to 14<input type="file" accept="image/*" multiple onChange={e=>picked(e.target.files)}/><span>{references.length?references.length+' reference image(s) loaded':'Use faces, characters, products, locations, or style references you have rights to use.'}</span></label>
 <div className="buttons"><button onClick={plan} disabled={!!busy||!prompt.trim()}>{busy==='plan'?'PLANNING…':'BUILD STORYBOARD'}</button><button className="primary" onClick={create} disabled={!!busy||!prompt.trim()}>{busy==='create'?'CREATING…':`CREATE ${kind.toUpperCase()}`}</button><button onClick={speak} disabled={!prompt.trim()}>HEAR FREE NARRATION</button>{config?.studio?.voice_enabled&&<><button onClick={()=>studioVoice('economy')} disabled={!!busy||!prompt.trim()}>{busy==='voice'?'CREATING VOICE…':'CREATE ECONOMY VOICE'}</button><button onClick={()=>studioVoice('max')} disabled={!!busy||!prompt.trim()}>{busy==='voice'?'CREATING VOICE…':'CREATE MAX STUDIO VOICE'}</button></>}</div>{message&&<p className="notice">{message}</p>}{voiceAsset?.asset_url&&<div className="voice"><small>STUDIO NARRATION</small><audio src={voiceAsset.asset_url} controls/><a href={voiceAsset.download_url||voiceAsset.asset_url} download target="_blank" rel="noopener noreferrer">Download narration</a></div>}
 </div><aside className="panel"><h2>Production rules</h2><p><b>Free + Plus:</b> pictures and videos carry the Magnanimous AI watermark. Free public watch pages can show clearly labeled owner-approved ads/sponsors.</p><p><b>Business and above:</b> clean exports. Economy, editable, fast and maximum-quality studio choices use verified direct-source pricing plus exactly 20%, only when included allowance or prepaid funding covers it.</p><p><b>No fake ad clicks:</b> Movie Maker can create strong titles/thumbnails and measure real views/clicks, but never incentivizes or manufactures ad engagement.</p><p><b>Rights:</b> users must have permission to use uploaded people, voices, logos, music, and copyrighted source material.</p></aside></section>
 {scenes.length>0&&<section className="story"><div className="storyHead"><div><small>STORYBOARD</small><h2>{scenes.length} scenes</h2></div><button onClick={speak}>Narrate storyboard</button></div><div className="sceneGrid">{scenes.map((s:any)=><article key={s.scene}><b>{String(s.scene).padStart(2,'0')}</b><p>{s.narration}</p><small>{s.seconds}s suggested</small></article>)}</div></section>}
 {asset&&<section className="result"><div><small>FINISHED ASSET</small><h2>{title}</h2>{asset.content_type?.startsWith('video')?<video src={asset.asset_url||asset.data_uri||''} controls playsInline/>:<img src={asset.asset_url||asset.data_uri||''} alt={title}/>}</div><div className="actions">{asset.download_url&&<a href={asset.download_url} download target="_blank" rel="noopener noreferrer">Download</a>}<button onClick={copyLink}>Copy link</button><button onClick={share}>Share</button>{kind==='video'&&<button onClick={social}>YouTube • TikTok • LinkedIn</button>}</div></section>}
 <style jsx>{`.page{min-height:100vh;background:#05090f;color:#eef8ff;padding:26px;font-family:Inter,system-ui,sans-serif;background-image:radial-gradient(circle at 20% 5%,#132d4d 0,transparent 28%),radial-gradient(circle at 90% 45%,#321849 0,transparent 26%)}header,.status,.grid,.story,.result{max-width:1400px;margin:auto}header{display:grid;grid-template-columns:auto 1fr auto;gap:24px;align-items:start}header a{color:#72eaff;text-decoration:none}header small,.story small,.result small{color:#70dfff;letter-spacing:.17em}h1{font-size:clamp(42px,7vw,84px);line-height:.9;margin:9px 0}header p{max-width:850px;color:#9bb0c3;line-height:1.6}.status{display:flex;gap:10px;flex-wrap:wrap;margin-top:20px}.status span,.status b{border:1px solid #274358;border-radius:999px;padding:8px 11px;font-size:11px}.grid{display:grid;grid-template-columns:1fr 360px;gap:14px;margin-top:14px}.panel,.story,.result{border:1px solid #223b50;background:#08111cde;border-radius:20px;padding:20px}.panel label{display:block;color:#8fa9bd;font-size:11px;text-transform:uppercase;letter-spacing:.07em;margin-bottom:12px}input,textarea,select{width:100%;box-sizing:border-box;margin-top:7px;border:1px solid #29445d;border-radius:10px;background:#07101a;color:#fff;padding:12px;font:inherit;text-transform:none;letter-spacing:0}textarea{min-height:210px;line-height:1.5}.row{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.upload{border:1px dashed #31536c;padding:13px;border-radius:12px}.upload span{display:block;margin-top:7px;color:#6f8799;text-transform:none;letter-spacing:0}.buttons,.actions{display:flex;gap:8px;flex-wrap:wrap}.buttons button,.actions button,.actions a,.story button{border:1px solid #31516b;background:#0c1b28;color:#e9f9ff;padding:11px 14px;border-radius:10px;font-weight:800;text-decoration:none;cursor:pointer}.buttons .primary{background:linear-gradient(90deg,#27def2,#795fff,#ef5edb);border:0}.notice{padding:11px;border:1px solid #31526a;border-radius:10px;color:#78e9ff}.voice{margin-top:12px;border:1px solid #2b495f;border-radius:12px;padding:12px}.voice small{display:block;color:#70dfff;letter-spacing:.14em}.voice audio{width:100%;margin:10px 0}.voice a{color:#77eaff;text-decoration:none;font-weight:800}.panel h2{margin-top:0}.panel p{color:#9db0c0;line-height:1.55}.story{margin-top:14px}.storyHead{display:flex;justify-content:space-between}.sceneGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.sceneGrid article{border:1px solid #21394d;border-radius:12px;padding:13px;background:#07101a}.sceneGrid b{color:#70eaff}.sceneGrid p{line-height:1.45}.sceneGrid small{color:#748b9e;letter-spacing:0}.result{margin-top:14px}.result video,.result img{width:100%;max-height:720px;object-fit:contain;background:#000;border-radius:14px}.actions{margin-top:12px}@media(max-width:900px){header,.grid,.row{grid-template-columns:1fr}.sceneGrid{grid-template-columns:1fr}.page{padding:16px}header>a:last-child{display:none}}`}</style></main>
}
