(()=>{
const style=document.createElement('style');style.textContent=`
.creatorWrap{width:min(1180px,94vw);margin:auto}.creatorGrid{display:grid;grid-template-columns:minmax(260px,.8fr) minmax(300px,1.2fr);gap:14px}.creatorPanel{background:#0d1018;border:1px solid #252c3c;border-radius:18px;padding:17px}.creatorPanel h3{margin:0 0 8px}.creatorField{display:grid;gap:6px;margin:10px 0}.creatorField input,.creatorField textarea,.creatorField select{width:100%;background:#090e18;border:1px solid #2b3448;color:#fff;border-radius:11px;padding:11px}.creatorField textarea{min-height:130px;resize:vertical}.hitScripts{display:flex;gap:8px;overflow:auto;padding-bottom:6px}.hitScript{min-width:200px;background:#121827;border:1px solid #2d3850;border-radius:14px;padding:12px;cursor:pointer}.hitScript b{display:block;margin-bottom:5px}.projectList,.workList{display:grid;gap:9px}.projectCard,.episodeCard{background:#111725;border:1px solid #2b3448;border-radius:13px;padding:12px}.projectCard.active{border-color:#d6ac45}.statusPill{display:inline-block;border:1px solid #44516b;border-radius:999px;padding:4px 8px;font-size:11px;color:#c7d0e1}.statusPill.ready,.statusPill.published{border-color:#2d805a;color:#aef0cd}.creatorActions{display:flex;flex-wrap:wrap;gap:7px;margin-top:9px}.creatorNote{font-size:12px;color:#99a4b8}.previewBox{position:relative;aspect-ratio:9/16;max-width:360px;margin:auto;background:#020305;border-radius:20px;overflow:hidden;border:1px solid #2a3244}.previewBox img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;transition:opacity .28s ease,transform 4.5s ease}.previewBox:after{content:"";position:absolute;inset:0;background:linear-gradient(transparent 45%,rgba(0,0,0,.82))}.previewCaption{position:absolute;z-index:2;left:7%;right:7%;bottom:7%;font-size:20px;line-height:1.12;font-weight:900;text-shadow:0 2px 8px #000;text-align:center}.creatorPublished{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:12px}.publishedCard{background:#0d1018;border:1px solid #252c3c;border-radius:15px;overflow:hidden}.publishedCard .thumb{aspect-ratio:9/13;overflow:hidden}.publishedCard img{width:100%;height:100%;object-fit:cover}.publishedCard .body{padding:10px}.freeTag{color:#61e4a7;font-weight:800}.creatorToast{position:fixed;z-index:140;left:50%;bottom:20px;transform:translateX(-50%);background:#121826;border:1px solid #3a4763;color:#fff;padding:10px 14px;border-radius:12px;display:none}.creatorToast.show{display:block}@media(max-width:800px){.creatorGrid{grid-template-columns:1fr}.creatorPanel{padding:14px}}
`;document.head.appendChild(style);

const nav=document.querySelector('.top nav');
if(nav){nav.insertAdjacentHTML('beforeend','<button class="navb" data-go="createReel">Create</button><button class="navb" data-go="workList">Work List</button>')}
const main=document.querySelector('main');
main.insertAdjacentHTML('beforeend',`
<section class="section" id="createReel"><div class="creatorWrap"><h2>Create a Short Drama</h2><p class="sub">EPNOVA-style creation, but native to Magnanimous Reels: start from an idea or hit-story pattern, build episodes, generate a free dynamic-comic preview, then publish when you are ready.</p><div class="creatorGrid"><div class="creatorPanel"><h3>Hit Story Starters</h3><p class="creatorNote">These are original structural prompts, not copied scripts.</p><div class="hitScripts" id="hitScripts"></div><form id="projectForm"><div class="creatorField"><label>Series title</label><input id="creatorTitle" maxlength="80" required placeholder="The Secret Behind the Door"></div><div class="creatorField"><label>Genre</label><select id="creatorGenre"></select></div><div class="creatorField"><label>Premise / hook</label><textarea id="creatorPremise" maxlength="900" required placeholder="Tell us who wants what, what stands in the way, and the twist that makes viewers need the next episode."></textarea></div><button class="btn gold" type="submit">Create series</button></form></div><div class="creatorPanel"><h3>Episode Builder</h3><div id="activeProject" class="status">Create or select a series first.</div><form id="episodeForm"><div class="creatorField"><label>Episode title</label><input id="episodeTitle" maxlength="90" placeholder="Episode 1 — The Message"></div><div class="creatorField"><label>Voice</label><select id="episodeVoice"></select></div><div class="creatorField"><label>Episode script</label><textarea id="episodeScript" maxlength="8000" placeholder="Write a fast hook. Change something every few sentences. End with a reveal, danger, unanswered question, or decision that makes the viewer continue."></textarea></div><button class="btn gold" type="submit">Save episode draft</button><p class="creatorNote">Drafting, native narration, animated-comic preview and publishing are currently ₱0. Paid cinematic-model adapters stay optional and must show price before use.</p></form></div></div></div></section>
<section class="section" id="workList"><div class="creatorWrap"><h2>Work List</h2><p class="sub">Every episode shows its actual status: Draft → Generating → Ready → Published. Unfinished work stays saved.</p><div class="creatorGrid"><div class="creatorPanel"><h3>Your Series</h3><div id="projectList" class="projectList"><div class="muted">No series yet.</div></div></div><div class="creatorPanel"><h3>Episodes</h3><div id="episodeWorkList" class="workList"><div class="muted">Select a series.</div></div></div></div></div></section>
<section class="section" id="creatorSpotlight"><div class="creatorWrap"><h2>Creator Spotlight</h2><p class="sub">Published Magnanimous Reels originals appear here as soon as they are ready.</p><div id="publishedCreatorGrid" class="creatorPublished"><div class="muted">No creator episodes published yet.</div></div></div></section>
<div class="modal hidden" id="creatorPreview"><div class="sheet"><div class="tiny">MAGNANIMOUS REELS PREVIEW</div><h3 id="creatorPreviewTitle">Episode preview</h3><div class="previewBox"><img id="creatorPreviewImg" alt="Creator scene"><div id="creatorPreviewCaption" class="previewCaption"></div></div><div class="controls"><button class="btn gold" id="creatorPreviewPlay">▶ Play</button><button class="btn" id="creatorPreviewClose">Close</button></div><div class="creatorNote">Neural narration is mixed with low-volume genre ambience. Captions and visuals change on the narration timeline.</div><audio id="creatorVoiceAudio" preload="metadata"></audio><audio id="creatorAmbientAudio" preload="auto" loop></audio></div></div>
<div class="creatorToast" id="creatorToast"></div>
`);

const cState={config:null,projects:[],activeProjectId:null,preview:null,previewScene:-1,voiceGraph:null};
const genreAmbient={Drama:'drama',Romance:'romance',Thriller:'thriller',Mystery:'mystery',Fantasy:'fantasy',Action:'action',Adventure:'adventure'};
const cq=q=>document.querySelector(q);
function toast(text){let el=cq('#creatorToast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
async function cfetch(url,opts){let r=await fetch(url,opts);let data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.detail||data.error||'Request failed');return data}
async function cpost(url,payload){return cfetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...payload,device_id:deviceId})})}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function activeProject(){return cState.projects.find(p=>Number(p.id)===Number(cState.activeProjectId))}
function renderConfig(){let c=cState.config;cq('#creatorGenre').innerHTML=c.genres.map(g=>`<option>${esc(g)}</option>`).join('');cq('#episodeVoice').innerHTML=c.voices.map(v=>`<option value="${esc(v.id)}">${esc(v.label)}</option>`).join('');cq('#hitScripts').innerHTML=c.templates.map(t=>`<button type="button" class="hitScript" data-template="${esc(t.id)}"><b>${esc(t.title)}</b><span class="tiny">${esc(t.genre)}</span><div class="creatorNote">${esc(t.hook)}</div></button>`).join('')}
function renderProjects(){let list=cq('#projectList');if(!cState.projects.length){list.innerHTML='<div class="muted">No series yet.</div>';cq('#episodeWorkList').innerHTML='<div class="muted">Select a series.</div>';return}list.innerHTML=cState.projects.map(p=>`<button class="projectCard ${Number(p.id)===Number(cState.activeProjectId)?'active':''}" data-project="${p.id}"><b>${esc(p.title)}</b><div class="tiny">${esc(p.genre)} · ${p.episodes.length} episode${p.episodes.length===1?'':'s'}</div><span class="statusPill ${esc(p.status)}">${esc(p.status)}</span></button>`).join('');renderEpisodes()}
function renderEpisodes(){let p=activeProject();if(!p){cq('#activeProject').textContent='Create or select a series first.';cq('#episodeWorkList').innerHTML='<div class="muted">Select a series.</div>';return}cq('#activeProject').innerHTML=`<b>${esc(p.title)}</b><br><span class="tiny">${esc(p.genre)} · ${esc(p.premise)}</span>`;let box=cq('#episodeWorkList');if(!p.episodes.length){box.innerHTML='<div class="muted">No episodes yet. Write Episode 1.</div>';return}box.innerHTML=p.episodes.map(ep=>`<div class="episodeCard"><div><b>Ep ${ep.episode_number}: ${esc(ep.title)}</b> <span class="statusPill ${esc(ep.status)}">${esc(ep.status)}</span></div><div class="creatorNote">${esc(ep.script.slice(0,180))}${ep.script.length>180?'…':''}</div><div class="creatorActions">${ep.status==='draft'?`<button class="btn gold" data-generate="${ep.id}">Generate free preview</button>`:''}${['ready','published'].includes(ep.status)?`<button class="btn" data-preview="${ep.id}">Preview</button>`:''}${ep.status==='ready'?`<button class="btn gold" data-publish="${ep.id}">Publish</button>`:''}${ep.status==='published'?'<span class="freeTag">Live</span>':''}</div></div>`).join('')}
async function loadProjects(){let d=await cfetch('/api/creator/projects/'+deviceId);cState.projects=d.projects||[];if(cState.activeProjectId&&!cState.projects.some(p=>Number(p.id)===Number(cState.activeProjectId)))cState.activeProjectId=null;if(!cState.activeProjectId&&cState.projects.length)cState.activeProjectId=cState.projects[0].id;renderProjects()}
async function loadPublished(){let d=await cfetch('/api/creator/published');let episodes=d.episodes||[];cq('#publishedCreatorGrid').innerHTML=episodes.length?episodes.map(ep=>`<article class="publishedCard"><div class="thumb"><img src="/assets/${esc(ep.scenes?.[0]?.tag||'citylight')}.jpg" alt="${esc(ep.title)}"></div><div class="body"><b>${esc(ep.project_title)}</b><div class="tiny">Episode ${ep.episode_number} · ${esc(ep.genre)}</div><button class="btn gold" style="width:100%;margin-top:8px" data-preview-public="${ep.id}">▶ Watch</button></div></article>`).join(''):'<div class="muted">No creator episodes published yet.</div>'}
async function initCreator(){cState.config=await cfetch('/api/creator/config');renderConfig();await Promise.all([loadProjects(),loadPublished()])}
cq('#projectForm').addEventListener('submit',async e=>{e.preventDefault();try{let d=await cpost('/api/creator/project',{title:cq('#creatorTitle').value,genre:cq('#creatorGenre').value,premise:cq('#creatorPremise').value});cState.activeProjectId=d.project.id;await loadProjects();toast('Series created. Write Episode 1.');go('workList')}catch(err){toast(err.message)}});
cq('#episodeForm').addEventListener('submit',async e=>{e.preventDefault();let p=activeProject();if(!p){toast('Create or select a series first.');return}try{await cpost('/api/creator/episode',{project_id:p.id,title:cq('#episodeTitle').value||`Episode ${p.episodes.length+1}`,voice_key:cq('#episodeVoice').value,script:cq('#episodeScript').value});cq('#episodeTitle').value='';cq('#episodeScript').value='';await loadProjects();toast('Episode draft saved.');go('workList')}catch(err){toast(err.message)}});
document.addEventListener('click',async e=>{let t=e.target.closest('[data-template]');if(t){let x=cState.config.templates.find(v=>v.id===t.dataset.template);if(x){cq('#creatorTitle').value=x.title;cq('#creatorGenre').value=x.genre;cq('#creatorPremise').value=x.hook;go('createReel')}return}let p=e.target.closest('[data-project]');if(p){cState.activeProjectId=Number(p.dataset.project);renderProjects();return}let g=e.target.closest('[data-generate]');if(g){g.disabled=true;g.textContent='Generating…';try{let d=await cpost('/api/creator/generate',{episode_id:Number(g.dataset.generate)});await loadProjects();toast('Free dynamic preview is ready.');previewEpisode(d.episode.id,true)}catch(err){toast(err.message)}finally{g.disabled=false}return}let pub=e.target.closest('[data-publish]');if(pub){pub.disabled=true;try{await cpost('/api/creator/publish',{episode_id:Number(pub.dataset.publish)});await Promise.all([loadProjects(),loadPublished()]);toast('Episode published to Magnanimous Reels.')}catch(err){toast(err.message)}finally{pub.disabled=false}return}let pre=e.target.closest('[data-preview]');if(pre){previewEpisode(Number(pre.dataset.preview),true);return}let prep=e.target.closest('[data-preview-public]');if(prep){previewEpisode(Number(prep.dataset.previewPublic),false);return}});
function setPreviewScene(i){let p=cState.preview;if(!p||!p.episode.scenes?.length)return;i=Math.max(0,Math.min(p.episode.scenes.length-1,i));if(i===cState.previewScene)return;cState.previewScene=i;let scene=p.episode.scenes[i];let img=cq('#creatorPreviewImg');img.style.opacity='.2';setTimeout(()=>{img.src='/assets/'+scene.tag+'.jpg';img.style.opacity='1';let motions={slow_push:'scale(1.1)',slow_pull:'scale(1.0)',pan_left:'scale(1.08) translateX(-2%)',pan_right:'scale(1.08) translateX(2%)',float_up:'scale(1.06) translateY(-2%)'};img.style.transform=motions[scene.motion]||'scale(1.07)'},100);cq('#creatorPreviewCaption').textContent=scene.text}
function previewSceneForTime(t){let b=cState.preview?.timings||[];if(!b.length)return 0;let i=0;for(let x=0;x<b.length;x++){if(t+.04>=b[x].start)i=x;else break}return i}
function enhanceVoice(){let voice=cq('#creatorVoiceAudio');if(cState.voiceGraph||!window.AudioContext)return;try{let ctx=new AudioContext();let src=ctx.createMediaElementSource(voice);let hp=ctx.createBiquadFilter();hp.type='highpass';hp.frequency.value=70;let comp=ctx.createDynamicsCompressor();comp.threshold.value=-18;comp.knee.value=15;comp.ratio.value=3;comp.attack.value=.006;comp.release.value=.22;let gain=ctx.createGain();gain.gain.value=1.08;src.connect(hp).connect(comp).connect(gain).connect(ctx.destination);cState.voiceGraph={ctx}}catch{}}
async function previewEpisode(id,owner){try{let suffix=owner?'?device='+encodeURIComponent(deviceId):'';let d=await cfetch('/api/creator/episode/'+id+suffix);cState.preview=d;cState.previewScene=-1;cq('#creatorPreviewTitle').textContent=(d.episode.project_title?d.episode.project_title+' — ':'')+d.episode.title;setPreviewScene(0);let voice=cq('#creatorVoiceAudio'),ambient=cq('#creatorAmbientAudio');voice.pause();ambient.pause();voice.src='/creator-audio/'+id+'.mp3'+suffix;let ambientName=genreAmbient[d.episode.genre]||'drama';ambient.src='/ambient/'+ambientName+'.wav';ambient.volume=.055;voice.volume=1;cq('#creatorPreview').classList.remove('hidden');enhanceVoice();await voice.play();ambient.play().catch(()=>{})}catch(err){toast(err.message)}}
cq('#creatorPreviewPlay').onclick=async()=>{let v=cq('#creatorVoiceAudio'),a=cq('#creatorAmbientAudio');enhanceVoice();if(v.paused){await v.play().catch(()=>{});a.play().catch(()=>{});cq('#creatorPreviewPlay').textContent='⏸ Pause'}else{v.pause();a.pause();cq('#creatorPreviewPlay').textContent='▶ Play'}};
cq('#creatorPreviewClose').onclick=()=>{cq('#creatorVoiceAudio').pause();cq('#creatorAmbientAudio').pause();cq('#creatorPreview').classList.add('hidden')};
cq('#creatorVoiceAudio').addEventListener('play',()=>cq('#creatorPreviewPlay').textContent='⏸ Pause');cq('#creatorVoiceAudio').addEventListener('pause',()=>cq('#creatorPreviewPlay').textContent='▶ Play');cq('#creatorVoiceAudio').addEventListener('timeupdate',e=>setPreviewScene(previewSceneForTime(e.target.currentTime)));cq('#creatorVoiceAudio').addEventListener('ended',()=>{cq('#creatorAmbientAudio').pause();cq('#creatorPreviewPlay').textContent='▶ Replay'});
initCreator().catch(err=>toast('Creator could not load: '+err.message));
})();
