(()=>{
const SERIES_API='/api/series';
let catalog=[];let currentSeries=null;let currentEpisode=null;
const device=()=>localStorage.getItem('mr_device_id')||'';
const css=`
#seriesModal{position:fixed;z-index:140;inset:0;background:rgba(0,0,0,.82);display:none;align-items:flex-end;justify-content:center;padding:12px}#seriesModal.open{display:flex}.seriesSheet{width:min(780px,100%);max-height:92vh;overflow:auto;background:#0e131f;border:1px solid #33405a;border-radius:22px;padding:18px;box-shadow:0 30px 100px #000}.seriesHead{display:flex;gap:12px;align-items:flex-start;justify-content:space-between}.seriesHead h3{font-size:27px;margin:2px 0}.seriesMeta{color:#aeb7c9;margin:5px 0 12px}.episodeRows{display:grid;gap:8px}.episodeRow{display:grid;grid-template-columns:54px 1fr auto;gap:10px;align-items:center;background:#121a29;border:1px solid #28334a;border-radius:13px;padding:10px}.epNum{font-weight:950;color:#ffd05a}.epTitle{font-weight:800}.epStatus{font-size:12px;color:#9eabc1}.epBadge{font-size:11px;border:1px solid #44506a;border-radius:999px;padding:4px 7px}.epBadge.free{color:#bff5d8;border-color:#28744e}.epBadge.pending{color:#ffce87;border-color:#7c5b2b}.seriesBtn{border:1px solid #394861;background:#1a2232;color:#fff;border-radius:10px;padding:8px 10px;cursor:pointer}.seriesBtn[disabled]{opacity:.5;cursor:not-allowed}.seriesBtn.gold{background:#ffd05a;color:#111;border-color:#ffd05a;font-weight:900}.seriesCardBtn{width:100%;margin-top:7px;border:1px solid #3a4760;background:#182033;color:#fff;border-radius:10px;padding:8px;cursor:pointer}.realVideoNotice{background:#161c29;border:1px solid #36445f;border-radius:12px;padding:10px;margin:10px 0;color:#cad3e4}.videoBox{display:none;margin:12px 0}.videoBox.open{display:block}.videoBox video{width:100%;max-height:68vh;background:#000;border-radius:15px}.videoMessage{font-size:13px;color:#aab4c7;margin-top:7px}@media(max-width:560px){.episodeRow{grid-template-columns:44px 1fr}.episodeRow .seriesBtn{grid-column:1/-1;width:100%}.seriesSheet{padding:14px}}
`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
const modal=document.createElement('div');modal.id='seriesModal';modal.innerHTML=`<div class="seriesSheet"><div class="seriesHead"><div><div class="tiny">MAGNANIMOUS REELS · SEASON 1</div><h3 id="seriesTitle">Series</h3><div class="seriesMeta" id="seriesMeta"></div></div><button class="seriesBtn" id="seriesClose">✕</button></div><div class="realVideoNotice" id="seriesNotice"></div><div class="videoBox" id="seriesVideoBox"><video id="seriesVideo" controls playsinline></video><div class="videoMessage" id="seriesVideoMessage"></div></div><div class="episodeRows" id="episodeRows"></div></div>`;document.body.appendChild(modal);
const q=s=>document.querySelector(s);
q('#seriesClose').onclick=closeSeries;modal.addEventListener('click',e=>{if(e.target===modal)closeSeries()});
function closeSeries(){q('#seriesVideo').pause();q('#seriesVideo').removeAttribute('src');q('#seriesVideoBox').classList.remove('open');modal.classList.remove('open')}
function decorateGrid(){document.querySelectorAll('#grid .card').forEach(card=>{if(card.querySelector('.seriesCardBtn'))return;let p=card.querySelector('[data-play]');if(!p)return;let sid=Number(p.dataset.play);let s=catalog.find(x=>x.series_id===sid);if(!s)return;let b=document.createElement('button');b.className='seriesCardBtn';b.textContent=`📺 ${s.episode_count} Episodes · Season ${s.season}`;b.onclick=e=>{e.stopPropagation();openSeries(sid)};card.querySelector('.ct')?.appendChild(b);let small=card.querySelector('.ct small');if(small)small.textContent=`${s.category} · ${s.episode_count}-episode series`;});}
const obs=new MutationObserver(decorateGrid);let grid=q('#grid');if(grid)obs.observe(grid,{childList:true,subtree:true});
async function loadCatalog(){let x=await fetch(SERIES_API,{cache:'no-store'}).then(r=>r.json());catalog=x.series||[];document.querySelectorAll('.badge').forEach(b=>{if(b.textContent.includes('First 3 reels free'))b.textContent='First 3 episodes of every series free'});let h=q('#series h2');if(h)h.textContent='60 Original Series · 10 Episodes Each';let sub=q('#series .sub');if(sub)sub.textContent='Every original pilot is now Season 1 of a ten-episode story. Episodes 1–3 are free. Real TV-style video is required before any paid episode can take coins.';decorateGrid();}
async function openSeries(id){let x=await fetch(`/api/series/${id}`,{cache:'no-store'}).then(r=>r.json());currentSeries=x.series;if(!currentSeries)return;q('#seriesTitle').textContent=currentSeries.title;q('#seriesMeta').textContent=`${currentSeries.category} · ${currentSeries.episode_count} episodes · Lead: ${currentSeries.lead}`;let ready=currentSeries.episodes.filter(e=>e.real_video_ready).length;q('#seriesNotice').innerHTML=`<b>Production target:</b> real moving 9:16 cinematic video with actors/characters, dialogue, facial movement, camera cuts, sound effects and music. <b>${ready}/${currentSeries.episode_count}</b> real-video episodes are rendered now. Motion-comic assets are preview fallback only, not the finished TV-style episode.`;q('#episodeRows').innerHTML=currentSeries.episodes.map(ep=>episodeHTML(ep)).join('');modal.classList.add('open')}
function episodeHTML(ep){let free=ep.episode_number<=3;let ready=ep.real_video_ready;let badge=free?(ready?'<span class="epBadge free">FREE</span>':'<span class="epBadge free">FREE WHEN READY</span>'):(ready?`<span class="epBadge">30 coins</span>`:'<span class="epBadge pending">NOT FOR SALE YET</span>');let action=ready?`<button class="seriesBtn gold" data-watch-ep="${ep.episode_number}">▶ Watch cinematic episode</button>`:(ep.episode_number===1?`<button class="seriesBtn" data-preview-pilot="${ep.episode_number}">▶ Free story preview</button>`:`<button class="seriesBtn" disabled>🎬 Cinematic video pending</button>`);return `<div class="episodeRow"><div class="epNum">EP ${ep.episode_number}</div><div><div class="epTitle">${escapeHTML(ep.title.replace(/^Episode \d+ — /,''))} ${badge}</div><div class="epStatus">${ready?'Cinematic video ready':'Story/script ready · awaiting real-video renderer'}</div></div>${action}</div>`}
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
modal.addEventListener('click',async e=>{let preview=e.target.closest('[data-preview-pilot]');if(preview&&currentSeries){closeSeries();let pilot=document.querySelector(`[data-play=\"${currentSeries.series_id}\"]`);pilot?.click();document.getElementById('watch')?.scrollIntoView({behavior:'smooth'});return}let b=e.target.closest('[data-watch-ep]');if(!b||!currentSeries)return;let epn=Number(b.dataset.watchEp);currentEpisode=epn;let detail=await fetch(`/api/series/${currentSeries.series_id}/episode/${epn}?device=${encodeURIComponent(device())}`,{cache:'no-store'}).then(r=>r.json());let ep=detail.episode;if(!ep?.access?.allowed){let u=await fetch('/api/series/unlock',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({device_id:device(),series_id:currentSeries.series_id,episode_number:epn})});let ux=await u.json();if(!u.ok){q('#seriesVideoMessage').textContent=ux.code==='INSUFFICIENT_COINS'?`You need ${ux.needed} coins. You have ${ux.coins}.`:'This episode is locked.';q('#seriesVideoBox').classList.add('open');return}}
 let v=q('#seriesVideo');v.src=`/series-video/${currentSeries.series_id}/${epn}.mp4?device=${encodeURIComponent(device())}`;q('#seriesVideoBox').classList.add('open');q('#seriesVideoMessage').textContent=`${currentSeries.title} · Episode ${epn}`;try{await v.play()}catch{q('#seriesVideoMessage').textContent+=' · Tap play to start.'}}
);
window.MagnanimousSeries={open:openSeries,refresh:loadCatalog};
loadCatalog().catch(()=>{});
})();

(()=>{
'use strict';
const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let installPrompt=null, renderSummary={total:600,ready:0,awaiting_capacity:600};
const style=document.createElement('style');
style.textContent=`
:focus-visible{outline:3px solid #ffd05a;outline-offset:3px}.anonPill{border:1px solid #2d6f50;background:#0d2118;color:#bff3d6;border-radius:999px;padding:7px 10px;font-size:12px;font-weight:800;white-space:nowrap}.heroActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:15px}.softBtn{border:1px solid #344158;background:#101725;color:#fff;border-radius:12px;padding:10px 13px;min-height:42px;cursor:pointer}.softBtn[disabled],.btn[disabled],.purchase[disabled]{opacity:.48;cursor:not-allowed}.readiness{margin-top:12px;background:#101725;border:1px solid #2d3850;border-radius:14px;padding:12px;max-width:780px}.readiness b{color:#ffd05a}.collectionGrid{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:12px}.collectionCard{background:#0d1018;border:1px solid #252c3c;border-radius:15px;overflow:hidden}.collectionCard img{width:100%;aspect-ratio:9/12;object-fit:cover}.collectionBody{padding:10px}.collectionBody h3{font-size:15px;margin:0 0 5px}.emptyState{background:#0d1018;border:1px dashed #344158;border-radius:16px;padding:20px;color:#aab1c0}.offlineBar{position:fixed;z-index:180;left:12px;right:12px;bottom:12px;background:#34191d;border:1px solid #7a323b;color:#ffd8dc;border-radius:12px;padding:10px 13px;text-align:center;display:none}.offlineBar.show{display:block}.toastX{position:fixed;z-index:190;left:50%;bottom:18px;transform:translateX(-50%);background:#101725;border:1px solid #45536f;color:#fff;padding:11px 15px;border-radius:12px;box-shadow:0 14px 50px #000;display:none;max-width:min(92vw,600px);text-align:center}.toastX.show{display:block}.mobileDock{display:none}.availabilityTag{font-size:11px;border:1px solid #63552c;color:#ffe09a;border-radius:999px;padding:4px 7px;display:inline-block;margin-left:5px}.previewLabel{position:absolute;z-index:4;top:22px;right:12px;background:rgba(0,0,0,.72);border:1px solid rgba(255,255,255,.18);padding:6px 9px;border-radius:999px;font-size:11px}.srOnly{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}@media(max-width:800px){body{padding-bottom:68px}.anonPill{order:2}.mobileDock{display:grid;grid-template-columns:repeat(5,1fr);position:fixed;z-index:120;left:0;right:0;bottom:0;background:rgba(5,6,10,.97);backdrop-filter:blur(16px);border-top:1px solid #252c3c;padding:6px max(5px,env(safe-area-inset-right)) calc(6px + env(safe-area-inset-bottom)) max(5px,env(safe-area-inset-left))}.mobileDock button{border:0;background:transparent;color:#d5dbea;padding:7px 2px;font-size:11px}.mobileDock button b{display:block;font-size:17px}.offlineBar{bottom:78px}.toastX{bottom:84px}}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{scroll-behavior:auto!important;animation-duration:.001ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important}}
`;
document.head.appendChild(style);

function toast(text){let e=q('#appToastX');if(!e){e=document.createElement('div');e.id='appToastX';e.className='toastX';e.setAttribute('role','status');e.setAttribute('aria-live','polite');document.body.appendChild(e)}e.textContent=text;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),3000)}
function goto(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'})}

function addShell(){
 const top=q('.topin'); if(top&&!q('#anonymousPill')){const pill=document.createElement('div');pill.id='anonymousPill';pill.className='anonPill';pill.textContent='Public · No sign-in required';pill.title='Watching, browsing, rewards, and story previews work without an account.';top.insertBefore(pill,top.querySelector('nav'))}
 const phone=q('#phone'); if(phone&&!q('#previewLabel')){let p=document.createElement('div');p.id='previewLabel';p.className='previewLabel';p.textContent='STORY PREVIEW';phone.appendChild(p)}
 const hero=q('.hero .wrap'); if(hero&&!q('#heroActions')){let x=document.createElement('div');x.id='heroActions';x.className='heroActions';x.innerHTML='<button class="softBtn" id="installAppBtn">＋ Install app</button><button class="softBtn" id="shareAppBtn">↗ Share Magnanimous Reels</button><button class="softBtn" id="openMyListBtn">♡ My List</button>';hero.appendChild(x);let r=document.createElement('div');r.id='renderReadiness';r.className='readiness';r.setAttribute('role','status');r.innerHTML='Checking cinematic episode readiness…';hero.appendChild(r)}
 if(!q('#myList')){const series=q('#series');series?.insertAdjacentHTML('afterend','<section class="section" id="myList"><div class="wrap"><h2>My List & Continue Watching</h2><p class="sub">Saved privately on this device. No account or sign-in required.</p><div id="continueGrid" class="collectionGrid"></div><div style="height:14px"></div><div id="myListGrid" class="collectionGrid"></div></div></section>')}
 if(!q('#offlineBar')){let e=document.createElement('div');e.id='offlineBar';e.className='offlineBar';e.setAttribute('role','alert');e.textContent='You are offline. Already cached pages may still open, but new media needs a connection.';document.body.appendChild(e)}
 if(!q('#mobileDock')){let d=document.createElement('nav');d.id='mobileDock';d.className='mobileDock';d.setAttribute('aria-label','Magnanimous Reels mobile navigation');d.innerHTML='<button data-dock="watch"><b>▶</b>Watch</button><button data-dock="series"><b>▦</b>Series</button><button data-dock="myList"><b>♡</b>My List</button><button data-dock="rewards"><b>★</b>Rewards</button><button data-dock="pricing"><b>🪙</b>Unlock</button>';document.body.appendChild(d)}
 const heroCopy=q('.hero p'); if(heroCopy)heroCopy.textContent='Original vertical story previews now, with 60 complete Season 1 story arcs prepared for cinematic production. Watch and browse publicly with no sign-in. Paid episode access stays closed until real cinematic video is actually ready.';
 const watchSub=q('#watch .sub'); if(watchSub)watchSub.textContent='Swipe up or use Next to explore free Episode 1 story previews. Full cinematic episodes appear in each series only after their real video render is complete.';
 const pd=q('#playerDesc'); if(pd)pd.textContent='Free Episode 1 story preview with synchronized narration and visual beats. Cinematic series video is labeled separately when rendered.';
 const welcome=qa('#rewards .reward').find(x=>/Welcome bonus/i.test(x.textContent)); if(welcome){let p=q('p',welcome);if(p)p.textContent='New anonymous viewers start with 90 coins immediately on this device. No sign-in required.'}
 const priceSub=q('#pricing .sub'); if(priceSub)priceSub.textContent='Pricing is transparent and already configured. Purchases remain disabled until premium cinematic episodes are actually available to watch.';
 const footer=q('.footer .wrap');if(footer&&!/No sign-in/.test(footer.textContent))footer.append(' · Public viewing · No sign-in required');
}

function getStories(){return fetch('/api/stories',{cache:'no-store'}).then(r=>r.ok?r.json():[])}
function getSeries(){return fetch('/api/series',{cache:'no-store'}).then(r=>r.ok?r.json():({series:[],render:{}}))}
function storyById(stories,id){return stories.find(s=>Number(s.id)===Number(id))}
function imgFor(s){return s?.scenes?.[0]?.tag?'/assets/'+s.scenes[0].tag+'.jpg':''}
function card(s,buttonText,attrs=''){return `<article class="collectionCard"><img loading="lazy" src="${esc(imgFor(s))}" alt="${esc(s?.title||'Story')} poster"><div class="collectionBody"><h3>${esc(s?.title||'Story')}</h3><div class="tiny">${esc(s?.category||'Magnanimous Reels')}</div><button class="btn" style="width:100%;margin-top:8px" ${attrs}>${esc(buttonText)}</button></div></article>`}
async function renderCollections(){
 const stories=await getStories().catch(()=>[]); const ids=JSON.parse(localStorage.getItem('mr_watchlist')||'[]').map(Number); const list=q('#myListGrid');
 if(list){const items=ids.map(id=>storyById(stories,id)).filter(Boolean);list.innerHTML=items.length?items.map(s=>card(s,'Open preview',`data-enh-play="${s.id}"`)).join(''):'<div class="emptyState">Your list is empty. Tap ♡ while previewing a story to save it here.</div>'}
 const c=q('#continueGrid'); const last=Number(localStorage.getItem('mr_last_story')||0); const s=storyById(stories,last); if(c)c.innerHTML=s?card(s,'Continue preview',`data-enh-play="${s.id}"`):'<div class="emptyState">Start any story preview and it will appear here for quick return.</div>';
}

function updateReadiness(){
 const ready=Number(renderSummary.ready||0), total=Number(renderSummary.total||600), premiumReady=ready>0; const e=q('#renderReadiness');
 if(e)e.innerHTML=premiumReady?`<b>${ready}/${total}</b> cinematic episodes are live. Finished video episodes are labeled clearly in their series.`:`<b>Production integrity:</b> ${ready}/${total} finished cinematic episode renders are live right now. Story previews work, but premium purchases stay disabled until finished cinematic episodes exist.`;
 qa('[data-buy]').forEach(b=>{b.disabled=!premiumReady;b.setAttribute('aria-disabled',String(!premiumReady));if(!premiumReady)b.title='Premium purchases open when finished cinematic episodes are live.'});
 const weekly=qa('[data-buy="weekly"]'); weekly.forEach(b=>{if(!premiumReady)b.textContent='Weekly pass · opens with premium video'});
 qa('[data-buy="coins150"]').forEach(b=>{if(!premiumReady)b.textContent='150 coins · opens with premium video'});qa('[data-buy="coins500"]').forEach(b=>{if(!premiumReady)b.textContent='500 coins · opens with premium video'});qa('[data-buy="coins1400"]').forEach(b=>{if(!premiumReady)b.textContent='1,400 coins · opens with premium video'});
}

function wire(){
 document.addEventListener('click',e=>{
  const dock=e.target.closest('[data-dock]');if(dock){goto(dock.dataset.dock);return}
  const enh=e.target.closest('[data-enh-play]');if(enh){let el=q(`[data-play="${enh.dataset.enhPlay}"]`);el?.click();goto('watch');return}
  if(e.target.closest('#openMyListBtn')){goto('myList');return}
  if(e.target.closest('#shareAppBtn')){share();return}
  if(e.target.closest('#installAppBtn')){install();return}
  const p=e.target.closest('[data-play]');if(p)localStorage.setItem('mr_last_story',p.dataset.play);
  if(e.target.closest('#listBtn'))setTimeout(renderCollections,20);
  const buy=e.target.closest('[data-buy]');if(buy&&Number(renderSummary.ready||0)===0){e.preventDefault();e.stopImmediatePropagation();toast('Premium purchases are paused until finished cinematic episodes are live. No charge was started.');}
 },true);
 const audio=q('#audio'); if(audio){audio.addEventListener('timeupdate',()=>{if(audio.currentTime>1)localStorage.setItem('mr_last_time',String(audio.currentTime))});audio.addEventListener('ended',()=>localStorage.removeItem('mr_last_time'))}
 q('#search')?.setAttribute('aria-label','Search Magnanimous Reels series'); q('#seek')?.setAttribute('aria-label','Story preview progress'); q('#speed')?.setAttribute('aria-label','Playback speed');
 qa('button').forEach(b=>{if(!b.getAttribute('type'))b.setAttribute('type','button')});
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;let b=q('#installAppBtn');if(b){b.disabled=false;b.textContent='＋ Install app'}});
 window.addEventListener('appinstalled',()=>{toast('Magnanimous Reels installed.');let b=q('#installAppBtn');if(b)b.textContent='✓ App installed'});
 window.addEventListener('online',network);window.addEventListener('offline',network);network();
 document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(e.key===' '){e.preventDefault();q('#playBtn')?.click()}if(e.key==='ArrowRight')q('#nextBtn')?.click();if(e.key==='ArrowLeft')q('#prevBtn')?.click();if(e.key.toLowerCase()==='m')q('#soundBtn')?.click();if(e.key==='Escape'){q('#closePay')?.click();q('#seriesClose')?.click();q('#creatorPreviewClose')?.click()}});
}
function network(){q('#offlineBar')?.classList.toggle('show',!navigator.onLine)}
async function share(){const data={title:'Magnanimous Reels',text:'Watch Magnanimous Reels — public short-drama previews and series, no sign-in required.',url:'https://iammagnanimousway.com/reels'};try{if(navigator.share)await navigator.share(data);else if(navigator.clipboard){await navigator.clipboard.writeText(data.url);toast('Magnanimous Reels link copied.')}else{toast(data.url)}}catch(e){if(e?.name!=='AbortError')toast('Share is unavailable on this browser.')}}
async function install(){if(installPrompt){await installPrompt.prompt();installPrompt=null;return}const ios=/iphone|ipad|ipod/i.test(navigator.userAgent||'');toast(ios?'On iPhone: tap Share, then “Add to Home Screen.”':'Use your browser menu and choose “Install app” or “Add to Home screen.”')}

async function init(){addShell();wire();await Promise.all([renderCollections(),getSeries().then(x=>{renderSummary=x.render||renderSummary;updateReadiness()}).catch(()=>updateReadiness())]);const mo=new MutationObserver(()=>{qa('.card [data-play]').forEach(b=>{if(!b.dataset.enhanced){b.dataset.enhanced='1';if(/Watch|Unlock/.test(b.textContent))b.textContent='▶ Preview Episode 1'}})});const grid=q('#grid');if(grid)mo.observe(grid,{childList:true,subtree:true});setTimeout(()=>{qa('.card [data-play]').forEach(b=>{b.dataset.enhanced='1';b.textContent='▶ Preview Episode 1'})},500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
