(()=>{
const SERIES_API='/api/series';
let catalog=[];let currentSeries=null;let currentEpisode=null;
const device=()=>localStorage.getItem('mr_device_id')||'';
const css=`
#seriesModal{position:fixed;z-index:140;inset:0;background:rgba(0,0,0,.82);display:none;align-items:flex-end;justify-content:center;padding:12px}#seriesModal.open{display:flex}.seriesSheet{width:min(780px,100%);max-height:92vh;overflow:auto;background:#0e131f;border:1px solid #33405a;border-radius:22px;padding:18px;box-shadow:0 30px 100px #000}.seriesHead{display:flex;gap:12px;align-items:flex-start;justify-content:space-between}.seriesHead h3{font-size:27px;margin:2px 0}.seriesMeta{color:#aeb7c9;margin:5px 0 12px}.episodeRows{display:grid;gap:8px}.episodeRow{display:grid;grid-template-columns:54px 1fr auto;gap:10px;align-items:center;background:#121a29;border:1px solid #28334a;border-radius:13px;padding:10px}.epNum{font-weight:950;color:#ffd05a}.epTitle{font-weight:800}.epStatus{font-size:12px;color:#9eabc1}.epBadge{font-size:11px;border:1px solid #44506a;border-radius:999px;padding:4px 7px}.epBadge.free{color:#bff5d8;border-color:#28744e}.epBadge.pending{color:#ffce87;border-color:#7c5b2b}.seriesBtn{border:1px solid #394861;background:#1a2232;color:#fff;border-radius:10px;padding:8px 10px;cursor:pointer}.seriesBtn[disabled]{opacity:.5;cursor:not-allowed}.seriesBtn.gold{background:#ffd05a;color:#111;border-color:#ffd05a;font-weight:900}.seriesCardBtn{width:100%;margin-top:7px;border:1px solid #3a4760;background:#182033;color:#fff;border-radius:10px;padding:8px;cursor:pointer}.realVideoNotice{background:#161c29;border:1px solid #36445f;border-radius:12px;padding:10px;margin:10px 0;color:#cad3e4}.videoBox{display:none;margin:12px 0}.videoBox.open{display:block}.videoBox video{width:100%;max-height:68vh;background:#000;border-radius:15px}.videoMessage{font-size:13px;color:#aab4c7;margin-top:7px}@media(max-width:560px){.episodeRow{grid-template-columns:44px 1fr}.episodeRow .seriesBtn{grid-column:1/-1;width:100%}.seriesSheet{padding:14px}}
`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
const modal=document.createElement('div');modal.id='seriesModal';modal.innerHTML=`<div class="seriesSheet"><div class="seriesHead"><div><div class="tiny">MAGNANIMOUS REELS · SEASON 1</div><h3 id="seriesTitle">Series</h3><div class="seriesMeta" id="seriesMeta"></div></div><button class="seriesBtn" id="seriesClose">✕</button></div><div class="realVideoNotice" id="seriesNotice"></div><div class="videoBox" id="seriesVideoBox"><video id="seriesVideo" controls playsinline></video><div class="videoMessage" id="seriesVideoMessage"></div></div><div class="episodeRows" id="episodeRows"></div></div>`;document.body.appendChild(modal);
const q=s=>document.querySelector(s);
q('#seriesClose').onclick=closeSeries;modal.addEventListener('click',e=>{if(e.target===modal)closeSeries()});
function closeSeries(){q('#seriesVideo').pause();q('#seriesVideo').removeAttribute('src');q('#seriesVideoBox').classList.remove('open');modal.classList.remove('open')}
function decorateGrid(){document.querySelectorAll('#grid .card').forEach(card=>{if(card.querySelector('.seriesCardBtn'))return;let p=card.querySelector('[data-play]');if(!p)return;let sid=Number(p.dataset.play);let s=catalog.find(x=>x.series_id===sid);if(!s)return;let b=document.createElement('button');b.className='seriesCardBtn';b.textContent=`📺 ${s.episode_count} Episodes · Season ${s.season}`;b.onclick=e=>{e.stopPropagation();openSeries(sid)};card.querySelector('.ct')?.appendChild(b);let small=card.querySelector('.ct small');if(small)small.textContent=`${s.category} · ${s.episode_count}-episode series`;});}
const obs=new MutationObserver(decorateGrid);let grid=q('#grid');if(grid)obs.observe(grid,{childList:true,subtree:true});
async function loadCatalog(){let x=await fetch(SERIES_API,{cache:'no-store'}).then(r=>r.json());catalog=x.series||[];document.querySelectorAll('.badge').forEach(b=>{if(b.textContent.includes('First 3 reels free'))b.textContent='First 3 episodes of every series free'});let h=q('#series h2');if(h)h.textContent='60 Original Series · 10 Episodes Each';let sub=q('#series .sub');if(sub)sub.textContent='Every original pilot is now Season 1 of a ten-episode story. Episodes 1–3 are free. Real TV-style video is required before any paid episode can take coins.';decorateGrid();}
async function openSeries(id){let x=await fetch(`/api/series/${id}`,{cache:'no-store'}).then(r=>r.json());currentSeries=x.series;if(!currentSeries)return;q('#seriesTitle').textContent=currentSeries.title;q('#seriesMeta').textContent=`${currentSeries.category} · ${currentSeries.episode_count} episodes · Lead: ${currentSeries.lead}`;let ready=currentSeries.episodes.filter(e=>e.real_video_ready).length;q('#seriesNotice').innerHTML=`<b>Production target:</b> real moving 9:16 cinematic video with actors/characters, dialogue, facial movement, camera cuts, sound effects and music. <b>${ready}/${currentSeries.episode_count}</b> real-video episodes are rendered now. Motion-comic assets are preview fallback only, not the finished TV-style episode.`;q('#episodeRows').innerHTML=currentSeries.episodes.map(ep=>episodeHTML(ep)).join('');modal.classList.add('open')}
function episodeHTML(ep){let free=ep.episode_number<=3;let ready=ep.real_video_ready;let badge=free?'<span class="epBadge free">FREE</span>':`<span class="epBadge">30 coins</span>`;let action=ready?`<button class="seriesBtn gold" data-watch-ep="${ep.episode_number}">▶ Watch</button>`:`<button class="seriesBtn" disabled>🎬 Real video pending</button>`;return `<div class="episodeRow"><div class="epNum">EP ${ep.episode_number}</div><div><div class="epTitle">${escapeHTML(ep.title.replace(/^Episode \d+ — /,''))} ${badge}</div><div class="epStatus">${ready?'Cinematic video ready':'Story/script ready · awaiting real-video renderer'}</div></div>${action}</div>`}
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
modal.addEventListener('click',async e=>{let b=e.target.closest('[data-watch-ep]');if(!b||!currentSeries)return;let epn=Number(b.dataset.watchEp);currentEpisode=epn;let detail=await fetch(`/api/series/${currentSeries.series_id}/episode/${epn}?device=${encodeURIComponent(device())}`,{cache:'no-store'}).then(r=>r.json());let ep=detail.episode;if(!ep?.access?.allowed){let u=await fetch('/api/series/unlock',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({device_id:device(),series_id:currentSeries.series_id,episode_number:epn})});let ux=await u.json();if(!u.ok){q('#seriesVideoMessage').textContent=ux.code==='INSUFFICIENT_COINS'?`You need ${ux.needed} coins. You have ${ux.coins}.`:'This episode is locked.';q('#seriesVideoBox').classList.add('open');return}}
 let v=q('#seriesVideo');v.src=`/series-video/${currentSeries.series_id}/${epn}.mp4?device=${encodeURIComponent(device())}`;q('#seriesVideoBox').classList.add('open');q('#seriesVideoMessage').textContent=`${currentSeries.title} · Episode ${epn}`;try{await v.play()}catch{q('#seriesVideoMessage').textContent+=' · Tap play to start.'}}
);
window.MagnanimousSeries={open:openSeries,refresh:loadCatalog};
loadCatalog().catch(()=>{});
})();
