'use client';
import {useEffect,useRef,useState} from 'react';
const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
const rtcConfig={iceServers:[{urls:'stun:stun.l.google.com:19302'}]};
export default function Phone(){
 const[token,setToken]=useState(''),[session,setSession]=useState(''),[joinId,setJoinId]=useState(''),[status,setStatus]=useState('Ready'),[muted,setMuted]=useState(false);const pc=useRef<RTCPeerConnection|null>(null);const stream=useRef<MediaStream|null>(null);const lastSignal=useRef(0);const remoteAudio=useRef<HTMLAudioElement>(null);const timer=useRef<any>(null);
 useEffect(()=>{const t=localStorage.getItem('iam_account_token')||'';setToken(t);return()=>{if(timer.current)clearInterval(timer.current);pc.current?.close();stream.current?.getTracks().forEach(x=>x.stop())}},[]);
 async function signal(id:string,kind:string,payload:any){await fetch(`${api}/api/phone/session/${id}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({kind,payload})})}
 async function setup(id:string,caller:boolean){setStatus('Requesting microphone…');const s=await navigator.mediaDevices.getUserMedia({audio:true});stream.current=s;const p=new RTCPeerConnection(rtcConfig);pc.current=p;s.getTracks().forEach(t=>p.addTrack(t,s));p.ontrack=e=>{if(remoteAudio.current)remoteAudio.current.srcObject=e.streams[0]};p.onicecandidate=e=>{if(e.candidate)signal(id,'candidate',e.candidate)};p.onconnectionstatechange=()=>setStatus(`Call: ${p.connectionState}`);if(caller){const offer=await p.createOffer();await p.setLocalDescription(offer);await signal(id,'offer',offer)}else await signal(id,'ready',null);poll(id,caller,p)}
 async function poll(id:string,caller:boolean,p:RTCPeerConnection){if(timer.current)clearInterval(timer.current);timer.current=setInterval(async()=>{const r=await fetch(`${api}/api/phone/session/${id}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)return;const d=await r.json();for(const x of d.signals||[]){if(x.id<=lastSignal.current)continue;lastSignal.current=x.id;const payload=JSON.parse(x.payload||'null');if(x.kind==='offer'&&!caller){await p.setRemoteDescription(payload);const answer=await p.createAnswer();await p.setLocalDescription(answer);await signal(id,'answer',answer)}else if(x.kind==='answer'&&caller){await p.setRemoteDescription(payload)}else if(x.kind==='candidate'&&payload){try{await p.addIceCandidate(payload)}catch{}}else if(x.kind==='hangup'){hangup()}}},1000)}
 async function create(){const r=await fetch(`${api}/api/phone/session`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({})});const d=await r.json();if(!r.ok){setStatus(d.detail||'Sign in required');return}setSession(d.session_id);setStatus('Share the session ID with the other I AM user.');await setup(d.session_id,true)}
 async function join(){if(!joinId)return;setSession(joinId);await setup(joinId,false)}
 async function hangup(){if(session)await signal(session,'hangup',null);pc.current?.close();stream.current?.getTracks().forEach(x=>x.stop());pc.current=null;setStatus('Call ended');if(timer.current)clearInterval(timer.current)}
 return <main style={{maxWidth:760,margin:'50px auto',padding:24,fontFamily:'system-ui'}}><p style={{opacity:.6}}>I AM MAGNANIMOUS WAY™</p><h1>I AM Phone</h1><p>Browser-to-browser Internet calling with CRM call logging and WebRTC signaling. This is the free Internet-phone layer; ordinary telephone numbers require a carrier.</p><audio ref={remoteAudio} autoPlay/><div style={{display:'grid',gap:12,marginTop:24}}><button onClick={create}>Start a Call</button><input placeholder="Paste call session ID" value={joinId} onChange={e=>setJoinId(e.target.value)}/><button onClick={join}>Join Call</button>{session&&<div style={{padding:16,border:'1px solid #ddd',borderRadius:12}}><b>Session ID</b><div style={{wordBreak:'break-all'}}>{session}</div></div>}<p>Status: <b>{status}</b></p>{session&&<div style={{display:'flex',gap:10}}><button onClick={()=>{stream.current?.getAudioTracks().forEach(t=>t.enabled=muted);setMuted(!muted)}}>{muted?'Unmute':'Mute'}</button><button onClick={hangup}>Hang Up</button></div>}</div><hr style={{margin:'30px 0'}}/><p><a href="/crm">CRM</a> · <a href="/leads">Lead Generator</a> · <a href="/">I AM Platform</a></p></main>;
}
