'use client';
import {FormEvent,useEffect,useState} from 'react';
import {getPlatformAuthToken} from '../lib/magnanimous-session';
const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
async function read(r:Response){const t=await r.text();try{return JSON.parse(t)}catch{return{detail:t||`Request failed (${r.status})`}}}
export default function VideoAgents(){
 const[token,setToken]=useState(''),[agents,setAgents]=useState<any[]>([]),[providers,setProviders]=useState<any>({}),[agentId,setAgentId]=useState('social-short'),[title,setTitle]=useState(''),[message,setMessage]=useState(''),[visual,setVisual]=useState('futuristic premium robotic animated, sleek holographic UI, credible business technology'),[story,setStory]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const t=getPlatformAuthToken();if(!t){location.href='/login';return}setToken(t);fetch(`${api}/api/video-agents`).then(read).then(d=>{setAgents(d.agents||[]);setProviders(d.providers||{})}).catch(()=>{})},[]);
 async function build(e:FormEvent){e.preventDefault();setBusy(true);setError('');setStory(null);try{const r=await fetch(`${api}/api/video-agents/storyboard`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({agent_id:agentId,title,message,visual_direction:visual,format:'9:16'})});const d=await read(r);if(!r.ok)throw new Error(d.detail||'Video agent failed.');setStory(d)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <main className="page"><header><div><a href="/video-studio">← Video Studio</a><small>MAGNANIMOUS MULTI-AGENT VIDEO</small><h1>Video Agents</h1><p>Choose a specialist agent, generate cinematic scenes free-first, then assemble them with the platform renderer. Premium avatar providers stay optional.</p></div><a className="back" href="/enterprise">Enterprise →</a></header>{error&&<div className="error">{error}</div>}
 <section className="agents">{agents.map(a=><button key={a.id} className={agentId===a.id?'active':''} onClick={()=>setAgentId(a.id)}><b>{a.name}</b><span>{a.role}</span><em>{a.ready?'READY':'PROVIDER NEEDED'}</em></button>)}</section>
 <section className="grid"><form onSubmit={build}><label>Video title<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Magnanimous AI — AI built to work"/></label><label>Message / script<textarea required rows={8} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Describe what the video should say…"/></label><label>Visual direction<textarea rows={4} value={visual} onChange={e=>setVisual(e.target.value)}/></label><button disabled={busy}>{busy?'DIRECTING SCENES…':'BUILD VIDEO STORYBOARD'}</button></form><aside><article><small>FREE-FIRST ENGINE</small><strong>{providers.free_cinematic?'ONLINE':'NOT CONFIGURED'}</strong><p>Cloudflare FLUX scenes + browser animation keep ordinary video creation from requiring a paid presenter provider.</p></article><article><small>HEYGEN</small><strong>{providers.heygen?'CONNECTED':'OPTIONAL'}</strong></article><article><small>TAVUS</small><strong>{providers.tavus?'CONNECTED':'OPTIONAL'}</strong></article></aside></section>
 {story&&<section className="story"><h2>{story.title}</h2><p>{story.agent?.name} • {story.format} • {story.scenes?.length||0} scenes</p><div className="scenes">{story.scenes?.map((s:any)=><article key={s.index}>{s.image_data_uri?<img src={s.image_data_uri} alt={`Scene ${s.index}`}/>:<div className="missing">Scene unavailable</div>}<small>SCENE {s.index}</small><b>{s.narration}</b>{s.error&&<em>{s.error}</em>}</article>)}</div><a className="studio" href="/video-studio">Open Video Studio to assemble →</a></section>}
 <style jsx>{`.page{min-height:100vh;background:#05080d;color:#eef8ff;padding:28px;font-family:Inter,system-ui;background-image:radial-gradient(circle at 15% 8%,rgba(39,213,255,.11),transparent 26%),radial-gradient(circle at 90% 30%,rgba(127,86,255,.12),transparent 30%)}header{max-width:1200px;margin:auto;display:flex;justify-content:space-between;gap:20px}header a,.studio{color:#74ddff;text-decoration:none}header small{display:block;margin-top:16px;color:#7192a5;letter-spacing:.18em;font-size:9px}h1{font-size:clamp(52px,8vw,92px);line-height:.9;margin:8px 0}header p{max-width:760px;color:#8aa4b3;line-height:1.6}.agents{max-width:1200px;margin:28px auto;display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.agents button,form,aside article,.story{background:rgba(10,17,27,.9);border:1px solid #22364a;border-radius:18px;color:#eaf7ff;padding:18px;text-align:left}.agents button{cursor:pointer}.agents button.active{border-color:#66ddff;box-shadow:0 0 0 1px #66ddff inset}.agents b,.agents span,.agents em{display:block}.agents span{color:#88a6b8;font-size:11px;margin:7px 0}.agents em{font-style:normal;color:#63efbc;font-size:9px}.grid{max-width:1200px;margin:auto;display:grid;grid-template-columns:1fr 330px;gap:12px}form label{display:block;color:#91adbd;font-size:11px;margin-bottom:13px}input,textarea{width:100%;box-sizing:border-box;margin-top:6px;background:#060c13;border:1px solid #29465d;border-radius:12px;padding:13px;color:white}form button{width:100%;background:#61dfff;border:0;border-radius:12px;padding:14px;font-weight:900;color:#06131b}aside{display:grid;gap:10px}aside small{color:#7596aa;font-size:9px;letter-spacing:.15em}aside strong{display:block;margin:7px 0;font-size:23px}aside p{color:#819aaa;font-size:11px;line-height:1.5}.error{max-width:1200px;margin:16px auto;background:#35141a;border:1px solid #6c303b;padding:12px;border-radius:10px}.story{max-width:1164px;margin:15px auto}.story>p{color:#87a3b4}.scenes{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.scenes article{background:#060c13;border:1px solid #1d3141;border-radius:13px;overflow:hidden;padding-bottom:12px}.scenes img,.missing{width:100%;aspect-ratio:9/16;object-fit:cover;background:#101923}.scenes small,.scenes b,.scenes em{display:block;padding:0 11px}.scenes small{margin-top:10px;color:#6fdfff;font-size:9px}.scenes b{font-size:11px;line-height:1.45;margin-top:6px}.scenes em{color:#ff9ca8;font-size:9px}.studio{display:inline-block;margin-top:15px}@media(max-width:850px){.agents{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}.scenes{grid-template-columns:1fr 1fr}}@media(max-width:520px){.page{padding:16px}.agents,.scenes{grid-template-columns:1fr}}`}</style></main>
}
