'use client';
import {useEffect,useMemo,useState} from 'react';
import {getPlatformAuthToken} from '../lib/magnanimous-session';

const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
async function read(r:Response){const t=await r.text();try{return JSON.parse(t)}catch{return{detail:t||`Request failed (${r.status})`}}}

export default function TravelAgencyPage(){
 const[token,setToken]=useState(''),[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const[origin,setOrigin]=useState('MNL'),[destination,setDestination]=useState('SIN'),[date,setDate]=useState('2026-10-15'),[results,setResults]=useState<any>(null);
 const[ownerMargin,setOwnerMargin]=useState(150),[resellerMarkup,setResellerMarkup]=useState(500),[resellerName,setResellerName]=useState(''),[resellers,setResellers]=useState<any[]>([]),[newKey,setNewKey]=useState('');
 useEffect(()=>{const t=getPlatformAuthToken();if(!t){location.href='/login';return}setToken(t)},[]);
 async function get(path:string){const r=await fetch(`${api}${path}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'}),d=await read(r);if(!r.ok)throw new Error(d.detail||'Request failed.');return d}
 useEffect(()=>{if(!token)return;Promise.all([get('/api/travel-agency/catalog'),get('/api/travel-agency/resellers').catch(()=>({resellers:[]}))]).then(([a,b])=>{setData(a);setOwnerMargin(a?.pricing_policy?.owner_margin_bps||150);setResellerMarkup(a?.pricing_policy?.reseller_default_markup_bps||500);setResellers(b.resellers||[])}).catch(e=>setError(e.message))},[token]);
 async function search(){setBusy(true);setError('');try{const r=await fetch(`${api}/api/travel-agency/search/flights`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({slices:[{origin:origin.toUpperCase(),destination:destination.toUpperCase(),departure_date:date}],passengers:[{type:'adult'}],cabin_class:'economy',max_connections:1})}),d=await read(r);if(!r.ok)throw new Error(d.detail||'Search failed.');setResults(d)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function savePricing(){setBusy(true);setError('');try{const r=await fetch(`${api}/api/travel-agency/pricing`,{method:'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({owner_margin_bps:Number(ownerMargin),reseller_default_markup_bps:Number(resellerMarkup)})}),d=await read(r);if(!r.ok)throw new Error(d.detail||'Pricing update failed.');setData((x:any)=>({...x,pricing_policy:d.pricing_policy}))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function addReseller(){if(!resellerName.trim())return;setBusy(true);setError('');try{const r=await fetch(`${api}/api/travel-agency/resellers`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({name:resellerName,markup_bps:Number(resellerMarkup)})}),d=await read(r);if(!r.ok)throw new Error(d.detail||'Reseller creation failed.');setResellers(x=>[d.reseller,...x]);setResellerName('')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function issueKey(id:string){setBusy(true);setError('');setNewKey('');try{const r=await fetch(`${api}/api/travel-agency/resellers/${id}/keys`,{method:'POST',headers:{Authorization:`Bearer ${token}`}}),d=await read(r);if(!r.ok)throw new Error(d.detail||'Key creation failed.');setNewKey(d.api_key)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const configured=useMemo(()=>((data?.suppliers||[]) as any[]).filter(x=>x.configured),[data]);
 return <main className="page">
  <header><div><small>MAGNANIMOUS TRAVEL AGENCY</small><h1>Find the best verified deal. Sell it twice.</h1><p>Magnanimous compares authorized travel supply, keeps supplier net rates private, adds your small source margin, and lets approved agents add their own markup through your distribution API.</p></div><nav><a href="/reservations">Reservations</a><a href="/b2b">B2B</a><a href="/connections">Connections</a></nav></header>
  {error&&<div className="error">{error}</div>}
  <section className="stats"><article><small>SUPPLIER TARGETS</small><b>{data?.summary?.suppliers||0}</b></article><article><small>TRAVEL SKILLS</small><b>{data?.summary?.skills||0}</b></article><article><small>CONFIGURED SOURCES</small><b>{configured.length}</b></article><article><small>OWNER MARGIN</small><b>{(ownerMargin/100).toFixed(2)}%</b></article></section>
  <section className="grid"><article className="panel"><small>LIVE FLIGHT SEARCH</small><h2>Compare authorized supply</h2><div className="fields"><input value={origin} onChange={e=>setOrigin(e.target.value)} maxLength={3}/><input value={destination} onChange={e=>setDestination(e.target.value)} maxLength={3}/><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><button onClick={search} disabled={busy}>{busy?'Searching…':'Search live deals'}</button>{results?.groups?.map((g:any)=><div className="deal" key={g.currency}><b>{g.proof_label}</b>{g.best&&<><h3>{g.best.currency} {g.best.sell_amount}</h3><p>{g.best.supplier} · {g.best.refundable?'Refundable':'Rules apply'}</p></>}</div>)}</article>
  <article className="panel"><small>PRICE WATERFALL</small><h2>Small source margin + reseller freedom</h2><label>Magnanimous owner margin (basis points)<input type="number" value={ownerMargin} onChange={e=>setOwnerMargin(Number(e.target.value))}/></label><label>Default reseller markup (basis points)<input type="number" value={resellerMarkup} onChange={e=>setResellerMarkup(Number(e.target.value))}/></label><button onClick={savePricing} disabled={busy}>Save pricing policy</button><p className="muted">100 basis points = 1%. Raw supplier net price remains private. Resellers receive your wholesale price and can add their approved markup.</p></article></section>
  <section className="panel"><small>SUPPLY MESH</small><h2>Wholesale, GDS/NDC, bedbanks and benchmarks</h2><div className="cards">{(data?.suppliers||[]).map((s:any)=><article key={s.id} className={s.configured?'ready':''}><b>{s.name}</b><span>{s.products.join(' · ')}</span><p>{s.role}</p><em>{s.configured?'CREDENTIALS PRESENT':s.adapter.replaceAll('-',' ').toUpperCase()}</em></article>)}</div></section>
  <section className="grid"><article className="panel"><small>B2B RESELLERS</small><h2>Let other agencies sell your source</h2><div className="inline"><input placeholder="Reseller / agency name" value={resellerName} onChange={e=>setResellerName(e.target.value)}/><button onClick={addReseller} disabled={busy}>Add</button></div>{resellers.map(r=><div className="reseller" key={r.id}><div><b>{r.name}</b><span>{(r.markup_bps/100).toFixed(2)}% markup</span></div><button onClick={()=>issueKey(r.id)} disabled={busy}>Issue API key</button></div>)}{newKey&&<div className="key"><b>Copy this key now — shown once</b><code>{newKey}</code></div>}</article>
  <article className="panel"><small>DOWNSTREAM SOURCE API</small><h2>Magnanimous becomes the wholesaler interface</h2><p><code>GET /api/travel-source/v1/catalog</code></p><p><code>POST /api/travel-source/v1/search/flights</code></p><p className="muted">Downstream agents never receive supplier credentials or raw supplier net cost. Booking remains authority-gated through the reservation service.</p></article></section>
  <style jsx>{`
   .page{min-height:100vh;background:#05090d;color:#edf7fa;font-family:Inter,system-ui,sans-serif;padding:28px}header{max-width:1320px;margin:auto;display:flex;justify-content:space-between;gap:24px;align-items:end;padding:30px 0}small{color:#65e9b1;font-weight:900;letter-spacing:.14em}h1{font-size:clamp(38px,5.5vw,70px);margin:6px 0}header p,.muted{color:#91a7b1;line-height:1.6;max-width:900px}nav{display:flex;gap:8px;flex-wrap:wrap}a{color:#d9edf5;text-decoration:none;border:1px solid #29404b;padding:10px;border-radius:9px}.stats{max-width:1320px;margin:auto;display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.stats article,.panel{border:1px solid #203a46;background:#081118;border-radius:16px;padding:18px}.stats b{display:block;font-size:30px;margin-top:8px}.grid{max-width:1320px;margin:14px auto;display:grid;grid-template-columns:1fr 1fr;gap:14px}.panel{max-width:1284px;margin:14px auto}.fields{display:grid;grid-template-columns:1fr 1fr 1.4fr;gap:8px}input,button{box-sizing:border-box;width:100%;padding:11px;border:1px solid #2a4652;border-radius:10px;background:#07151d;color:#eef9fc}button{background:#12462f;border-color:#2c845c;color:#c9ffe5;font-weight:900;cursor:pointer}label{display:block;color:#9db1ba;font-size:12px;margin:10px 0}label input{margin-top:5px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.cards article{border:1px solid #263943;border-radius:11px;padding:11px;background:#071018}.cards article.ready{border-color:#2b7654}.cards b,.cards span,.cards em{display:block}.cards span{font-size:10px;color:#70d9ad;margin-top:3px}.cards p{font-size:11px;color:#8da1aa}.cards em{font-style:normal;font-size:9px;color:#dfa873}.ready em{color:#6ce8ab}.deal,.key{margin-top:12px;border:1px solid #2b7654;background:#0a1b14;border-radius:12px;padding:12px}.deal h3{font-size:28px;margin:8px 0}.inline{display:grid;grid-template-columns:1fr 110px;gap:8px}.reseller{display:flex;justify-content:space-between;gap:10px;align-items:center;border-top:1px solid #20333c;padding:10px 0}.reseller span{display:block;color:#7dddb1;font-size:10px}.reseller button{width:auto}.key code{display:block;margin-top:8px;word-break:break-all;color:#c9ffe5}.error{max-width:1320px;margin:0 auto 12px;border:1px solid #793b49;background:#2b1018;padding:12px;border-radius:10px}@media(max-width:1000px){.stats,.cards{grid-template-columns:repeat(2,1fr)}}@media(max-width:720px){.page{padding:16px}header{display:block}.stats,.grid,.cards,.fields,.inline{grid-template-columns:1fr}}
  `}</style>
 </main>
}
