'use client';
import {useEffect,useState} from 'react';
const api=process.env.NEXT_PUBLIC_API_BASE_URL||'';
type Field={key:string;label:string;secret:boolean;required:boolean;set:boolean;source:string;updated_at?:number|null};
type Group={id:string;name:string;providers:string[];configured:boolean;fields:Field[]};
async function read(r:Response){const t=await r.text();try{return JSON.parse(t)}catch{return{error:t||`Request failed (${r.status})`}}}
export default function OwnerIntegrations(){
 const[token,setToken]=useState(''),[groups,setGroups]=useState<Group[]>([]),[values,setValues]=useState<Record<string,string>>({}),[busy,setBusy]=useState(''),[msg,setMsg]=useState(''),[error,setError]=useState('');
 async function load(t:string){setError('');const r=await fetch(`${api}/api/integrations/platform-credentials`,{headers:{Authorization:`Bearer ${t}`},cache:'no-store'}),d=await read(r);if(r.status===401||r.status===403){localStorage.removeItem('odin_admin_token');location.replace('/owner-login');return}if(!r.ok){setError(d.error||d.detail||'Unable to load provider vault.');return}setGroups(d.groups||[])}
 useEffect(()=>{const t=localStorage.getItem('odin_admin_token')||'';if(!t){location.replace('/owner-login');return}setToken(t);load(t)},[]);
 async function save(group:Group){const payload:Record<string,string>={};for(const field of group.fields){const v=(values[field.key]||'').trim();if(v)payload[field.key]=v}if(!Object.keys(payload).length){setError('Enter at least one value to save.');return}setBusy(group.id);setError('');setMsg('');const r=await fetch(`${api}/api/integrations/platform-credentials`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({values:payload})}),d=await read(r);if(!r.ok){setError(d.error||d.detail||'Unable to save credentials.')}else{setValues(v=>{const next={...v};group.fields.forEach(f=>delete next[f.key]);return next});setMsg(`${group.name} credentials saved encrypted in the owner vault.`);setGroups(d.groups||groups)}setBusy('')}
 async function remove(group:Group){const keys=group.fields.filter(f=>f.source==='vault').map(f=>f.key);if(!keys.length){setMsg(`${group.name} has no owner-vault values to remove.`);return}setBusy(group.id);setError('');const r=await fetch(`${api}/api/integrations/platform-credentials`,{method:'DELETE',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({keys})}),d=await read(r);if(!r.ok)setError(d.error||d.detail||'Unable to remove credentials.');else{setGroups(d.groups||groups);setMsg(`${group.name} owner-vault credentials removed.`)}setBusy('')}
 return <main><header><a href="/owner-center">← Owner Center</a><span>ENCRYPTED PLATFORM PROVIDER VAULT</span></header><section className="hero"><div><small>I AM MAGNANIMOUS WAY™</small><h1>Provider Setup</h1><p>Enter provider-issued credentials once. Values are encrypted server-side and are never returned to the browser after saving. Cloudflare deployment secrets, when present, remain higher priority.</p></div><div className="badges"><b>▣ OWNER ONLY</b><b>◆ ENCRYPTED AT REST</b><b>● SERVER SIDE</b></div></section>{msg&&<div className="msg ok">{msg}</div>}{error&&<div className="msg err">{error}</div>}<section className="grid">{groups.map(group=><article key={group.id}><div className="title"><div><small>{group.providers.join(' • ').toUpperCase()}</small><h2>{group.name}</h2></div><span className={group.configured?'ready':'missing'}>{group.configured?'READY':'SETUP'}</span></div>{group.fields.map(field=><label key={field.key}><span>{field.label}{field.required?' *':''}<em>{field.set?`SET • ${field.source.toUpperCase()}`:'NOT SET'}</em></span><input type={field.secret?'password':'text'} autoComplete="off" placeholder={field.set?'Enter a new value only to replace the saved value':'Enter provider credential'} value={values[field.key]||''} onChange={e=>setValues({...values,[field.key]:e.target.value})}/></label>)}<div className="actions"><button disabled={busy===group.id} onClick={()=>save(group)}>{busy===group.id?'SAVING…':'Save Encrypted'}</button><button className="remove" disabled={busy===group.id} onClick={()=>remove(group)}>Remove Vault Values</button></div></article>)}</section><section className="note"><b>Billing status</b><p>Stripe checkout and signed-webhook fulfillment are configured independently for the paid plans shown on the Pricing page. A Stripe Secret API Key is optional and adds advanced API functions such as direct Customer Portal session creation. Twilio and Tavus become active when their provider-issued credentials are saved here.</p></section><style jsx>{`
main{min-height:100vh;background:#060708;color:#f5ead7;padding:26px 34px 60px;font-family:Inter,system-ui,sans-serif;background-image:radial-gradient(circle at 75% 0,rgba(255,178,46,.08),transparent 32%)}header,.hero,.grid,.msg,.note{max-width:1350px;margin-left:auto;margin-right:auto}header{display:flex;justify-content:space-between;color:#a98a57;font-size:10px;letter-spacing:.17em}header a{color:#e6bd76;text-decoration:none}.hero{margin-top:28px;border:1px solid #594425;border-radius:20px;background:linear-gradient(135deg,#12100d,#090a0b);padding:32px;display:flex;justify-content:space-between;gap:30px}.hero small,.title small{color:#b9914e;font-size:9px;letter-spacing:.18em}.hero h1{font:700 clamp(40px,6vw,70px) Georgia,serif;color:#ffd88d;margin:5px 0 10px}.hero p{max-width:780px;color:#ad9d84;line-height:1.6}.badges{display:grid;align-content:center;gap:8px}.badges b{font-size:10px;letter-spacing:.1em;padding:10px 12px;border:1px solid #49391f;border-radius:8px;color:#d8b16e}.msg{margin-top:12px;padding:12px 14px;border-radius:10px}.ok{background:#0d1a10;border:1px solid #385d41;color:#a9efbb}.err{background:#251012;border:1px solid #673339;color:#ffb9bf}.grid{margin-top:14px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.grid article{background:#0b0c0d;border:1px solid #352b20;border-radius:16px;padding:20px}.title{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.title h2{margin:4px 0 14px}.title>span{padding:6px 9px;border-radius:20px;font-size:9px;font-weight:900;letter-spacing:.1em}.ready{border:1px solid #356147;color:#88efab}.missing{border:1px solid #6a4c22;color:#e7bd6d}label{display:block;margin:12px 0}label>span{display:flex;justify-content:space-between;gap:10px;color:#b7aa96;font-size:11px}label em{font-style:normal;color:#6f7a70;font-size:9px}input{width:100%;box-sizing:border-box;margin-top:6px;padding:12px;border:1px solid #3c3328;border-radius:9px;background:#070809;color:#fff0d7;outline:none}input:focus{border-color:#a97a35}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:15px}button{border:1px solid #9b722f;background:#8d5b16;color:#fff1cf;padding:10px 13px;border-radius:9px;font-weight:800;cursor:pointer}.remove{background:#171311;border-color:#4e4032;color:#bca98e}button:disabled{opacity:.55}.note{margin-top:14px;border:1px solid #2e353b;background:#0b0e10;border-radius:14px;padding:18px}.note b{color:#d8b36f}.note p{color:#92999e;line-height:1.55}@media(max-width:850px){main{padding:20px 14px 40px}.hero{display:block}.badges{margin-top:18px}.grid{grid-template-columns:1fr}header{gap:12px;flex-wrap:wrap}}
`}</style></main>}
